### ISSUE TITLE
Make git source repository and ref configurable

### ISSUE THREAD

**Issue by NobbZ** [elixir-lsp/vscode-elixir-ls#1]
Currently the Language server is built from git on activation of the plugin, if and only if there has not yet been a checkout/clone.

This happens from master and a the hardcoded URL of the [new LSPs home](https://github.com/elixir-lsp/elixir-ls).

This need to be configurable.

**Comment by lukaszsamson** [comment]
Is that still relevant?

**Comment by NobbZ** [comment]
As I am not using VScode anymore, it is not relevant anymore for me. Not sure though if it might be relevant for others.

**Comment by lukaszsamson** [comment]
Closing as OP is no longer interested in that feature
