### ISSUE TITLE
Spec hints show up from imported file

### ISSUE THREAD

**Issue by bpardee** [elixir-lsp/vscode-elixir-ls#100]
This is probably best to show with an example.  You can see in the following that spec hints show up at lines 6 and 11:
![image](https://user-images.githubusercontent.com/308614/83469491-d7e88b80-a44d-11ea-8bfd-5db514991561.png)
But these hints actually belong to the imported file:
![image](https://user-images.githubusercontent.com/308614/83469718-69f09400-a44e-11ea-94fb-5f4003bbe491.png)

**Comment by jayjun** [comment]
I cannot reproduce with 0.4.0. Can you upload a sample repo?

**Comment by bpardee** [comment]
Definitely using 0.4.0 but will try to trim down the repo and reproduce but it might be a couple days

**Comment by lukaszsamson** [comment]
@bpardee ping

**Comment by lukaszsamson** [comment]
Closing due to no response from OP
