### ISSUE TITLE
Go to definition does not work

### ISSUE THREAD

**Issue by nocivus** [elixir-lsp/vscode-elixir-ls#109]
### Description

Go to definition does not work (using OSX). ElixirLS starts properly and shows symbols being added/indexed.

![image](https://user-images.githubusercontent.com/3353/84792922-629fbd80-afec-11ea-85e7-17c810607f8a.png)

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] 
* Elixir 1.10.2 (compiled with Erlang/OTP 21)
 *VSCode ElixirLS version: 0.4.0
* Operating System Version: darwin 19.4.0
  
### Installed extensions

![image](https://user-images.githubusercontent.com/3353/84792965-6d5a5280-afec-11ea-81af-a8d4e52c622c.png)

### Troubleshooting

- Restarted editor. Same problem.
- Removed `.elixir_ls` directory. Same problem.

Any help appreciated :)
Thanks.

**Comment by axelson** [comment]
Is your `mix.exs` in your workspace root?

**Comment by nocivus** [comment]
yes

**Comment by nocivus** [comment]
Think between the "User", "Workspace", and project specific settings i had a "." in the Project Dir configuration. Removed it and it started working again. 

No symbol lookup though (CMD+T in VSCode), is that supposed to be working?

**Comment by axelson** [comment]
I'm glad that you got it working! The next version will have more warnings when the mix.exs cannot be found.

> No symbol lookup though (CMD+T in VSCode), is that supposed to be working?

Currently if you have dialyzer disabled, than that is expected. But the next release will support symbol lookup with dialyzer disabled.
