### ISSUE TITLE
Feature: a list of functions in the current module

### ISSUE THREAD

**Issue by aesmail** [elixir-lsp/vscode-elixir-ls#113]
It would be extremely useful to have a list of the functions in a specific module. Maybe ordered both by order of definition in the module and alphabetically.

Sometimes when code bases become large enough and modules tend to accumulate functions, it's super useful to glance somewhere and see what lists exist in the module you're working with.

I'm not sure if this actually already exists. If it does, I apologize for this issue and I would love to know how to activate it.

Thanks for this awesome extension.

**Comment by jayjun** [comment]
You can enable [Outline View](https://code.visualstudio.com/docs/getstarted/userinterface#_outline-view) in File Explorer then _Sort By: Name_.

**Comment by aesmail** [comment]
uff! You are kidding me! How come I've never come across this before!
Thank you @jayjun
