### ISSUE TITLE
Make ElixirLS available on the Open VSX marketplace mirror

### ISSUE THREAD

**Issue by foggy1** [elixir-lsp/vscode-elixir-ls#118]
Sorry to break from template, but this issue relates to uploading to the Open VSX marketplace. I posted on the forums but this seemed a more appropriate place to track the done state.

Users of VSCodium, as of latest version (post-1.46.0) don't have access to the Microsoft Marketplace, and instead are pointed at a [separate mirror](https://open-vsx.org/). Having this package available on that mirror would be very welcome.

**Comment by axelson** [comment]
Cool, this seems like a good idea.

Published the first version! :confetti_ball:  https://open-vsx.org/extension/elixir-lsp/elixir-ls

Also in the process of claiming the namespace https://github.com/eclipse/open-vsx.org/issues/71
