### ISSUE TITLE
Treat typespecs as documentation for syntax highlighting

### ISSUE THREAD

**Issue by joecorkerton** [elixir-lsp/vscode-elixir-ls#12]
Is there any chance this PR can be merged here https://github.com/JakeBecker/vscode-elixir-ls/pull/55 ?

I think the current syntax highlighting is not optimal, with the spec highlighting at the same 'level' as regular code. Having a more toned down highlighting would be ideal

**Comment by axelson** [comment]
I don't think typspecs should be treated as pure documentation (i.e. strings) since they have their own syntax. However this can be accomplished for you locally with a local override: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by lukaszsamson** [comment]
For future reference as noted in https://github.com/elixir-lsp/vscode-elixir-ls/pull/263

> However this can be accomplished for you locally with a local override: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme 

This comment is incorrect. You can see that VSCode tokenizes `@spec` as `variable.other.readwrite.module.elixir`. There is no specific tokenization rule for typespecs, therefore no way to create a local override.

**Comment by lukaszsamson** [comment]
Tracked in https://github.com/elixir-lsp/vscode-elixir-ls/issues/311
