### ISSUE TITLE
Feature Request: Support `.formatter` config

### ISSUE THREAD

**Issue by jtrees** [elixir-lsp/vscode-elixir-ls#120]
The `.formatter` file is used by `mix format` to configure what is formatted and how it is formatted.

I am particularly interested in the the `inputs` key because it allows you to provide a whitelist of files to be formatted.

vscode-elixir-ls should respect this config and not format files that aren't included in the whitelist.

**Comment by jayjun** [comment]
ElixirLS respects `.formatter.exs` since https://github.com/elixir-lsp/elixir-ls/commit/5042cc937d1fb7794606eb7b51a6171d80c78ae7.

Did you name the file correctly? If the problem persists, please push a sample repo. Your project might have an unusual layout and ElixirLS can’t locate the file.

**Comment by pfitz** [comment]
We do have a ```.formatter.exs``` at the root of the project. And excluded a directory (wich includes the ```test_helper.exs```) which we do not want to get formatted. My setting is to format on save and it does format the  excluded ```test_helper.exs```. 

Content of the ```formatter.exs``` is : 
```
[
  # Note: `test_helper.exs` is deliberately excluded.
  inputs: [
    "mix.exs",
    "{config,lib}/**/*.{ex,exs}",
    "config/test/project/**/*.{ex.exs}"
  ]
]
```
which from our point of view should exclude ```test/test_helper.exs```

**Comment by NobbZ** [comment]
Indeed it seems as if the configuration is respected, though the name of the file to format is not filtered against any include/exclude-lists.

And in my opinion it makes sense, that the LS formats whatever it is asked to format (I might be alone with this opinion). You should configure your editor to not format this particular file on save (and if its only as a temporary workaround).

**Comment by pfitz** [comment]
Since there is no white or blacklist function (I know of) for the setting ```Format on Save``` from VSCode is there by any chance a way to configure it in vscode-elixir-ls?

**Comment by jayjun** [comment]
@pfitz You’re right, `:inputs` is ignored. https://github.com/elixir-lsp/elixir-ls/pull/315 should fix that.
