### ISSUE TITLE
I get two results for everything

### ISSUE THREAD

**Issue by krainboltgreene** [elixir-lsp/vscode-elixir-ls#122]
* Elixir & Erlang versions (elixir --version): Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] Elixir 1.10.3 (compiled with Erlang/OTP 21)
  * VSCode ElixirLS version: 0.5.0
  * Operating System Version: darwin 19.5.0

  - [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues
  - [X] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

When I look at a suggestion or information or warning, I get two results
![Screen Shot 2020-07-11 at 2 21 57 PM](https://user-images.githubusercontent.com/334809/87234047-11cc7c00-c382-11ea-9d4e-b72938eea4a3.png)

![Screen Shot 2020-07-11 at 2 23 36 PM](https://user-images.githubusercontent.com/334809/87234055-214bc500-c382-11ea-9e82-010d097d3724.png)

**Comment by krainboltgreene** [comment]
Okay, now it's getting weird:
![Screen Shot 2020-07-12 at 2 01 46 PM](https://user-images.githubusercontent.com/334809/87256523-515d9b80-c448-11ea-90dc-8767f0a586a1.png)


The top result is correct, but the bottom result is incorrect.

**Comment by krainboltgreene** [comment]
I was able to "fix" the issue by calling that very function above that line. After deleting the newly called function, I now see the identical 2 details.

**Comment by axelson** [comment]
What kind of project setup do you have? Do you have multiple folders in your workspace? Is it an umbrella project? Do you get this on all elixir projects or just that specific project?

**Comment by krainboltgreene** [comment]
One folder per workspace, two projects so far, neither an umbrella.

**Comment by krainboltgreene** [comment]
FWIW, if there's a question about this I can answer I will answer. I have a lot of time to debug this.

**Comment by jayjun** [comment]
Are there two instances of ElixirLS running? Possibly related to #125.

**Comment by lukaszsamson** [comment]
Closing as this is most likely fixed now
