### ISSUE TITLE
VScode merge conflicts crush

### ISSUE THREAD

**Issue by TrueDoleron** [elixir-lsp/vscode-elixir-ls#123]
In last version VScode ElixirLS crush Merge Conflicts Tool. ElixirLS disable or hidden command panel Merge Conflicts Tool and  only after off ElixirLS, merge conflicts tool works :/
![Снимок экрана от 2020-07-14 15-00-57](https://user-images.githubusercontent.com/17336921/87423677-5d319500-c5e3-11ea-8ede-fbd9eb395591.png)
![Снимок экрана от 2020-07-14 15-01-20](https://user-images.githubusercontent.com/17336921/87423683-5efb5880-c5e3-11ea-8a7c-9701f09b4462.png)

**Comment by jayjun** [comment]
I can reproduce this if _Suggest Specs_ is enabled (make sure Dialyzer is enabled too). For a temporary workaround, you can disable _Suggest Specs_ for now.

```jsonc
// settings.json
{
  "elixirLS.suggestSpecs": false
}
```

**Comment by TrueDoleron** [comment]
@jayjun ty, that fix errors
