### ISSUE TITLE
False-positive conflict message in OpenVSX

### ISSUE THREAD

**Issue by c06b0617-309e-4b17-a4f2-ad80ebce85f0** [elixir-lsp/vscode-elixir-ls#135]
https://github.com/elixir-lsp/vscode-elixir-ls/blob/8aedd5f33fc9fc79e16f722ca9eb54c34953f0ae/src/extension.ts#L159

This extension is called [`elixir-lsp.elixir-ls`](https://open-vsx.org/extension/elixir-lsp/elixir-ls) in the open vsx registry, so when you install it complains about conflicting with itself

It doesn't break anything though.

**Comment by c06b0617-309e-4b17-a4f2-ad80ebce85f0** [comment]
@axelson

**Comment by axelson** [comment]
@c06b0617-309e-4b17-a4f2-ad80ebce85f0 thanks for the report! Fixed.
