### ISSUE TITLE
Better indentation in `.html.eex` autocompletion

### ISSUE THREAD

**Issue by clmay** [elixir-lsp/vscode-elixir-ls#140]
Phew,

```
"emmet.includeLanguages": {
  "html-eex": "html"
}
```

was exactly what I needed to get HTML completion working... but I have one more small, niggling problem with it still.

When the language is set to `html` instead of `html-eex`, creating a new node in the DOM and hitting return automatically adds a level of indentation, and moves the closing tag behind an extra newline, as well.

But when the language is set to `html-eex`, this behavior is disabled, so using a completion for e.g. `<ul>` will add the closing tag, but a return will add a newline and leave the cursor in front of the closing tag on the next line... no extra newline or indentation fanciness.

What would it take to make the behavior match the `html` autocompletion behavior in this final respect?

**Comment by axelson** [comment]
I've added emmet instructions to the README in https://github.com/elixir-lsp/vscode-elixir-ls/pull/141

> But when the language is set to html-eex, this behavior is disabled, so using a completion for e.g. <ul> will add the closing tag, but a return will add a newline and leave the cursor in front of the closing tag on the next line... no extra newline or indentation fanciness.
>
> What would it take to make the behavior match the html autocompletion behavior in this final respect?

I'm not sure what this would involve so more research is needed.

**Comment by clmay** [comment]
Let me know, I'm not sure I'm familiar enough with VS Code extensions to know how to accomplish this, or even where to look. But if you're able to suggest a starting place I'd be happy to do what I can.

**Comment by axelson** [comment]
Unfortunately I'm not either which is why I've marked it as help wanted.

**Comment by clmay** [comment]
Makes sense—no problem. :) Maybe someone will chime in.

**Comment by type1fool** [comment]
Hey gang. I'm here thanks to the [Thinking Elixir](https://thinkingelixir.com/podcast-episodes/028-depviz-and-elixirls-with-jason-axelson/) interview with @axelson. Aloha!

I've been annoyed by this issue, too. I started poking around the docs to see if I could help. After a little bit of digging, it seems [eex-language-configuration.json](https://github.com/elixir-lsp/vscode-elixir-ls/blob/master/eex-language-configuration.json) might need [indentation rules](https://code.visualstudio.com/api/language-extensions/language-configuration-guide):

```json
...
  "indentationRules": {
    "increaseIndentPattern": "^((?!\\/\\/).)*(\\{[^}\"'`]*|\\([^)\"'`]*|\\[[^\\]\"'`]*)$",
    "decreaseIndentPattern": "^((?!.*?\\/\\*).*\\*/)?\\s*[\\}\\]].*$"
  }
...
```

I don't know how to test this locally. Is it possible those additional rules would fix this issue?

**Comment by clmay** [comment]
Unless someone can do it sooner, I can probably try to test these specific changes and maybe open a PR if it looks like they work. It looks like everything necessary to tweak the extension and load local changes is in the README, so I will give it a shot.

**Comment by axelson** [comment]
@type1fool hi :wave:! Hope you enjoyed the podcast :)

You can test locally by following the installation instructions: https://github.com/elixir-lsp/vscode-elixir-ls#installation

Those rules would definitely change the indentation support but I think you'd probably want more than just those.

**Comment by lukaszsamson** [comment]
html.eex is now effectively replaced by html.heex. If this is still an issue it would be best if it was addressed in https://github.com/phoenixframework/vscode-phoenix
