### ISSUE TITLE
Formatter (and maybe other things) not working

### ISSUE THREAD

**Issue by a8t** [elixir-lsp/vscode-elixir-ls#144]
Hi, first off I almost feel apologetic opening this as an issue since the error may be on my end. But, I can't find any other discussion area for this extension, so I'll open here.

The formatter no longer runs. When I try to format a `.ex` file, I get the message "There is no formatter for 'elixir' files installed". No combinations of settings seems to fix this.

Then, when I tried to use the Copy Debug Info command, I got this: `Command 'ElixirLS: Copy Debug Info' resulted in an error (command 'extension.copyDebugInfo' not found)`. But if all you need from that command is the following info, then I found it:

- Elixir 1.10.4 (compiled with Erlang/OTP 23)
- ElixirLS Extension v0.6.0 (i notice this says `jakebecker.exlisir-ls` and not `elixir-lsp.elixir-ls`)
- VS Code v1.49.3
- MacOS v10.14.6

Please let me know if there's any other info I can provide.

(also i've tried restarting VSCode and re-installing the extension several times, and also my computer.)

**Comment by a8t** [comment]
(also yes i've tried restarting VSCode and re-installing the extension several times – next i will try restarting my computer.)

**Comment by a8t** [comment]
Downgraded to 0.5.0 and it works. Upgraded back to 0.6.0 and it breaks again.

**Comment by jeramyRR** [comment]
How do you downgrade in VS Code?

**Comment by BlueHotDog** [comment]
Same issue here.

**Comment by a8t** [comment]
Closing my issue in favor of https://github.com/elixir-lsp/vscode-elixir-ls/issues/145
