### ISSUE TITLE
intellisense, CamelCase filtering doesn't seem to work in version 0.5.0 and greater

### ISSUE THREAD

**Issue by ddaugher** [elixir-lsp/vscode-elixir-ls#150]
typing 'ccc' in the Intellisense window, I would expect a value in the list with CustomerContactsController to be selected... two issues, the case of the input is not honored and the text input has to be exactly as the value in the list... e.g. typing 'CustomerC' will highlight the previously mentioned option.

The functionality works as I would expect in 0.4.0, but versions 0.5.0 and greater do not support this expectation.  Was this changed by design... I would expect it to do CamelCase filtering as that is the standard for VSCode Intellisense.

I have attached images showing the issue.

The following image shows the list available after activating intellisense (version 0.6.1 of ElixirLS)

<img width="548" alt="Screen Shot 2020-11-06 at 8 05 09 PM" src="https://user-images.githubusercontent.com/209234/98427618-e3c72200-206b-11eb-8924-abd6c8c59acd.png">

This image shows after typing '.ccc'... everything is removed from list (version 0.6.1 of ElixirLS)

<img width="363" alt="Screen Shot 2020-11-06 at 8 05 27 PM" src="https://user-images.githubusercontent.com/209234/98427690-14a75700-206c-11eb-95ea-87a985225229.png">

This image shows what I expect to happen (version 0.4.0 of ElixirLS)
<img width="565" alt="Screen Shot 2020-11-06 at 8 08 02 PM" src="https://user-images.githubusercontent.com/209234/98427712-2ee13500-206c-11eb-8a92-50a67b39fcdf.png">

**Comment by axelson** [comment]
ElixirLS never truly supported camel case filtering. I believe this is what was happening previously:
* You type `.`: ElixirLS returns the list of modules in the first screenshot
* You type `c`: I think ElixirLS then returns only the modules that start with `c`
* You type `ccc`: ElixirLS returns an empty list and VSCode does client-side filtering

The ElixirLS behavior was changed in https://github.com/elixir-lsp/elixir-ls/pull/259 to reduce the number of false-positive completions, in particular for `do`:
![82835207-10d99c80-9e5f-11ea-82b1-b745707ecf74](https://user-images.githubusercontent.com/9973/98482957-dd8a9000-21a8-11eb-8b2f-93ce18f52fab.png)

If you have suggestions for different behavior that will solve that issue and still solve the issue you present here then we can look at making that change. Possibly we could add a configuration option to control `isComplete` but we'd have to look at the utility of that.

**Comment by ddaugher** [comment]
thank you for the explanation... I will put some thought into how I would prefer this to work. I can work around it for now, but it was a nice side effect that I got used to.  thanks!
