### ISSUE TITLE
How to provide startup flags to ElixirLS.LanguageServer.CLI.main() 

### ISSUE THREAD

**Issue by syfgkjasdkn** [elixir-lsp/vscode-elixir-ls#151]
👋

How would one provide language server startup flags similar to https://github.com/elixir-lsp/elixir-ls/issues/96 but in vscode instead of vim?

**Comment by axelson** [comment]
Hi @syfgkjasdkn

**Comment by syfgkjasdkn** [comment]
Thank you! I'll go with the second approach for now.
