### ISSUE TITLE
Auto formatter inserts lots of empty lines at beginning of some modules

### ISSUE THREAD

**Issue by samuelventura** [elixir-lsp/vscode-elixir-ls#169]
### Description

Auto formatter inserts lots of empty lines at beginning of some modules.

* Attached [Athasha.Phoenix-main.zip](https://github.com/elixir-lsp/vscode-elixir-ls/files/5940084/Athasha.Phoenix-main.zip) with phoenix project that builds correctly
* Launch VSCode and wait for elixir-ls to build
* Trigger auto formatter on lib/athasha/auth.ex or lib/athasha_web/router.ex
* Lots of empty lines are inserted just after the first defmodule line
* Most other files work fine
* Output panel attached [ElixirLS_Output.txt](https://github.com/elixir-lsp/vscode-elixir-ls/files/5940125/ElixirLS_Output.txt)

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 21 [erts-10.3] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] Elixir 1.11.3 (compiled with Erlang/OTP 21)
* VSCode ElixirLS version: 0.6.4
* Operating System Version: win32 10.0.18363
* VSCode About
```
Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
```

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

![Capture1](https://user-images.githubusercontent.com/4142710/107160890-a621b000-695e-11eb-8220-bcc1171e42b4.png)

**Comment by axelson** [comment]
Hmm, that is quite odd! Does this reproduce every time for you?

**Comment by samuelventura** [comment]
Yep, every single time.

**Comment by samuelventura** [comment]
Not happening on macos.

**Comment by mkhennoussi** [comment]
Same issue for me, working on Windows

**Comment by axelson** [comment]
This is fixed by https://github.com/elixir-lsp/elixir-ls/pull/489

**Comment by CallumVass** [comment]
FYI. You can use 0.6.5 of this extension now by changing your VS Code settings to be just LF in your settings.json file:

"files.eol": "\n",

Tested on Windows machine just now.

**Comment by Attrams** [comment]
I am currently using windows and this stopped when I change the End of line sequence from CRLF to LF.
