### ISSUE TITLE
There is no formatter for "html (Eex)" files installed

### ISSUE THREAD

**Issue by colinramsay** [elixir-lsp/vscode-elixir-ls#172]
When I format a .ex file, it works as expected. When I try a .html.ex file, I receive the message in the issue subject. I'm not sure how to go about debugging this, but happy to provide whatever information is needed.

### Environment

Using the VSCode Container environment with this setup but with only vscode-elixir-ls installed:

https://github.com/nicbet/docker-phoenix/

The following are therefore the versions inside the container.

* Elixir & Erlang versions (elixir --version): Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.11.2 (compiled with Erlang/OTP 23)
* VSCode ElixirLS version: 0.6.5
* Operating System Version: linux 5.8.0-43-generic

The host OS is Ubuntu 20.04.

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

**Comment by NobbZ** [comment]
There is currently no formatter provided by the LS that would be format any `*.eex` files.

Some users reported great success with using generic HTML formatters on `*.html.eex`.

**Comment by colinramsay** [comment]
Thanks for the response and that would explain the problem! I searched this repository and found that the extension seems to register for html.eex and also provides a syntax for it, so that's probably where I went wrong. Can I ask what things like the [syntax](https://github.com/elixir-lsp/vscode-elixir-ls/blob/418e189eebd6e7d72753f13661fee12e7583d8e6/syntaxes/html-eex.json) allow the extension to do? Just code folding?

I will try a generic formatter but haven't had much success in the past. Thanks again though!

**Comment by axelson** [comment]
You might be able to try out https://github.com/adamzapasnik/prettier-plugin-eex although it looks like you'll have to modify your project for it.

This is a relevant Elixir Forum thread: https://elixirforum.com/t/vs-code-formatter-for-html-leex-and-html-eex-files/35959/
