### ISSUE TITLE
How to tabSize = 4 please

### ISSUE THREAD

**Issue by mfoncho** [elixir-lsp/vscode-elixir-ls#174]
I normally work on vim with the tab width set to 4.
I recently just open vscode to do some refactoring and every file that was touched had their indentations changed to 2 spaces.
I thought knew how to setup tabSize in vscode and even how to set it per workspace and per language
this is part of my vs code settings.json file 
```json
{
  
    "editor.formatOnSave": true,
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.wordBasedSuggestions": false,
    "editor.formatOnType": true,
    "editor.trimAutoWhitespace": false,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "[elixir]": {
        "editor.tabSize": 4,
        "editor.formatOnSave": true,
        "editor.insertSpaces": true,
        "editor.formatOnType": true,
        "editor.wordBasedSuggestions": false,
        "editor.trimAutoWhitespace": false,
        "files.trimTrailingWhitespace": true,
        "files.insertFinalNewline": true,
        "files.trimFinalNewlines": true
    }
}
```
The final fix was to set ```editor.formatOnSave``` to ```false``` 
#### Question:  can i use MY preferred tab width with this plugin, or is there something more i need to  do?

**Comment by NobbZ** [comment]
Disable format on save. And do not run `mix format` ever.

It is what reindents with 2 spaces.

**Comment by mindok** [comment]
The settings for code formatting are in `.formatter.exs` in the root folder of your project. This is what the format on save uses, and also `mix format`. I had a look through the options for code formatting (search for `Code.format_string` and `mix format` in the online docs) and I don't think there is an option to change the indent level - the community agreed on 2 spaces (not 4 spaces and not tabs) so if you want to share code with other Elixir devs you're best off just accepting the defaults.

**Comment by axelson** [comment]
Closing this since the elixir formatter doesn't allow configuring the indentation level.

**Comment by mfoncho** [comment]
Yes @mindok  the "community agreed" on 2 spaces so @axelson  isn't it logical to not have ```  "editor.tabSize": 2 ``` as a configuration setting for the vscode plugin as its seams sort of misleading right? Yes open source software and all but then again ...

**Comment by NobbZ** [comment]
This option is provided by VScode and not "removable".

**Comment by mfoncho** [comment]
Yes but for language servers that can take advantage of it. I think its just an option not a requirement if the language or language server doesn't support it. VScode supports the option but the language server itself doesn't so having it in the docs is what i meant by misleading, because from reading the docs it will be save to assume the ```editor.tabSize``` is configurable but it isn't. There are many other options supported by VScode which aren't valid option param for the elixir-lsp server hence are not included in the config readme right
> This option is provided by VScode and not "removable".

**Comment by NobbZ** [comment]
As I said already, the option is editable and VScode adheres to it. And if you do not format your code, then there will be nothing that destroys your beloved 4 spaces indent…

Also, setting it to 2 by default, makes it match the formatter and therefore the decreases clutter during format on save.

**Comment by mfoncho** [comment]
> As I said already, the option is editable and VScode adheres to it. And if you do not format your code, then there will be nothing that destroys your beloved 4 spaces indent…

Its just code, text file indentation, not a "beloved  4 space index"  as i'm comfortable reading and writing elixir source files any indent available. 

I'm sorry this turning out to be a point of contention. I get wanting everyone to use `editor.tabSize=2` and its fine really.

Many thanks to members of this project.
