### ISSUE TITLE
Enable collapsing whole @moduledoc blocks

### ISSUE THREAD

**Issue by Hajto** [elixir-lsp/vscode-elixir-ls#181]
I would like to collapse whole module docs blocks. I noticed that I couldn't do so when I was contributing to this project:
https://github.com/dashbitco/broadway

These cannot be collapsed
```
@moduledoc ~S"""
```

These can be though:
```
@moduledoc """
```

### Environment

Most of this can be filled out by running the VSCode command (by default bound to Ctrl+Shift+P) "ElixirLS: Copy Debug Info"

* Elixir & Erlang versions (elixir --version): Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] Elixir 1.11.3 (compiled with Erlang/OTP 21)
* VSCode ElixirLS version: 0.6.5
* Operating System Version: darwin 19.6.0

**Comment by axelson** [comment]
FYI soon this will be handled by https://github.com/elixir-lsp/elixir-ls/pull/492
If you want to give that branch a try it would be greatly appreciated (the contribution instructions are helpful for running a custom branch locally https://github.com/elixir-lsp/vscode-elixir-ls/#contributing)

**Comment by axelson** [comment]
This is fixed in https://github.com/elixir-lsp/elixir-ls/pull/492 and will be released soon
