### ISSUE TITLE
[Crash] function nil.dirty?/0 is undefined

### ISSUE THREAD

**Issue by pedro-lb** [elixir-lsp/vscode-elixir-ls#186]
For me, elixir-ls keeps crashing all the time with the same exception message: `function nil.dirty?/0 is undefined`.

### Is this the right repo?

I think so

### Environment

```
* Elixir & Erlang versions (elixir --version): Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.12.0-rc.0 (77fa0c4) (compiled with Erlang/OTP 22)

* VSCode ElixirLS version: 0.7.0
* Operating System Version: linux 5.4.72-microsoft-standard-WSL2
```

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

### Crash report template

```
22:00:21.984 [error] GenServer ElixirLS.LanguageServer.Server terminating
** (UndefinedFunctionError) function nil.dirty?/0 is undefined
    nil.dirty?()
    (elixir 1.12.0-rc.0) lib/enum.ex:2189: anonymous fn/3 in Enum.split_with/2
    (elixir 1.12.0-rc.0) lib/enum.ex:2358: Enum."-split_with/2-lists^foldl/2-0-"/3
    (elixir 1.12.0-rc.0) lib/enum.ex:2358: Enum.split_with/2
    (language_server 0.7.0) lib/language_server/server.ex:909: ElixirLS.LanguageServer.Server.handle_dialyzer_result/3
    (language_server 0.7.0) lib/language_server/server.ex:146: ElixirLS.LanguageServer.Server.handle_cast/2
    (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.1) gen_server.erl:765: :gen_server.handle_msg/6
Last message: {:"$gen_cast", {:dialyzer_finished, [], #Reference<0.3444722972.2955411459.156730>}}
```

**Comment by lukaszsamson** [comment]
@pedro-lb this is not the right repo. This issue should go to https://github.com/elixir-lsp/elixir-ls as this is language server crash. Anyway, do you have a simple project that reproduces it on an official elixir release? We do not support RC or dev versions.

**Comment by pedro-lb** [comment]
Hey there @lukaszsamson!

Sorry for opening the issue in the wrong repo, but I'll keep this open as there is also a PR open - feel free to close it tho.

Unfortunately, I don't have any example project as the error happens very spontaneously, and I can't seem to reproduce it with a specific file or content. However, looking at your PR it does seem to make a lot of sense since the error often happens after I closed a file.

 I'm eager to help you with this investigation - I'm currently testing your PR locally while coding and monitoring if this error happens.
