### ISSUE TITLE
Dialyzer doesn't report problems after Elixir 1.12 upgrade

### ISSUE THREAD

**Issue by javobalazs** [elixir-lsp/vscode-elixir-ls#191]
### Symptoms

Sometimes after upgrading first to Erlang 24 and then later to Elixir 1.12 (can't remember, the two was very close to each other in time but I think it was the Elixir upgrade) I noticed dialyzer warnings were gone.

### Is this the right repo?

I notice this using VSCode, this is the "entry point" of the problem.

### Environment

Most of this can be filled out by running the VSCode command (by default bound to Ctrl+Shift+P) "ElixirLS: Copy Debug Info"

- VSCode: 1.56.2
- Electron: 12.0.4
- Chrome: 89.0.4389.114
- Node.js: 14.16.0
- V8: 8.9.255.24-electron.0
- Elixir & Erlang versions (elixir --version): 1.12.0
- Erlang: 1:24.0.1-1
- VSCode ElixirLS version: 0.7.0
- Operating System Version: Ubuntu 20.04.2 LTS (5.4.0-73-generic #82-Ubuntu SMP x86_64 GNU/Linux)

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

Nothing worked.

**Comment by axelson** [comment]
Hi, do you get any errors in your logs? https://github.com/elixir-lsp/vscode-elixir-ls/#check-elixirls-output

**Comment by javobalazs** [comment]
Curiously, there are no errors. I've copied the log (that was produced after deleting the .elixir_ls directory), skipping the part where the dependencies compilation is done, and I erased the module name listings too. Note, that the dialyzer manifest file `dialyzer_manifest_24.0.1_elixir-1.12.0_test` was generated along with the `build` and `dialyzer_tmp` directories.

```log
Started ElixirLS v0.7.0
Elixir version: "1.12.0 (compiled with Erlang/OTP 24)"
Erlang version: "24"
ElixirLS compiled with Elixir 1.8.2 and erlang 21
MIX_ENV: test
MIX_TARGET: 
... dependencies and the actual app ...
[Info  - 4:55:12 PM] Compile took 68504 milliseconds
[Info  - 4:55:12 PM] [ElixirLS WorkspaceSymbols] Indexing...
MIX_ENV: test
MIX_TARGET: 
[Info  - 4:55:13 PM] [ElixirLS WorkspaceSymbols] Module discovery complete
[Info  - 4:55:13 PM] [ElixirLS WorkspaceSymbols] 78 callbacks added to index
[Info  - 4:55:14 PM] Compile took 1147 milliseconds
[Info  - 4:55:14 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 4:55:17 PM] [ElixirLS WorkspaceSymbols] 543 modules added to index
[Info  - 4:55:20 PM] [ElixirLS WorkspaceSymbols] 596 types added to index
[Info  - 4:55:28 PM] [ElixirLS Dialyzer] Found 473 changed files in 14229 milliseconds
[Info  - 4:55:46 PM] [ElixirLS WorkspaceSymbols] 8607 functions added to index
[Info  - 4:56:05 PM] [ElixirLS Dialyzer] Analyzing 509 modules: [...]
[Info  - 5:00:38 PM] [ElixirLS Dialyzer] Analysis finished in 310377 milliseconds
[Info  - 5:00:39 PM] Dialyzer analysis is up to date
[Info  - 5:00:40 PM] [ElixirLS Dialyzer] Writing manifest...
[Info  - 5:00:42 PM] [ElixirLS Dialyzer] Done writing manifest in 3228 milliseconds.
[Warn  - 8:11:32 PM] Received $/cancelRequest for unknown request id: 13
MIX_ENV: test
MIX_TARGET: 
Compiling 5 files (.ex)
[Info  - 8:11:51 PM] Compile took 4740 milliseconds
[Info  - 8:11:51 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 8:11:51 PM] [ElixirLS WorkspaceSymbols] Updating index...
[Info  - 8:11:52 PM] [ElixirLS WorkspaceSymbols] 1 modules need reindexing
[Info  - 8:11:52 PM] [ElixirLS WorkspaceSymbols] 0 callbacks added to index
[Info  - 8:11:52 PM] [ElixirLS WorkspaceSymbols] 1 modules added to index
[Info  - 8:11:52 PM] [ElixirLS WorkspaceSymbols] 4 functions added to index
[Info  - 8:11:52 PM] [ElixirLS WorkspaceSymbols] 0 types added to index
[Info  - 8:11:52 PM] [ElixirLS Dialyzer] Found 5 changed files in 356 milliseconds
[Info  - 8:11:53 PM] [ElixirLS Dialyzer] Analyzing 5 modules: [...]
[Info  - 8:11:56 PM] [ElixirLS Dialyzer] Analysis finished in 4050 milliseconds
[Info  - 8:11:57 PM] Dialyzer analysis is up to date
[Info  - 8:11:58 PM] [ElixirLS Dialyzer] Writing manifest...
[Info  - 8:11:59 PM] [ElixirLS Dialyzer] Done writing manifest in 2675 milliseconds.
[Warn  - 8:12:19 PM] Received $/cancelRequest for unknown request id: 26
[Warn  - 8:14:56 PM] Received $/cancelRequest for unknown request id: 33
```

**Comment by javobalazs** [comment]
Okay, there was another observation but I couldn't reproduce it. There were a few ordinary compiler warnings in a project (defined but unused variables). I did a commit, push, deploy, whatever. When I got back to VSCode, _all the warnings were gone_. I think I modified one of the files and then I got back the warnings.

**Comment by javobalazs** [comment]
I can reproduce the disappearing warning phenomenon in my VSCode. I have a file with an unused variable. I edit the file, save it, the warning appears:

```
somefile1.ex
  variable "x" is unused (if the variable is not meant to be used, prefix it with an underscore)
```

Then I open another file (somefile2.ex) that has no problem. I make a useless edit (like inserting an empty row), Ctrl-S, and the warning disappears. And it's reproducible:

- I click on the tab of `somefile1.ex`, insert an empty row, Ctrl-S, the warning reappears.
- I click on the tab of `somefile2.ex`, insert an empty row, Ctrl-S, the warning disappears.
- and so on.

I don't know whether it has anything to do with the missing dialyzer warnings (or vscode-elixir-ls at all) but the message display has some problems anyway.

**Comment by javobalazs** [comment]
Update: Dialyzer warning options are empty by default, so even if Dialyzer is run, vscode-elixir-ls won't report anything. But when I set `Dialyzer Warn Opts` to the list copied from the option definitions (below, JSON), the reporting comes back.

```json
"elixirLS.dialyzerWarnOpts": [
      "error_handling",
      "no_behaviours",
      "no_contracts",
      "no_fail_call",
      "no_fun_app",
      "no_improper_lists",
      "no_match",
      "no_missing_calls",
      "no_opaque",
      "no_return",
      "no_undefined_callbacks",
      "no_unused",
      "underspecs",
      "unknown",
      "unmatched_returns",
      "overspecs",
      "specdiffs"
    ]
```

**Comment by Defman21** [comment]
@javobalazs I'd also go for removing the `no_` options since they silence many useful reports from Dialyzer.

**Comment by javobalazs** [comment]
Thx, now I really have my old, familiar warnings :)
