### ISSUE TITLE
Elixir embeddings not tokenized properly in HTLM sigil block

### ISSUE THREAD

**Issue by jonatanklosko** [elixir-lsp/vscode-elixir-ls#194]
Elixir embeddings (like `<%= %>`) are not tokenized properly in `~L""" """` as opposed to `.(l)eex` files

![image](https://user-images.githubusercontent.com/17034772/123525222-5c4c2300-d6cf-11eb-9d7a-662c29578746.png)

<details>
<summary>Code</summary>

```
# Elixir

~L"""
<div class="one <%= if(true, do: "ok", else: "") %>">
</div>
"""
```

```
<%# HTML Elixir %>

<div class="one <%= if(true, do: "ok", else: "") %>">
</div>
```
</details>

### Details

The `~L` sigil includes all the rules that `.(l)eex` files use:

https://github.com/elixir-lsp/vscode-elixir-ls/blob/00023f4cbeda1b0aefd4043b3e1ce733bc9e20d6/syntaxes/elixir.json#L1585-L1589

However, the Elixir HTML tokenizer has this special configuration:

https://github.com/elixir-lsp/vscode-elixir-ls/blob/00023f4cbeda1b0aefd4043b3e1ce733bc9e20d6/syntaxes/html-eex.json#L5-L14

My guess is that `"include"` refers only to rules, so this additional configuration doesn't apply in the Elixir tokenizer. Mirroring `"injections"` into `elixir.json` seems to help, though I may be missing some other alternative.

### Environment

- VSCode ElixirLS version: 0.7.0

**Comment by lukaszsamson** [comment]
Thanks @jonatanklosko, this seems to work well and even paly nicely with do/end bracket matching.
<img width="576" alt="Screenshot 2023-06-04 at 12 20 08" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/2ddf6ff7-55ee-4244-ac77-0ffaf62c66ed">
