### ISSUE TITLE
Support compiling, linting and warnings on files outside "lib" folder

### ISSUE THREAD

**Issue by dekdekbaloo** [elixir-lsp/vscode-elixir-ls#198]
### Environment
- Elixir & Erlang versions (elixir --version): Erlang/OTP 23 [erts-11.1.8] Elixir 1.11.3
- VSCode ElixirLS version: 0.7.0
- Operating System Version: macOS Big Sur 11.2.2

As I understand, `vscode-elixir-ls` doesn't output warnings for files outside "lib" folder.

Following this [issue](https://github.com/JakeBecker/elixir-ls/issues/77) from the old repo, we have to run `mix compile` on our own. Ideally, we expect to see results for any file inside `elixir.projectDir` e.g. `test/*`, `priv/*`. Are there any suggestions?

**Comment by lukaszsamson** [comment]
Elixir-ls uses mix underneath and only returns diagnostics that mix returns. See https://github.com/elixir-lsp/elixir-ls/issues/89 for details. Closing this as the issue needs to be handle upstream by elixir-lang developers.
