### ISSUE TITLE
Update the LS if updates are available

### ISSUE THREAD

**Issue by NobbZ** [elixir-lsp/vscode-elixir-ls#2]
Currently the LS is built only once from master.

We need to check for updates and update/rebuild the LS when updates are available.

**Comment by lukaszsamson** [comment]
Why add another update mechanism over vscode extension one?

**Comment by NobbZ** [comment]
Because when I still used VScode it annoyed me as hell, as it updated without telling me, and that I can not (easily) influence which versions of what to use.

Though I have to admit, it seems to be state of the art in the VScode community to opt out of controlling these things. This was one of the reasons why I do not use it anymore.
