### ISSUE TITLE
~H sigil support

### ISSUE THREAD

**Issue by exit9** [elixir-lsp/vscode-elixir-ls#201]
Environment: Elixir 1.12 & Erlang 24, Linux, VSCode, elixir-ls-vscode

Hello.
There's new ~H sigil in Phoenix 1.6 acts like shorthand to html.leex. Is any plans for support it? I think it would be the same as ~L sigil. And I unfortunately can't find ~L support in repo and history to make pull request myself.
https://github.com/phoenixframework/phoenix_live_view/blob/45d871f5d633c61b9304f005b9d7d86df9c252a3/lib/phoenix_live_view/helpers.ex#L703

**Comment by axelson** [comment]
There's relevant discussion in https://github.com/elixir-lsp/vscode-elixir-ls/pull/193 the current plan is to add support for `~H` in a separate extension which can be maintained upstream. I'll leave this open until that is resolved.

**Comment by lukaszsamson** [comment]
@exit9 You can find `~L` support here https://github.com/elixir-lsp/vscode-elixir-ls/blob/16f3a856af893b6fa1dae8687b50f379e3f1b16f/syntaxes/elixir.json#L1566 (and 3 other places, just search the file for '~L')
As for templates, see https://github.com/elixir-lsp/vscode-elixir-ls/blob/master/syntaxes/html-eex.json and https://github.com/elixir-lsp/vscode-elixir-ls/blob/master/syntaxes/eex.json

**Comment by lukaszsamson** [comment]
Addressed in https://github.com/elixir-lsp/vscode-elixir-ls/pull/277
