### ISSUE TITLE
Autocomplete being invoke for "do"

### ISSUE THREAD

**Issue by ltd** [elixir-lsp/vscode-elixir-ls#206]
This  behavior seemed to change recently, when I type  "do" followed by return (which I do often), I end up inserting a defoverride from the autocomplete menu.   I'm not sure if autocomplete previously popped up for "do" previously.

![Cursor_and_nlog_ex_—_ldb](https://user-images.githubusercontent.com/67152/130396476-36047b64-3802-4645-8f86-e1b67771d212.png)

### Environment
* Elixir & Erlang versions (elixir --version): Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit] [dtrace]

Elixir 1.12.2 (compiled with Erlang/OTP 24)

* VSCode ElixirLS version: 0.8.0
* Operating System Version: darwin 20.6.0

**Comment by Qizot** [comment]
Can confirm, it's really annoying, it happened in the past for some time but haven't seen it for a while until recently.

**Comment by MzudemO** [comment]
There's been a PR for this issue in elixir-ls https://github.com/elixir-lsp/elixir-ls/pull/593

**Comment by ltd** [comment]
thanks, i see it was merged in, so we just need to wait for a release.

**Comment by jraregris** [comment]
It is released now!
https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.8.1

**Comment by jessbowers** [comment]
this behavior is back for me in 0.13.0. I think there was a setting to ignore autocomplete for < n chars? I can't find it now
