### ISSUE TITLE
Failed to run 'elixir' command. ElixirLS will probably fail to launch.

### ISSUE THREAD

**Issue by krainboltgreene** [elixir-lsp/vscode-elixir-ls#208]
### Environment

* Elixir & Erlang versions (elixir --version): `Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit] Elixir 1.12.1 (compiled with Erlang/OTP 24)`
* Operating system: `Linux 033d18dbe177 5.4.0-1055-azure elixir-lsp/elixir-ls#57~18.04.1-Ubuntu SMP Fri Jul 16 19:40:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Editor or IDE name (e.g. Emacs/VSCode): `VSCode (Codespaces)`

Output logs:

```
[Trace - 9:57:33 AM] Sending request 'initialize - (0)'.
erl_child_setup closed

Crash dump is being written to: erl_crash.dump...done
[Info  - 9:57:35 AM] Connection to server got closed. Server will restart.
```

Developer Tool logs:

```
Failed to run 'elixir' command. ElixirLS will probably fail to launch. Logged PATH to Development Console.
[Extension Host] Failed to run 'elixir' command. Current process's PATH: /home/codespace/.vscode-remote/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
The ElixirLS - blank-application server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

I manually ran `/home/codespace/.vscode-remote/extensions/jakebeck…xir-ls-0.8.1/elixir-ls-release/language_server.sh` in my terminal and it booted up just fine.

**Comment by axelson** [comment]
> I dont't have access in that repo. @axelson?

Transferred! And I just gave you permissions to handle it next time.

@krainboltgreene I've never used codespaces before, but is asdf loaded in your codespace?

**Comment by krainboltgreene** [comment]
@axelson Yep! You can see it at krainboltgreene/blank-application.

**Comment by krainboltgreene** [comment]
Okay so this is the path it outputs:

```
Failed to run 'elixir' command. Current process's PATH: /home/codespace/.vscode-remote/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/codespace/.local/bin
```

I've also confirmed this with the default elixir codespace container.

**Comment by krainboltgreene** [comment]
When I run the startup script myself, in my own terminal, it boots just fine:

![Uploading Screen Shot 2021-10-03 at 6.35.23 AM.png…]()
