### ISSUE TITLE
Intellisense problem with nested structs and Phoenix 1.6 templates

### ISSUE THREAD

**Issue by dlsq** [elixir-lsp/vscode-elixir-ls#209]
### Problem
* No intellisense for nested structs (eg. Datetime or user defined)
* No intellisense in Phoenix 1.6 templates (eex or heex) (emmet is working).

### Environment
* Elixir & Erlang versions (elixir --version): Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.12.3 (compiled with Erlang/OTP 24)

* VSCode ElixirLS version: 0.8.1
* Operating System Version: linux 5.11.0-37-generic

* VSCode version: 1.61.0

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
- [x] Compiled ElixirLS with installed Erlang and Elixir versions: https://dragoshmocrii.com/fix-vscode-elixirls-intellisense-for-code-imported-with-use/

**Comment by lukaszsamson** [comment]
@dlsq please open separate issues and provide more details on how to reproduce
