### ISSUE TITLE
Add support for the Test tab

### ISSUE THREAD

**Issue by VitorTrin** [elixir-lsp/vscode-elixir-ls#211]
Vscode has the Test sidebar, which provides an usefull view to run tests and discover what failed, why, and quickly jump to the failing test. For those who has never seen it, it looks something like this

![image](https://user-images.githubusercontent.com/9387059/138481125-9d62bf1d-740c-4fa0-b1bc-a0c22b9b368b.png)

The image shows python, but the only language with support for this that I've tried is Go.

**Comment by lukaszsamson** [comment]
Addressed in https://github.com/elixir-lsp/vscode-elixir-ls/pull/276. Will need further work to make it good but the basics are there
