### ISSUE TITLE
Examples in @doc tags are no longer being rendered

### ISSUE THREAD

**Issue by markomitranic** [elixir-lsp/vscode-elixir-ls#233]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:no-native-stack] Elixir 1.13.2 (compiled with Erlang/OTP 24)
* VSCode ElixirLS version: 0.9.0
* Operating System Version: linux 5.13.0-22-generic

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

## Description
Since a few weeks ago (possibly after Elixir and Phoenix updates to latest versions), the context tooltip no longer renders ANY `iex>` lines from within moduledocs. Yes, not even the stdlib!

If I were to un-tab the `iex>` lines, they begin to be treated as normal text, and are shown.

I have tested this on multiple projects, including a new mix project. All running inside the latest elixir Docker.

For reference, here is a textual copypaste of the docblock, in case I've made a typo:
```elixir
  @doc """
  Marko `test`

  ## Example:

      iex> AggregateDataParser.parse_csv_file(nil)
      :ok

  ## Test2:
  Marko *test*.

  """
  def parse_csv_file(filename), do: filename |> File.stream!() |> parse_csv_stream
```

<img width="1323" alt="Screenshot 2022-02-14 at 13 02 32" src="https://user-images.githubusercontent.com/10811624/153860899-85088b44-e5e0-4ee4-a28b-b0322764cafe.png">
<img width="1323" alt="Screenshot 2022-02-14 at 13 02 43" src="https://user-images.githubusercontent.com/10811624/153860907-66cf18e9-0157-4e1c-8df1-951cf979d598.png">

**Comment by lukaszsamson** [comment]
I can confirm this issue. It looks like it is vscode that strips the examples as they are clearly sent in protocol messages. There were some changes related to markdown rendering recently. I guess that `iex>` is treated as some broken HTML tag and filtered out.

**Comment by markomitranic** [comment]
@lukaszsamson I don't fully understand. Does that mean that there will be no fix?

**Comment by lukaszsamson** [comment]
@markomitranic if you have an idea how we can work this issue around than go ahead. Otherwise I suggest reporting it to vscode repo.

**Comment by markomitranic** [comment]
@lukaszsamson I am unsuare how to do that. They explicitly say that **"Issues caused by an extension need to be reported directly to the extension publisher. The 'Help > Report Issue' dialog can assist with this."** I understand that this is a different case, because the extension fails due to VSCode's change, but I don't know how to file the Issue?

Also, this thing impacts the whole stdlib, because `iex>` is a required phrase when writing docblocks, and getting them inspected. I am unsure how is it that I am the only one filing this issue, its literally one of the main uses of this extension :O

**Comment by lukaszsamson** [comment]
We have 3 options @markomitranic :
- report an issue to VSCode (this one looks related https://github.com/microsoft/vscode/issues/143081)
- convince elixir community to format docs in a way that does not break VSCode rendering
- hack and transform markdown returned by elixir EIP48 API so it renders in VSCode

**Comment by markomitranic** [comment]
@lukaszsamson Ok, thanks for the snarky comment.
1. If you had actually read the issue you posted, you'd see that they closed it down without comment, and told the guy to contact the Extension developers - in this case you.
2. Thats not funny.
3. Yes, a very good idea, don't you think you should perhaps add it to the roadmap in some way and then someone (perhaps even me) can actually make a PR?

**Comment by lukaszsamson** [comment]
@markomitranic Sorry if I sounded rude.

> Yes, a very good idea, don't you think you should perhaps add it to the roadmap in some way and then someone (perhaps even me) can actually make a PR?

There is no roadmap actually and the project is not very organised ATM. If you would like to contribute then please go ahead.  I'd try with transforming the markdown here https://github.com/elixir-lsp/elixir-ls/blob/ba6252f4edb6909a6ce877834178ac7d0ff3f21d/apps/language_server/lib/language_server/providers/hover.ex#L32
But we need to make sure it doesn't break rendering in other clients

**Comment by lovebes** [comment]
any progress with this? I'm noticing it too - and thanks many times for this wonderful extension :)

**Comment by markomitranic** [comment]
@lovebes I haven't made any progress yet. Unfortunately due to unforseen circumstances I'm not in a position where I will be able to dedicate time for this - probably until end of March.

**Comment by henrythebuilder** [comment]
Hi,
It seems to be a problem only for _'four spaces indented' code blocks_.
I tried to write a comment to a 'js' function and I had the same problem:
```typescript
/**
 *> hello()
 *
 *Hello world.
 *
 *## Example ('four spaces indented' code block)
 *
 *    iex> Ex.hello()
 *         :world
 *
 *## Example ('fenced' code block)
 *
 *```
 *    iex> Ex.hello()
 *         :world
 *```
**/
function hello() {
  console.log("Hello World!");
}
```
![vscode-hover-help](https://user-images.githubusercontent.com/6670654/156028363-d2aebf47-59a5-41ec-84a6-e8df27178057.png)


Visual Studio Code seems to render only the 'fenced' code block. 
Could you confirm this too?

**Comment by lukaszsamson** [comment]
@henrythebuilder yes, it was already reported on vscode https://github.com/microsoft/vscode/issues/142501

**Comment by henrythebuilder** [comment]
Thanks @lukaszsamson I missed that issue :+1: 
I hope that they solve the problem '_Indented code blocks_' is a markdown spec!

**Comment by lukaszsamson** [comment]
> 'Indented code blocks' is a markdown spec!

There is no markdown spec, the author deliberately didn't wan't a spec. There are specs for markdown variants though and LSP references Github flavoured one https://microsoft.github.io/language-server-protocol/specifications/specification-current/#markupContent which should support intended code blocks https://github.github.com/gfm/#indented-code-blocks

**Comment by henrythebuilder** [comment]
This is true, thanks for clarification.
The reference must be the ['LSP#Markupcontent'](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#markupContent) specifications :+1:

**Comment by henrythebuilder** [comment]
VSCode version 1.65 seems to work :+1: 

My version is _Code-OSS self-compiled from source_:
```
Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-04T07:56:41.150Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.0-0.bpo.3-amd64
```

Thanks to [VSCode](https://github.com/microsoft/vscode) contributors!

**Comment by lovebes** [comment]
awesome same for me too!! 
Although .. didn't it used to have a different background color? To note it's a code block? 
Maybe I'm imagining things.
