### ISSUE TITLE
Module is not loaded and could not be found.

### ISSUE THREAD

**Issue by maiquitome** [elixir-lsp/vscode-elixir-ls#234]
![image](https://user-images.githubusercontent.com/16550103/156039012-611d04da-b2a7-497c-9800-5487f640e53c.png)

![image](https://user-images.githubusercontent.com/16550103/156039319-b1ed478b-bd05-43b8-a4c0-de7e5c2a2592.png)

the error is here => https://github.com/maiquitome/team_budget_api

**Comment by lukaszsamson** [comment]
Cannot reproduce. Please don't use issue tracker for support questions

**Comment by maiquitome** [comment]
ok... but if the project compiles, isn't the problem in the extension?

**Comment by lukaszsamson** [comment]
@maiquitome please post a project that reliably reproduces the error. I cloned your repo and couldn't reproduce it. Otherwise try to cleanup deps, buildd .elixir-ls and restart vscode

**Comment by maiquitome** [comment]
I deleted the .elixir_ls folder, restarted vscode and it worked. Thanks a lot!
