### ISSUE TITLE
Formatter does'nt work

### ISSUE THREAD

**Issue by adaosantos** [elixir-lsp/vscode-elixir-ls#235]
### Environment

Most of this can be filled out by running the VSCode command (by default bound to Ctrl+Shift+P) "ElixirLS: Copy Debug Info"

- Elixir & Erlang versions (elixir --version): Elixir 1.13.3 Erlang 24.2.2
- VSCode ElixirLS version: v0.9.0
- Operating System Version: Windows 11 (WSL2 Archlinux)

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

When I trigger `alt+shift+f` I receive this message on output:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/4481171/157723083-81f13ab6-4dd7-41a6-90eb-e5f49767f8a2.png">

My .formatter.exs
<img width="355" alt="image" src="https://user-images.githubusercontent.com/4481171/157723489-8e28ee4f-ffd4-4e29-88bd-9714b41a1c91.png">

**Comment by lukaszsamson** [comment]
Please post a repo that reproduces this issue

**Comment by adaosantos** [comment]
> Please post a repo that reproduces this issue

I used a blank repository, you can use `mix new <name>` to reproduce this

**Comment by lukaszsamson** [comment]
> I used a blank repository, you can use mix new <name> to reproduce this

@adaosantos I cannot reproduce it. From your screenshots I can see you are using ecto and phoenix so it's not blank one BTW.
