### ISSUE TITLE
Test Lens did not show run test command

### ISSUE THREAD

**Issue by Fubuchi** [elixir-lsp/vscode-elixir-ls#238]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.3 (compiled with Erlang/OTP 22)
```
* Elixir Language Server version: 0.8.2
* Operating system: Win 10 Pro Version 10.0.19042.1466
* Editor or IDE name (e.g. Emacs/VSCode): 
```
VSCode 
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```
* Editor Plugin/LSP Client name and version: 0.9.0

### Current behavior

`elixirLS.enableTestLenses` was set to true but run test command did not show for test 

![image](https://user-images.githubusercontent.com/42483897/160062037-8beb1bd1-4fef-49cd-89b8-4330d968b879.png)

ElixirLS log

```
Started ElixirLS v0.8.2
Elixir version: "1.13.3 (compiled with Erlang/OTP 22)"
Erlang version: "24"
ElixirLS compiled with Elixir 1.10.4 and erlang 22
MIX_ENV: test
MIX_TARGET: 
[Info  - 12:46:39 PM] Compile took 577 milliseconds
[Info  - 12:46:39 PM] [ElixirLS WorkspaceSymbols] Indexing...
[Info  - 12:46:39 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 12:46:39 PM] [ElixirLS Dialyzer] Found 0 changed files in 3 milliseconds
[Info  - 12:46:39 PM] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 12:46:39 PM] [ElixirLS Dialyzer] Analysis finished in 73 milliseconds
[Info  - 12:46:39 PM] Dialyzer analysis is up to date
[Info  - 12:46:39 PM] [ElixirLS WorkspaceSymbols] Module discovery complete
[Info  - 12:46:39 PM] [ElixirLS WorkspaceSymbols] 22 callbacks added to index
[Info  - 12:46:39 PM] [ElixirLS WorkspaceSymbols] 160 modules added to index
[Info  - 12:46:40 PM] [ElixirLS Dialyzer] Writing manifest...
[Info  - 12:46:41 PM] [ElixirLS Dialyzer] Done writing manifest in 1987 milliseconds.
[Info  - 12:46:41 PM] [ElixirLS WorkspaceSymbols] 325 types added to index
[Info  - 12:46:44 PM] [ElixirLS WorkspaceSymbols] 3878 functions added to index

```

### Expected behavior

Run test command should be shown and clickable

**Comment by lukaszsamson** [comment]
<img width="678" alt="Screenshot 2022-03-28 at 09 03 32" src="https://user-images.githubusercontent.com/1078186/160343820-e4cbd9d9-ba57-4cad-be14-9cf8bed4a0c0.png">
Works for me. @Fubuchi  Please post a repo that reproduces this bug.

**Comment by Fubuchi** [comment]
It is a basic project created by running `mix new hello_world`

[hello_world.zip](https://github.com/elixir-lsp/vscode-elixir-ls/files/8361818/hello_world.zip)

**Comment by Fubuchi** [comment]
@lukaszsamson 

The reason is  the function `is_test_file` could not handle the path. I added a bunch of log code, and here was what I got

![image](https://user-images.githubusercontent.com/42483897/160533853-5f249b20-dc72-4492-9ec3-01008735788d.png)

The modified code:

![image](https://user-images.githubusercontent.com/42483897/160534063-6359ba3b-b068-4dde-bdf2-2241c2bb1055.png)

**Comment by Fubuchi** [comment]
Since this is a elixir-ls issue. I close this one and open another one there.

https://github.com/elixir-lsp/elixir-ls/issues/685
