### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by jsmestad** [elixir-lsp/vscode-elixir-ls#250]
Not having any way to restart the language server from inside VSCode is a real headache. Any chance you could push out an updated release?

**Comment by robsonpeixoto** [comment]
The tag https://github.com/elixir-lsp/vscode-elixir-ls/releases/tag/v0.10.0 was created, but the extension wasn't published yet.

**Comment by lukaszsamson** [comment]
Yes, we're facing some publishing issues with vscode marketplace. Please be patient

**Comment by lukaszsamson** [comment]
Closing as 0.10.0 has been released
