### ISSUE TITLE
Add `Recompile project` command

### ISSUE THREAD

**Issue by konstantinzolotarev** [elixir-lsp/vscode-elixir-ls#251]
Please add `Recompile project` command to ElixirLS vs code extension. 
It's so annoying to close editor, remove `.elixir_ls` folder and start editor again every time you refactoring something.

**Comment by lukaszsamson** [comment]
I started work on a custom command to run `mix clean` within `.elixir_ls` directory.

**Comment by lukaszsamson** [comment]
An we'll need a similar command to clean and restart dialyzer

**Comment by aptinio** [comment]
Thanks @lukaszsamson for all your hard work that you make available to anyone for free. :heart:
