### ISSUE TITLE
`JakeBecker.elixir-ls` vs `elixir-lsp.elixir-ls`

### ISSUE THREAD

**Issue by filiptronicek** [elixir-lsp/vscode-elixir-ls#252]
Hi there to the Elixir LSP team 👋!

Recently, it came to my attention that VS Code by default, if the user tries to install the `elixir-lsp.elixir-ls` extension, it does not allow it and makes them download `JakeBecker.elixir-ls` instead. This seems a bit odd to me as it seems that the current extension (taking into consideration the information from the README and in https://github.com/elixir-lsp/vscode-elixir-ls/blob/master/package.json) is indeed intended to be under the `elixir-lsp` namespace. 

This can be problematic to folks using OpenVSX, because on there there is no `JakeBecker.elixir-ls` to recommend instead, as well as general confusion around this whole situation.

I am not sure of what to do to fix this, but I have a couple of ideas:
1. Start publishing the extension under `elixir-lsp.elixir-ls` on the Microsoft Marketplace and talk to the VS Code people at Microsoft to remove the extension from their "deprecated" list.
2. Publish the extension under `JakeBecker.elixir-ls` on OpenVSX.

<img width="919" alt="image" src="https://user-images.githubusercontent.com/29888641/172450492-206daadf-10c0-4e3e-9313-53729f2956e5.png">

**Comment by lukaszsamson** [comment]
It's not possible to change publisher on marketplace. The deprecated extension was a try on that but vscode would not pick updates from it as it treats it as a different one. This meant people was stuck on old not maintained one. Finally @JakeBecker transfered his publisher account to elixir-lsp org and we decided to deprecate our fork and publish on the original Jake's publisher.

**Comment by filiptronicek** [comment]
@lukaszsamson thanks for the response. I see how it is with the namespace. Would it be possible for the project to move to `JakeBecker.elixir-ls` on Open VSX as well? I would really appreciate it if it was possible for someone to try the migration. 

I would really love to help with anything needed here, since we really care about parity with the Microsoft Marketplace, because it can lead to confused users and broken experiences. Feel free to ping or reach out to me if you have any Open VSX related questions.

As an example of why this is important for us: if you use Settings Sync for syncing your extensions between computers and would have one computer using OpenVSX and the other using the MS Marketplace, it would always download the wrong extension on one machine if there is a discrepancy in the extension IDs.

**Comment by benvp** [comment]
This issue came up for me today aswell. Lately I started using Gitpod (gitpod.io) for my elixir projects and I am syncing the ElixirLS extension from my VSCode settings. The issue here is, that anytime when I open up VSCode with a local project it would download the `elixir-lsp.elixir-ls` instead of `jakebecker.elixir-ls` resulting in using the deprecated fork. I would highly appreciate if the extension could be published under the same namespace on Open VSX.
