### ISSUE TITLE
VS Code marketplace still shows 0.9.0 as latest.

### ISSUE THREAD

**Issue by dogweather** [elixir-lsp/vscode-elixir-ls#253]
Maybe there's some extra step that needs to happen to push out 0.10.0?

<img width="195" alt="Screen Shot 2022-06-18 at 11 33 15 PM" src="https://user-images.githubusercontent.com/150670/174467359-7c687795-7114-4e44-aa4e-906f289706d0.png">

**Comment by lukaszsamson** [comment]
We are having problems with vs code marketplace publish

**Comment by dogweather** [comment]
> We are having problems with vs code marketplace publish

Sorry to hear that!

**Comment by lukaszsamson** [comment]
Closing as 0.10.0 is finally released to marketplace
