### ISSUE TITLE
.eex file syntax highlight bug

### ISSUE THREAD

**Issue by ccc1924** [elixir-lsp/vscode-elixir-ls#26]
![深度截图_选择区域_20200109221157](https://user-images.githubusercontent.com/8176393/72077772-ca155b00-3332-11ea-9072-9e61eb701735.png)

**Comment by NobbZ** [comment]
For me this looks correct:

```plain
iex(4)> EEx.eval_string("<%# <%= %> %>")
" %>"
```

**Comment by Fudoshiki** [comment]
@NobbZ Maybe @ccc1924 saying about this bug

Use `cmd` + `/` in VSCode

<img width="833" alt="Снимок экрана 2020-03-03 в 12 41 15" src="https://user-images.githubusercontent.com/4083992/75753293-47b28180-5d4c-11ea-9173-ad2936f91954.png">

Then update page

<img width="885" alt="Снимок экрана 2020-03-03 в 12 41 28" src="https://user-images.githubusercontent.com/4083992/75753313-500abc80-5d4c-11ea-9f6c-4e10d2426023.png">

**Comment by NobbZ** [comment]
It is not a bug in highlighting, as highlighting does the highlighting how EEx will interpret the "comment"…

It is a bug in whatever comments out the code. I'm not sure if this is delegated to the language server or done by something in VScode.

**Comment by axelson** [comment]
If EEx had some sort of block comment operator with a different closing syntax than a normal code tag than this could be supported better, but since that is not the case there is nothing we can do. And an HTML comment is not better IMO since the code is still run which may not be obvious at first.
