### ISSUE TITLE
Feature suggestion: Command to open hexdocs in web browser.

### ISSUE THREAD

**Issue by zorn** [elixir-lsp/vscode-elixir-ls#269]
Wishlist idea: I'd love a new command to, for the function at the current cursor position, open the hexdocs URL in a web browser. 

![FdCRdUvXEAATCnf](https://user-images.githubusercontent.com/52168/191084838-c115970b-33fd-49fc-b553-d2d16303bce4.jpg)

I am aware of the link in the documentation popup but activating that requires me to click a link with my mouse. Maybe I'm missing a way to navigate to that link in the popup?

<https://twitter.com/zorn/status/1571916486566105088>

Thanks for all you do on this project. 💜

**Comment by dacz** [comment]
As an elixir beginner I love the idea.

Whan I started with rust, I figured out this keybinding:

```
{
    "key": "shift+cmd+d",
    "command": "rust-analyzer.openDocs",
    "when": "editorLangId == 'rust'"
  }
```

I tried something similar with elixir, but I'm not able to guess the right command:

``` 
{
    "key": "shift+cmd+d",
    "command": "elixir.???????",
    "when": "editorLangId == 'elixir'"
  }
```

I tried to peek into the code (of rust ls and this repo) but I've never done VSCode plugin and I'm Elixir beginner. I figured out that the command is probably not implemented in this VSCode ext but I do not know, how to get the info from LS and try to make this command and PR. Maybe @Fenix can help?

**Comment by lukaszsamson** [comment]
This would requre adding a custom vscode command, a custom LSP command, implementing it similarity to the current hover LSP command. It is adds up to a lot of work just to add a functionality already covered by current hover. I'd be willing to accept a PR but otherwise I don't plan to address that
