### ISSUE TITLE
Wrong highlight color for string interpolation brackets when using font ligatures

### ISSUE THREAD

**Issue by alexandre-pedroza-h65** [elixir-lsp/vscode-elixir-ls#270]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 23)

* VSCode ElixirLS version: 0.11.0
* Operating System Version: linux 5.19.9-200.fc36.x86_64

### Error

As the title says, if you're using font ligatures, your opening and closing brackets will have different colors:
![image](https://user-images.githubusercontent.com/104759735/191673370-7db65a11-a492-4f2e-a2d6-b04e32ea171d.png)

It does look correct when font ligatures are off:
![image](https://user-images.githubusercontent.com/104759735/191673490-6cb44082-1c90-4249-bfaf-dc4f41a51372.png)

I understand this isn't the most impactful bug ever, but it'd be a nice fix. I can try to take a stab on this if you give me some pointers.

**Comment by lukaszsamson** [comment]
There are similar issues reported upstream
https://github.com/microsoft/vscode/issues/148885
https://github.com/microsoft/vscode/issues/155554
https://github.com/microsoft/vscode/issues/183050
All marked as duplicates of https://github.com/microsoft/vscode/issues/131092
That one is marked as wont-fix

**Comment by lukaszsamson** [comment]
Maybe. Please send a PR if that's easy to do. Keep in mind that `{` is used also for tuples, structs and maps.
