### ISSUE TITLE
The ElixirLS - elixir_learn server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by topazus** [elixir-lsp/vscode-elixir-ls#271]
### Is this the right repo?

I installed the elixir-ls extension in vscode. open a new example project, got error.
`The ElixirLS - elixir_learn server crashed 5 times in the last 3 minutes. The server will not be restarted`.

![image](https://user-images.githubusercontent.com/77263945/192093455-c5d8da90-62e6-433c-ba92-f16f802b67d1.png)

### Environment

Most of this can be filled out by running the VSCode command (by default bound to Ctrl+Shift+P) "ElixirLS: Copy Debug Info"

- Elixir & Erlang versions (elixir --version):
```
$ elixir --version
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 25)
```
- VSCode ElixirLS version: v0.11.0
![image](https://user-images.githubusercontent.com/77263945/192093486-55ef18ce-1692-45df-80a0-74c3ee1d0e16.png)

- Operating System Version:
Fedora

### Troubleshooting

 Restart your editor (which will restart ElixirLS) sometimes fixes issues
 Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
the above steps seem unuseful.

**Comment by lukaszsamson** [comment]
Please post logs from vscode output panel

**Comment by topazus** [comment]
> Please post logs from vscode output panel

After seeing the logs of the vscode output panel about elixir_ls extension, it says a incomplete erlang installation. At the time of writing, I only install elixir by `sudo dnf install elixir`, it may missing some dependencies.
`sudo dnf install erlang` may get a fully complete erlang installation, and the elixir_ls extension works. Many thanks for your prompt tips and works.
