### ISSUE TITLE
"OTP compiled without EEP48 documentation chunks"

### ISSUE THREAD

**Issue by MMAcode** [elixir-lsp/vscode-elixir-ls#284]
Hi team, I am see this alert across my projects.

![image](https://user-images.githubusercontent.com/52301171/203759864-9e9d9aa5-b3de-4421-92da-dcec30d3223e.png)

Before, it was not even compiling/crushing (or sth like that, if I remember correctly, saying that no erlang version specified in .tool_versions so I did that manually as advised by logs on screen. Due to that elixirls starts, but now this issue occured.

![image](https://user-images.githubusercontent.com/52301171/203762285-84fa051a-1326-424b-87aa-65addeff7490.png)

### Environment
* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]
Elixir 1.14.0 (compiled with Erlang/OTP 25)
* VSCode ElixirLS version: 0.12.0
* Operating System Version: darwin 21.6.0 (Mac M1)
Most of this can be filled out by running the VSCode command (by default bound to Ctrl+Shift+P) "ElixirLS: Copy Debug Info"

### Troubleshooting
- [ tried] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [ tried] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

**Comment by DuldR** [comment]
I don't think this is an issue with ElixirLS, but with Erlang itself. This is how I fixed it on Ubuntu 22.04. I assume you're using asdf with a `.tool-versions` file.

1. Remove Erlang by `asdf plugin remove erlang`
2. Follow the instructions at https://github.com/asdf-vm/asdf-erlang#getting-erlang-documentation and set `export KERL_BUILD_DOCS=yes` for the erlang documentation.
3. Run `asdf install`
4. You should see the following from `asdf current `
![image](https://user-images.githubusercontent.com/36017878/204122214-f9c130a3-aa68-40b1-b29f-a083d5cb91a5.png)
5. Set the global usage of erlang - `asdf global erlang latest`
6. Restart the language server

**Comment by lukaszsamson** [comment]
@MMAcode please use elixir forum for support on how to install OTP with doc chunks. Otherwise you can ignore this warning but OTP related functionality (e.g. hover documentation) will not work.

**Comment by sabit990928** [comment]
Thanks for sharing @DuldR. Worked for me, at least working for now 😁

**Comment by lcmen** [comment]
Thank you @DuldR 🥂 , works for me on elixirls and neovim.
