### ISSUE TITLE
Request - Bump Elixir-LS

### ISSUE THREAD

**Issue by VictorGaiva** [elixir-lsp/vscode-elixir-ls#285]
Request: Bump elixir-ls version get resolved issues from upstream:

https://github.com/elixir-lsp/elixir-ls/issues/772

**Comment by VictorGaiva** [comment]
Hey @lukaszsamson. Sorry for the ping, but would it be possible to bump it? My compilations time are very high (10+ minutes), and the older version of the plugin seems to be crashing all the time too because of my Elixir version.

**Comment by lukaszsamson** [comment]
v0.13.0 released
