### ISSUE TITLE
Cannot register 'elixirLS.envVariables'. This property is already registered.

### ISSUE THREAD

**Issue by MichealThabbet** [elixir-lsp/vscode-elixir-ls#288]
Type: <b>Performance Issue</b>

Cannot register 'elixirLS.envVariables'. This property is already registered.

Extension version: 0.12.0
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.90GB (4.28GB free)|
|Process Argv|C:\\Users\\Marianne\\AppData\\Local\\Temp\\Rar$DIa4276.19246\\Program.cs --crash-reporter-id e16477a8-47fb-4336-9313-4e6bd27ae480|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   169	 17220	code main
    0	    85	  4928	   utility-network-service
    0	   256	  6152	   window (Extension: ElixirLS: Elixir support and debugger - New folder - Visual Studio Code)
    2	   107	 10092	   issue-reporter
    0	   284	 10900	   gpu-process
    0	   149	 12524	   shared-process
    0	    84	  8628	     fileWatcher
    0	    86	 13564	     ptyHost
    0	    80	 12668	   utility
    0	    81	 13736	   crashpad-handler
    0	    65	 14372	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: ElixirLS: Elixir support and debugger - New folder - Visual Studio Code)
|    Folder (New folder): 0 files
|      File types:
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by lukaszsamson** [comment]
Please provide more info about the issue
