### ISSUE TITLE
Testing tab errors when tests have "doctest"

### ISSUE THREAD

**Issue by Carl-Foster** [elixir-lsp/vscode-elixir-ls#291]
The testing tab with the test lens appears to throw an exception when a `doctest` is defined in a test.
By deleting the `doctest` line in the generated test file, the testing tab works as expected.

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.2 (compiled with Erlang/OTP 25)

* VSCode ElixirLS version: 0.13.0
* Operating System Version: darwin 22.1.0

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

### Crash report template

_Delete this section if not reporting a crash_

1.  Create a new Mix project with `mix new empty --sup`, then open that project with VS Code and open an Elixir file.
2. Run command: `Test: Run all tests`
3. Output: Permanent running tests with error in extension host
`[error] Error: %MatchError{term: "doctest Empty.hello/0 (1)"}`

**Comment by Carl-Foster** [comment]
I now realise this is probably a bug within elixir-ls. After I re-added back the `doctest`, the testing tab still worked, although the extension host continued to have errors.

**Comment by Carl-Foster** [comment]
I think the error may be caused here: https://github.com/elixir-lsp/elixir-ls/blob/d9dc1b1e810c2bc653aa6d9f886c75c3eb1525cb/apps/language_server/lib/language_server/ex_unit_test_tracer.ex#L83

**Comment by lukaszsamson** [comment]
Fixed in https://github.com/elixir-lsp/vscode-elixir-ls/pull/293
