### ISSUE TITLE
test using 'Test Lenses' button not working properly

### ISSUE THREAD

**Issue by Dylan-aidkr** [elixir-lsp/vscode-elixir-ls#292]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace] Elixir 1.14.1 (compiled with Erlang/OTP 25)
* VSCode ElixirLS version: 0.13.0
* Operating System Version: darwin 21.6.0

### 
![스크린샷 2023-01-12 오후 2 38 46](https://user-images.githubusercontent.com/107099503/211988194-8b48d366-59ca-4d4c-9978-b2f520a3844c.jpeg)

first clicking 'run test' on test lens open 'ElixirLS' terminal and make such outputs, which not executed.

after that, clicking button again  just clear out terminal and not running test.

no errors found on extension logs and extension host logs

i am trying to debug it myself. but not sure where to look.

**Comment by lukaszsamson** [comment]
The behavior of Run Test code lens has been unified to use Testing UI
Fixed in https://github.com/elixir-lsp/vscode-elixir-ls/pull/293
