### ISSUE TITLE
Just a question: Dialyzer not showing spec discrepancies.

### ISSUE THREAD

**Issue by CharlesIrvineKC** [elixir-lsp/vscode-elixir-ls#295]
I hope it's alright to ask an ElixirLS question here.

Say I have a function with a spec like this:

```
@spec my_func(list()) :: list()
def my_func(arg), do: []
```

In a test case, if I do this:

```
test "test my_fiunc" do
   assert my_func(1) == []
end
```

Shouldn't this trigger a warning for the assert call complaining that 1 is not a list?

I have an situation like this in my code, I can't see any dialyzer related output. I'm using vscode.

**Comment by lukaszsamson** [comment]
Dialyzer can only check compiled modules. .exs files are not compiled when running ’mix compile’

**Comment by CharlesIrvineKC** [comment]
Yep. Makes perfect sense. Thanks
