### ISSUE TITLE
Dialyzer is too slow on automatic updates

### ISSUE THREAD

**Issue by jedeleh** [elixir-lsp/vscode-elixir-ls#296]
When I'm working with ElixirLS & VSCode, dialyzer feedback (errors & warnings) update slowly--anywhere from 5-10 seconds. This is a lifetime. If there's no way to make the feedback more real-time, then perhaps provide a way to disable dialyzer behavior? 

### Environment

MacOS Monterrey (M1 chip)

Elixir 1.8.2 (compiled with Erlang/OTP 21)

* VSCode ElixirLS version: 0.7.0
* Operating System Version: darwin 21.6.0

- Elixir & Erlang versions (elixir --version):
- VSCode ElixirLS version:
- Operating System Version:

# Steps to reproduce. 
- Type in code that triggers an error or warning via dialyzer.
- Wait 5-10 seconds for error or warning to show up.
- Fix code
- It takes 5-10 seconds to refresh that line and either remove the coloration or leave it there with a new message.

That's 5-10 seconds of me sitting there waiting for the error/warning to update. Plus, if the "fix" fails to fix the error/earning--even worse turns the warning into an error--This can be a huge interruption in the flow.

**Comment by lukaszsamson** [comment]
Unfortunately there is no easy answer. We did some optimization of dialyzer back in 2020 but we are hitting a limits of the OTP library here. Later we even decided at some point to limit number of cores used by dialyzer as it made CPUs hot unnecessarily. That made it slower but more predictable. OTP 26 may bring some improvement as it introduces incremental dialyzer but that will likely require some work.

> If there's no way to make the feedback more real-time, then perhaps provide a way to disable dialyzer behavior?

It is already supported, please try `elixirLS.dialyzerEnabled` option. Alternatively you can try to disable some expensive checks.
