### ISSUE TITLE
Configure where to store the downloaded and compiled LS

### ISSUE THREAD

**Issue by NobbZ** [elixir-lsp/vscode-elixir-ls#3]
Let the user choose where the LS sources and binaries should be stored and whether or not they should be managed by this plugin or something else (which would deactivate auto update as described in #2).

**Comment by lukaszsamson** [comment]
What would be the benefit?

**Comment by NobbZ** [comment]
When I wrote this, I had to use different versions of the LS for different projects, or at least same version compiled with different erlangs/elixir combinations.

If I had been able to configure each version for each project it would had helped me a lot.

Also it would make testing self-made changes to the LSP itself easier if one could just change the PATH, instead of having to actually start VScode in development mode with an ElixirLS plugin that has been edited to use the local version of the LSP.

Though as I said in #1 and #2, I'm not using VScode anymore and therefore those issues are not relevant for me. I'm just trying to point out why I have created them initially.

**Comment by DragosMocrii** [comment]
@NobbZ what do you use in place of VSCode?

**Comment by NobbZ** [comment]
Emacs with `lsp-mode`, it just searches for the binary in `PATH`, so I make sure via an `.envrc` that the correct version of elixir LS is in `PATH` first.

**Comment by lukaszsamson** [comment]
Obsoleted by https://github.com/elixir-lsp/vscode-elixir-ls/pull/317. You can now use `MIX_INSTALL_DIR` to tell mix to store packages in a different directory. Refer to [Mix.install docks](https://hexdocs.pm/mix/1.14.4/Mix.html#install/2)
