### ISSUE TITLE
Setting MIX_ENV=test in the test lenses

### ISSUE THREAD

**Issue by guess** [elixir-lsp/vscode-elixir-ls#316]
When setting `"elixirLS.enableTestLenses": true` and running the tests, they currently just run `mix test ...`. I was wondering if it was possible to have it run with `MIX_ENV=test mix test ...` preceding it?

**Comment by lukaszsamson** [comment]
Why would you nedd that? mix test sets env to test by default.

**Comment by lukaszsamson** [comment]
@guess How do you end up running tests in a different env? `mix test` raises in that case https://github.com/elixir-lang/elixir/blob/6f96693b355a9b670f2630fd8e6217b69e325c5a/lib/mix/lib/mix/tasks/test.ex#L473

**Comment by guess** [comment]
Sorry i missed your first message. 

It's because I am running in a vscode devcontainer where the MIX_ENV is set to dev by default
