### ISSUE TITLE
VSCode hangs after elixir_ls update

### ISSUE THREAD

**Issue by kkalb** [elixir-lsp/vscode-elixir-ls#318]
Hello!

After I reloaded vscode after it updated the extension, my virtual machine completely freezes.
I retried 6 times now and it's the same everytime. I can not look anything up in vscode because after starting it, it hangs.

In .vscode/extensions I find jakebecker.elixir-ls-0.14.0 which was updated/released this night (04/14/23)

Task manager on host shows 30% CPU and 50% disk usage for the VM alone (system is on higher end regarding specs).

When I run a script to recompile/release elixir_ls in the extension folder with my elixir/erlang versions, it crashes on vscode boot but I now can use vscode again.

Elixir & Erlang versions (elixir --version):

- Elixir: 1.14.1-otp-25
- Erlang: 25.2.1

VSCode ElixirLS version:

- Todays update (0.14.0)

Operating System Version:

- Ubuntu 22.04 (VirtualBox) on Windows host

**Comment by lukaszsamson** [comment]
> When I run a script to recompile/release elixir_ls in the extension folder with my elixir/erlang versions, it crashes on vscode boot but I now can use vscode again.

Since 0.14.0 the extension uses Mix.install to manage elixir-ls. You shouldn't be doing anything there. Please read the updated README on how to run local version

**Comment by kkalb** [comment]
> > When I run a script to recompile/release elixir_ls in the extension folder with my elixir/erlang versions, it crashes on vscode boot but I now can use vscode again.
> 
> Since 0.14.0 the extension uses Mix.install to manage elixir-ls. You shouldn't be doing anything there. Please read the updated README on how to run local version

Good to know! 

Nevertheless, the bug has nothing to do with the script.

I ran the script to fix it, after the bug was already holding me back from using vscode. And by fixing I mean potentially breaking it, enabling me to use vscode again.

**Comment by christiansb91** [comment]
All my work colleagues has the same problem. ElixirLs has been updated to v0.14.0, now when some .ex file is open the computer keeps completely freezes.

We run it on Ubuntu 22.04 with Docker

**Comment by kkalb** [comment]
I managed to find the correct command:

First of all go to your home folder

```bash
~/.vscode/extensions
```

and make sure to delete

```bash
jakebecker.elixir-ls-0.14.0
```
then open vscode, open a terminal and type
```bash
code --install-extension jakebecker.elixir-ls@0.13.0
```
Afterwards go to your extensions and "Enable" the extension, but do not update it until a hotfix is also applied to this repo. Elixir-ls main repo released 0.14.1 the time writing.

**Comment by mrroot5** [comment]
While we wait for a fix just **change your version**.

This is how to do it by UI.

![image](https://user-images.githubusercontent.com/1659540/232024877-0651c319-284c-48af-84fd-dc3da75e8ff0.png)

Check @kkalb [solution](https://github.com/elixir-lsp/vscode-elixir-ls/issues/318#issuecomment-1508247409) to do it by command.

**Comment by kkalb** [comment]
> While we wait for a fix just **change your version**.
> 
> This is how to do it by UI.
> 
> ![image](https://user-images.githubusercontent.com/1659540/232025872-2920c61a-a1c7-466d-a8d8-92ca6c23606e.png)
> 
> ![image](https://user-images.githubusercontent.com/1659540/232025790-fbe46fe3-e91e-44a0-a46b-4367ccb5e1fb.png)
> 
> Check @kkalb [solution](https://github.com/elixir-lsp/vscode-elixir-ls/issues/318#issuecomment-1508247409) to do it by command.

I also tried this but it did not work for me, since we need to have it installed to change the version by UI.
If you install it, it got enabled and thus started and freezed.
That's why I needed to install it directly via command.

**Comment by christiansb91** [comment]
You can try opening vscode in an empty folder and disabling the extension then installing another version via the UI. The problem starts when an .ex file is opened I think.

**Comment by dvic** [comment]
I'm experiencing the same issue. Is everyone here with the same problem using ASDF? (I am)

**Comment by mrroot5** [comment]
> I'm experiencing the same issue. Is everyone here with the same problem using ASDF? (I am)

My colleague had a problem with asdf. I use asdf too. Using the previous ElixirLS version (0.13) work for us.

**Comment by dvic** [comment]
I somehow fixed the issue by manually running in an iex shell `Mix.install([{:elixir_ls, github: "elixir-lsp/elixir-ls", tag: "v0.14.0"}])` and then reinstalling the extension. A beam process then still spiked in memory usage and I killed it, but the extension started fine, and now there are no memory spikes 🤷🏻‍♂️

**Comment by kkalb** [comment]
> I somehow fixed the issue by manually running in an iex shell `Mix.install([{:elixir_ls, github: "elixir-lsp/elixir-ls", tag: "v0.14.0"}])` and then reinstalling the extension. A beam process then still spiked in memory usage and I killed it, but the extension started fine, and now there are no memory spikes 🤷🏻‍♂️

In your project's root or in the extension folder? Maybe **elixir-lsp/elixir-ls** is fixed now but the problem seems to be the version of **elixir-lsp/vscode-elixir-ls** still using 0.14.0 instead of 0.14.1.

**Comment by dvic** [comment]
> In your project's root or in the extension folder? Maybe **elixir-lsp/elixir-ls** is fixed now but the problem seems to be the version of **elixir-lsp/vscode-elixir-ls** still using 0.14.0 instead of 0.14.1.

I just ran this in a shell in my home folder. I guess the 0.14.1 elixir-ls fixes this issue?

**Comment by lukaszsamson** [comment]
I pushed a new release v0.14.2 that should resolve those issues

**Comment by YLivay** [comment]
> I pushed a new release v0.14.2 that should resolve those issues

Hmm files dont seem to be processed by the extension at all now. In dev console im seeing:
```languageConfigurationExtensionPoint.ts:139 Errors parsing file:///home/user/.vscode/extensions/jakebecker.elixir-ls-0.14.2/elixir-language-configuration.json: [0, 0] Value expected
...
log.ts:441   ERR Unable to load and parse grammar for scope source.elixir from file:///home/user/.vscode/extensions/jakebecker.elixir-ls-0.14.2/syntaxes/elixir.json SyntaxError: Unexpected end of JSON input
...
```
Seems like `elixir-language-configuration.json` and `elixir.json` files are empty?

Using vscode 1.77.3 on Fedora 37. Installed elixir 1.12.3-otp-24 and erlang 24.3 through asdf.

Reinstalling the extension doesnt seem to help.

**Comment by tfl** [comment]
v0.14.2 fixed it for me. Nothing special has been done here, just updated from within VSCode. Thanks!

**Comment by lukaszsamson** [comment]
@YLivay You have something broken with your setup. The files are not empty. BTW Elixir 1.12 is not supported on OTP 24. You need to either upgrade elixir or downgrade OTP.

**Comment by YLivay** [comment]
@lukaszsamson Indeed something was broken but I'm not sure what caused it. Removing the extension folder completely and reinstalling fixed the issue on my end :)

p.s. 1.12 should be supported on OTP 24 (at least according to https://hexdocs.pm/elixir/1.12.3/compatibility-and-deprecations.html)

**Comment by lukaszsamson** [comment]
I'm going to close this. If anyone still experiencing problems on 0.14.5 please open a new issue.
