### ISSUE TITLE
Cannot make this extension completely work on windows or WSL

### ISSUE THREAD

**Issue by ferdef** [elixir-lsp/vscode-elixir-ls#32]
I've been using this extension on Mac for a year (well, first the original and then the fork) and it works very well. However I've switched to a Windows machine recently and I've tried to make it work with no success.

Having Elixir and erlang with a compatible OTP (1.9.1-otp22 and otp 22), I open up an elixir project and:

- On both platforms I always get the message saying that the build is stopped because the cwd has changed (just removing the trailing `.`)
- In windows I get everything working except the @spec feature
- In WSL I cannot even get the code problems to be processed, so I only get the code documentation when hoovered. Taking a look on the `Output` window I can see that `CodeLens` gives an error.

WSL uses asdf, by the way

Is there anything I must do to make it work?

**Comment by shanlalit** [comment]
Hi @ferdef,

I'm also seeing similar issues on my Ubuntu 19.04 installation 
- Suggest @spec is not working
- Compile errors are not visible in the vscode
- Code documentation and code completion is working
- I'm running Elixir 1.10, It was working fine with Elixir 1.9 (I don't have version manager to quickly check if it still works with Elixir 1.9)

For this simple error in my code **"def get_task(task,, date) do"**
Here is what I see in the ElixirLS output in message mode: 

> [Trace - 10:01:23 PM] Sending notification 'textDocument/didSave'.
> [Trace - 10:01:23 PM] Sending notification 'workspace/didChangeWatchedFiles'.
> [Trace - 10:01:29 PM] Sending notification 'textDocument/didChange'.
> [Trace - 10:01:29 PM] Sending notification '$/cancelRequest'.
> [Trace - 10:01:29 PM] Sending request 'textDocument/codeLens - (72)'.
> [Trace - 10:01:29 PM] Received response 'textDocument/codeLens - (63)' in 11987ms. Request failed: Request cancelled (-32800).
> [Trace - 10:01:30 PM] Sending request 'textDocument/documentSymbol - (73)'.
> [Trace - 10:01:30 PM] Received response 'textDocument/documentSymbol - (73)' in 4ms. Request failed: an exception was raised:
>     ** (SyntaxError) nofile:7: syntax error before: ','
>         (language_server 0.2.28) lib/language_server/providers/document_symbols.ex:41: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
>         (language_server 0.2.28) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/2
>         (language_server 0.2.28) lib/language_server/server.ex:442: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2 (-32000).
> [Error - 10:01:30 PM] Request textDocument/documentSymbol failed.
>   Message: an exception was raised:
>     ** (SyntaxError) nofile:7: syntax error before: ','
>         (language_server 0.2.28) lib/language_server/providers/document_symbols.ex:41: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
>         (language_server 0.2.28) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/2
>         (language_server 0.2.28) lib/language_server/server.ex:442: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
>   Code: -32000 
> [Trace - 10:01:30 PM] Received notification 'window/logMessage'.
> 
> 22:01:30.139 [error] Process #PID<0.188.0> raised an exception
> ** (SyntaxError) nofile:7: syntax error before: ','
>     (language_server 0.2.28) lib/language_server/providers/document_symbols.ex:41: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
>     (language_server 0.2.28) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/2
>     (language_server 0.2.28) lib/language_server/server.ex:442: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
>

**Comment by shanlalit** [comment]
Hi @ferdef,

My issue is resolved, as it was specifically with .exs file.
According the ElixirLS readme -- in order to debug modules in .exs files (such as tests), they must be specified under requireFiles.

and there is one more thing :) which stops the compile error and spec suggestions on .ex files also
> On both platforms I always get the message saying that the build is stopped because the cwd has changed (just removing the trailing .)

I removed this trailing . and it works fine, however if you add it once again it will stop showing the compile errors. So make sure your Elixr LS: Project Dir is blank.

I hope it solves your problem.

**Comment by ferdef** [comment]
Thank you very much @shanlalit !!!

Removing the `.` on **Elixir LS Project Dir** makes it work on both `Windows` and `WSL`. Amazing, now I can work on both platforms as I was doing on MacOS.
