### ISSUE TITLE
Test lenses stopped work

### ISSUE THREAD

**Issue by sl1depengwyn** [elixir-lsp/vscode-elixir-ls#321]
Since 0.14.0 test lenses do not run in terminal, all that happens after the click that I was able to notice is warning from elixir that test file was reloaded in the output tab, but nothing more

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

* VSCode ElixirLS version: 0.14.0
* Operating System Version: darwin 22.4.0

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

**Comment by lukaszsamson** [comment]
I can confirm that problem. Most likely introduced in https://github.com/elixir-lsp/vscode-elixir-ls/pull/293. Anyway I'm leaning towards removing Run test code lense in vscode extension as it duplicates functionality of the builtin Test UI

**Comment by lukaszsamson** [comment]
There was no dedicated support for setting env on mix test. The old implementation used terminal and executed `mix test` there. The new one simply calls `mix test` directly in the project dir.
If you have an idea how to pass env you can open a PR

**Comment by jbosse** [comment]
I much prefer the terminal to Test UI so I hope this gets resolved soon.

**Comment by thetamind** [comment]
> I much prefer the terminal to Test UI.

I've found these extensions useful to run focused tests in the terminal; although they use commands, not code lenses.

- [Run Elixir Test in iTerm][iterm]
- [Elixir Test in IEx][iex]

[iterm]: https://marketplace.visualstudio.com/items?itemName=duarde-taulie.run-elixir-test-in-iterm
[iex]: https://marketplace.visualstudio.com/items?itemName=ScottMing.elixir-test-in-iex

**Comment by lukaszsamson** [comment]
@jbosse @thetamind In vscode you can use Terminal->Run task..->mix->test. The extension provides a few common mix tasks through https://code.visualstudio.com/api/extension-guides/task-provider. You can provide your own tasks for your workspace, see https://code.visualstudio.com/docs/editor/tasks

**Comment by lukaszsamson** [comment]
BTW this PR makes Test UI use the default launch config for `mix test` https://github.com/elixir-lsp/vscode-elixir-ls/pull/329

**Comment by jbosse** [comment]
> @jbosse @thetamind In vscode you can use Terminal->Run task..->mix->test. The extension provides a few common mix tasks through https://code.visualstudio.com/api/extension-guides/task-provider. You can provide your own tasks for your workspace, see https://code.visualstudio.com/docs/editor/tasks

@lukaszsamson Thanks for pointing that out. It was better than using TestUI but less convenient then just clicking "Run test" on a test.

The TestUI interface is not as elegant as it used to be just having a split terminal view where the test lens was running mix test commands.
