### ISSUE TITLE
Debug test function is not using "mix test" setup in launch.json

### ISSUE THREAD

**Issue by dpurrington** [elixir-lsp/vscode-elixir-ls#328]
When running or debugging tests from the "Testing" view, a hard-coded config is being used. It's not clear where this comes from. In other testing and debugging contexts, the launch.config file is being used. I propose to use that file here (using the one named "mix test") and document the fact.

### Is this the right repo?

Yes, because I see in the code where this functionality lives.

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.4 (compiled with Erlang/OTP 25)

* VSCode ElixirLS version: 0.14.5
* Operating System Version: linux 5.19.0-41-generic

### Troubleshooting

Issue persists across restarts. I think this is expected behavior.

**Comment by lukaszsamson** [comment]
The tasks simply run `MIX_ENV=test mix test` so it's your `config.exs` that decides if apps are started. While you may have some custom stuff in launch config I'm not convinced it's what most people do. Launch config does not exist at all by default. Does other languages do something similar?

**Comment by dpurrington** [comment]
I think once you're at the debugging code stage you're going to have the launch.json setup.

As I read [the code](https://github.com/elixir-lsp/vscode-elixir-ls/blob/master/src/commands/runTest.ts#L44), "mix test" is not used in the debug command. It is used in the `run` command, however.

**Comment by dpurrington** [comment]
I created a PR that preserves the current behavior if there is no "mix test" configuration found, but uses it if it does. Let me know what you think about it. I don't have anything exotic in my config, but I do have "--no-start".

**Comment by lukaszsamson** [comment]
Fixed in https://github.com/elixir-lsp/vscode-elixir-ls/pull/329
