### ISSUE TITLE
Formatter hangs on VSCode 1.42.0

### ISSUE THREAD

**Issue by andreapavoni** [elixir-lsp/vscode-elixir-ls#34]
I get this everytime I try to save an Elixir file:

```
Running Save Participants for 'test/users/notifications/mailer/some_mailer_test.exs': Formatting
```

It doesn't even save the file until i `Cancel` the message above. Once I cancelled it, it also formats the file. However, it's a really annoying behaviour.

It works fine if you downgrade VSCode to 1.41 or less.

Am I the only one with this problem on VSCode 1.42.0 ?

I've seen there are other Extensions with this problem, here's a PR from another project that explains and fixes it: https://github.com/zxh0/vscode-proto3/pull/73

**Comment by minibikini** [comment]
I'm experiencing the same with Formatter.

**Comment by andreapavoni** [comment]
@minibikini it turned out the problem (at least in my own case) was caused by an old `elixir-formatter` extension which was installed along with `elixir-ls`.

Removing that extension solved the problem, formatter works again.

Maybe I should close this issue.

**Comment by minibikini** [comment]
Hm, I don't have `elixir-formatter`, my formatter is `elixir-lsp.elixir-ls`.

**Comment by axelson** [comment]
@andreapavoni can you send a link to that incompatible formatter that you were using? I'd like to add it to the list of incompatible extensions.

@minibikini Can you send details of your setup? You can get initial details by running the "ElixirLS Fork: Copy Debug Info" command. Also please list your installed extensions and check your logs (via View->Output->ElixirLS Fork) for any potentially relevant info.

**Comment by andreapavoni** [comment]
@axelson I don’t remember for sure, but it should be one of these two (probably the second one):

- https://marketplace.visualstudio.com/items?itemName=saratravi.elixir-formatter

- https://marketplace.visualstudio.com/items?itemName=sammkj.vscode-elixir-formatter

It was a very old one, I don’t remember when I’ve installed it. I’ve just found to have it, I removed it, and everything worked as expected.

**Comment by minibikini** [comment]
@axelson not sure what happened but it works fine now.

**Visual Studio Code**

```
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z (5 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**ElixirLS Fork: Copy Debug Info**

```
  * Elixir & Erlang versions (elixir --version): Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.2 (compiled with Erlang/OTP 22)

  * VSCode ElixirLS Fork version: 0.3.2
  * Operating System Version: darwin 18.7.0
```

**Installed extentions**

```
karunamurti.haml-1.3.0
kumar-harsh.graphql-for-vscode-1.15.3
marcostazi.vs-code-vagrantfile-0.0.7
mauve.terraform-1.4.0
mrmlnc.vscode-stylefmt-2.5.0
mrorz.language-gettext-0.1.1
ms-azuretools.vscode-docker-1.0.0
ms-python.python-2020.3.71659
ms-vscode.theme-markdownkit-0.1.4
nuuf.theme-hackershaze-2.0.1
octref.vetur-0.24.0
pgourlain.erlang-0.5.2
rebornix.ruby-0.27.0
ricard.postcss-2.0.0
riussi.code-stats-vscode-1.0.18
robinbentley.sass-indented-1.5.1
rust-lang.rust-0.7.0
sammkj.vscode-elixir-formatter-0.2.0
samverschueren.final-newline-0.3.2
sensourceinc.vscode-sql-beautify-0.0.4
shanoor.vscode-nginx-0.6.0
shinnn.stylelint-0.51.0
stefanjarina.vscode-eex-snippets-0.0.6
streetsidesoftware.code-spell-checker-1.8.0
streetsidesoftware.code-spell-checker-russian-0.2.4
TeddyDD.fish-0.0.4
wingrunr21.vscode-ruby-0.27.0
yzhang.markdown-all-in-one-2.8.0
zhuangtongfa.material-theme-3.2.5
```

**Comment by minibikini** [comment]
Formatter still hangs for me. Nothing in the ElixirLS logs. :/

<img width="476" alt="Screen Shot 2020-04-18 at 4 54 47 PM" src="https://user-images.githubusercontent.com/439309/79638210-7cac5380-8195-11ea-9a03-a14c84e75ac6.png">

**Comment by andreapavoni** [comment]
@minibikini have you tried to uninstall your elixir-formatter extension at all? Your files should be formatted anyway.

**Comment by minibikini** [comment]
@andreapavoni I think my formatter is part of ElixirLS and I can't uninstall it separately.  I could disable formatting but prefer to keep it and restart vscode once in an hour (it helps in my case).

**Comment by axelson** [comment]
@minibikini Please uninstall `sammkj.vscode-elixir-formatter-0.2.0` and try again. Installing that extension reproduced your issue for me and the next version of vscode-elixir-ls will give a warning if it is installed.

**Comment by minibikini** [comment]
Oh, right. I thought I already uninstalled that.

**Comment by minibikini** [comment]
thanks, @axelson!

**Comment by axelson** [comment]
You're welcome! I'm glad that fixed it!

**Comment by minibikini** [comment]
@axelson Looks like the formatter still hangs for me 😢  
Nothing suspicions in logs.

**Comment by minibikini** [comment]
After looking again at the logs I found something which looks like ElixirLS error:

```
[Info  - 6:38:25 PM] Returning location struct
[Info  - 6:38:26 PM] [ElixirLS Dialyzer] Analysis finished in 3934 milliseconds
[Info  - 6:38:27 PM] Dialyzer analysis is up to date
/usr/local/Cellar/erlang/22.3.2/lib/erlang/lib/kernel-6.5.2/src/os.erl: 
at line 26: 
can't find include file "file.hrl"

[Warn  - 6:38:27 PM] docsh error: error
[{edoc,'-check_forms/3-fun-0-',3,[{file,"edoc.erl"},{line,712}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {edoc,read_source,2,[{file,"edoc.erl"},{line,581}]},
 {edoc_extract,source,3,[{file,"edoc_extract.erl"},{line,57}]},
 {docsh_edoc,to_internal,2,
             [{file,"/home/jason/dev/forks/vscode-elixir-ls/elixir-ls/deps/docsh/src/docsh_edoc.erl"},
              {line,43}]},
 {docsh_lib,convert_one,1,
            [{file,"/home/jason/dev/forks/vscode-elixir-ls/elixir-ls/deps/docsh/src/docsh_lib.erl"},
             {line,42}]},
 {lists,flatmap,2,[{file,"lists.erl"},{line,1250}]},
 {docsh_lib,convert,3,
            [{file,"/home/jason/dev/forks/vscode-elixir-ls/elixir-ls/deps/docsh/src/docsh_lib.erl"},
             {line,37}]}]

[Info  - 6:38:29 PM] [ElixirLS Dialyzer] Writing manifest...
[Info  - 6:38:31 PM] [ElixirLS Dialyzer] Done writing manifest in 3623 milliseconds.
[Info  - 6:38:40 PM] [ElixirLS WorkspaceSymbols] Indexing...
Compiling with Mix env test
RUM enabled: false
[Info  - 6:38:41 PM] [ElixirLS WorkspaceSymbols] Module discovery complete
[Info  - 6:38:43 PM] [ElixirLS WorkspaceSymbols] 773 callbacks added to index
[Info  - 6:38:53 PM] Compile took 12967 milliseconds
[Info  - 6:38:53 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 6:38:54 PM] [ElixirLS WorkspaceSymbols] 2614 modules added to index
[Info  - 6:38:54 PM] [ElixirLS Dialyzer] Found 0 changed files in 132 milliseconds
[Info  - 6:38:57 PM] [ElixirLS WorkspaceSymbols] 1622 types added to index
[Info  - 6:38:59 PM] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 6:38:59 PM] [ElixirLS Dialyzer] Analysis finished in 4763 milliseconds
[Info  - 6:39:00 PM] Dialyzer analysis is up to date
[Info  - 6:39:02 PM] [ElixirLS Dialyzer] Writing manifest...
[Info  - 6:39:03 PM] [ElixirLS Dialyzer] Done writing manifest in 3647 milliseconds.
[Info  - 6:39:28 PM] [ElixirLS WorkspaceSymbols] 30707 functions added to index
```

**Comment by axelson** [comment]
@minibikini what OS are you running and how did you install Elixir and Erlang? Maybe you have an incomplete installation of Erlang.

**Comment by minibikini** [comment]
- OSX 10.14.6
- Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
- Elixir 1.10.2 (compiled with Erlang/OTP 22)

I'll try to reinstall it, thanks.

**Comment by axelson** [comment]
@minibikini but how did you install elixir/erlang? homebrew? asdf? etc.

**Comment by minibikini** [comment]
Homebrew

**Comment by axelson** [comment]
@minibikini Did reinstalling help? I'm not able to reproduce when using elixir installed via homebrew. Does it also fail if you install elixir and erlang via asdf?

**Comment by minibikini** [comment]
Hopefully, yes - so far it works fine. 

I didn't try `asdf`. Will do if the the issue occur again.

**Comment by minibikini** [comment]
@axelson formatter still hangs, but it's probably not ElixirLS fault because I've noticed that erlang formatter hangs too. I've tried to install elixir and erlang via asdf, also reinstalled VSCode.

**Comment by axelson** [comment]
Okay, well if you figure it out please report back! Best of luck :)

**Comment by bstro** [comment]
I had this same issue and realized it was because I had set my default formatter to Prettier in my user settings. So prettier was trying to format my elixir files instead of vscode-elixir-ls.

**Comment by kevboh** [comment]
Hello! This is happening to me fairly reliably. I do not have any other formatters installed or set to my default formatter. My debug info is

```
* Elixir & Erlang versions (elixir --version): Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.13.0 (compiled with Erlang/OTP 24)

* VSCode ElixirLS version: 0.9.0
* Operating System Version: darwin 20.6.0
```

Elixir and erlang are installed via asdf.

Closing and reopening vscode seems to "fix" the formatter for one formatting action before it begins to hang again. Same with reshimming asdf. There is no other output in the dev console.

**Comment by kevboh** [comment]
Out of curiosity, I downgraded to 0.8.1 and this still occurs. I was able to format twice in quick succession, but after making some edits and attempting to format again it hung.
