### ISSUE TITLE
`v0.15.0` breaks syntax highlighting

### ISSUE THREAD

**Issue by ryanwinchester** [elixir-lsp/vscode-elixir-ls#344]
See images.

Before update
<img width="835" alt="Screenshot 2023-06-20 at 9 06 11 AM" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/2897340/b4ea4f58-e44d-44e3-94fd-55359e63948c">

After update
<img width="844" alt="Screenshot 2023-06-20 at 9 04 48 AM" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/2897340/3eeddcf8-4ac9-4fdc-ab01-70c63b2305a6">

**Comment by joaopealves** [comment]
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/56173070/b5eaf9a4-be8a-49ff-97a3-bed2311bff38)
It is worth pointing out that this color induces one to think that there is something wrong in the syntax

**Comment by NobbZ** [comment]
I have massive problems with "doc-comments" not beeing closed ever…

Sorry for the crop, but I have to be careful with sensitive code.

In the output-panes "window" log I can see the follwing traces:

```text
2023-06-20 16:03:15.998 [error] an exception was raised:
    ** (CaseClauseError) no case clause matching: nil
        (elixir_sense 2.0.0) lib/elixir_sense/providers/docs.ex:58: ElixirSense.Providers.Docs.mod_fun_docs/9
        (elixir_sense 2.0.0) lib/elixir_sense.ex:74: ElixirSense.docs/3
        (language_server 0.15.0) lib/language_server/providers/hover.ex:24: ElixirLS.LanguageServer.Providers.Hover.hover/4
        (language_server 0.15.0) lib/language_server/server.ex:828: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2: Error: an exception was raised:
    ** (CaseClauseError) no case clause matching: nil
        (elixir_sense 2.0.0) lib/elixir_sense/providers/docs.ex:58: ElixirSense.Providers.Docs.mod_fun_docs/9
        (elixir_sense 2.0.0) lib/elixir_sense.ex:74: ElixirSense.docs/3
        (language_server 0.15.0) lib/language_server/providers/hover.ex:24: ElixirLS.LanguageServer.Providers.Hover.hover/4
        (language_server 0.15.0) lib/language_server/server.ex:828: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
	at handleResponse (/Users/norbert.melzer/.vscode/extensions/jakebecker.elixir-ls-0.15.0/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)
	at handleMessage (/Users/norbert.melzer/.vscode/extensions/jakebecker.elixir-ls-0.15.0/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)
	at processMessageQueue (/Users/norbert.melzer/.vscode/extensions/jakebecker.elixir-ls-0.15.0/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
	at Immediate.<anonymous> (/Users/norbert.melzer/.vscode/extensions/jakebecker.elixir-ls-0.15.0/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
	at process.processImmediate (node:internal/timers:466:21)
```

NB: Only a couple of files seem to be affected, and after the first `@doc` things are usually still correct, only after the second or third things get weird.

**Comment by aj-foster** [comment]
Similar to https://github.com/phoenixframework/vscode-phoenix/issues/19, this looks like an interaction between the grammar and VS Code's built-in bracket pair colorization feature.

Specifically, [this commit](https://github.com/elixir-lsp/vscode-elixir-ls/commit/3cb15968190e32ce1b2d38d743e8266b8eae067b#diff-22786d3eee2d1273bed0f9d9b35faa08a29ed0149935bec4d05d5053f3a675d1R13) introduced `["do:", " "]` to the brackets configuration, which appears to be invalid.

**Comment by lukaszsamson** [comment]
> In the output-panes "window" log I can see the following traces

This is harmless

> Specifically, [this commit](https://github.com/elixir-lsp/vscode-elixir-ls/commit/3cb15968190e32ce1b2d38d743e8266b8eae067b#diff-22786d3eee2d1273bed0f9d9b35faa08a29ed0149935bec4d05d5053f3a675d1R13) introduced ["do:", " "] to the brackets configuration, which appears to be invalid.

I will have to revert it. My intention was to match `do:` with a whitespace next to it and create a closed pair. It seems that is not working correctly.

**Comment by aj-foster** [comment]
Regarding docstring highlighting that does not terminate, it appears to occur (for me) when a list is present in the markdown of the docstring. Removing the `-` or `*` of list items makes the markdown context end with the `"""` correctly.

**Comment by lukaszsamson** [comment]
Having brackets like this
```
"brackets": [
    ["{", "}"],
    ["[", "]"],
    ["(", ")"],
    ["<<", ">>"],
    ["do", ":"],
    ["do", "end"],
    ["fn", "end"]
  ]
```
fixes that case
<img width="392" alt="Screenshot 2023-06-21 at 08 25 37" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/1a36d925-75a2-41de-8e42-3ebe23387297">
but it makes `do` match with first `:` in the block. After looking though the docs and issues on vscode repo it's not possible to use regex nor negative matches in the bracket definition.

**Comment by DanBykov** [comment]
I have a problem with @moduledoc syntax highlighting and nested modules. If @moduledoc is in a nested module, the syntax highlighting is broken

OK:
![Screenshot 2023-06-21 at 14 52 40](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2178893/10fbd28e-17df-4860-bb39-634239eb18b9)

NOT OK:
![Screenshot 2023-06-21 at 14 56 54](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2178893/520e2bd4-a66b-4606-a8bc-58a8f698af1b)

**Comment by maxguzenski** [comment]
inline IF (or WITH, etc) is broken as well.

<img width="281" alt="Captura de Tela 2023-06-21 às 18 04 21" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/6819/465e352e-c00f-4dad-b5a8-f2b56349696d">

**Comment by lukaszsamson** [comment]
I had to remove markdown highlighting in heredocs. It interfered with elixir grammar and I couldn't find a workaround.
I believe all the issues are now fixed.
