### ISSUE TITLE
Syntax highlighting is broken by `-` in the @doc section

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-lsp/vscode-elixir-ls#346]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1][jit]
Elixir 1.14.3 (compiled with Erlang/OTP 25)

* VSCode ElixirLS version: 0.15.0
* Operating System Version: darwin 21.6.0

### Issue Description

If there is a `-` used in the `@doc` section highlighting breaks and threats everything after that as a comment, see screenshots:
<img width="699" alt="Screenshot 2023-06-22 at 12 09 21" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1877644/259a5248-dbea-4caa-a58f-a822b0fec2fd">
<img width="693" alt="Screenshot 2023-06-22 at 12 09 32" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1877644/c9a2f8be-4a08-4c0e-96ba-09b56b5be96f">

**Comment by lukaszsamson** [comment]
Already reported in https://github.com/elixir-lsp/vscode-elixir-ls/issues/344 and reverted in https://github.com/elixir-lsp/vscode-elixir-ls/commit/3e5c623a16305d86658b396e03299b74531b2f58. Please update to 0.15.1

**Comment by AndrewDryga** [comment]
Thank you ❤️
