### ISSUE TITLE
can not run single test from launch.json

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [elixir-lsp/vscode-elixir-ls#349]
### Environment

Most of this can be filled out by running the VSCode command "Elixir: Copy ElixirLS Debug Info". You can run the command by opening the Command Palette in VSCode (by default bound to Ctrl+Shift+P or Cmd+Shift+P on Mac), typing search terms like "elixir copy debug" until the command appears at the top of the list of results, and then hitting Enter. The info will be copied to the clipboard so you can paste it here.

- Elixir & Erlang versions (elixir --version):
- VSCode ElixirLS version:
- Operating System Version:
```sh
Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.114-2-MANJARO
```

elixir-ls version
```sh
JakeBecker.elixir-ls 0.15.1
```

### steps to reproduce

create a new project
```sh
mix new demo
```
create a new test file, such as aaa_test.exs

launch.json
```json
{
  "configurations": [
    {
      "type": "mix_task",
      "name": "my_test",
      "request": "launch",
      "task": "test",
      "taskArgs": ["--trace"],
      "startApps": true,
      "env": {
        // "ELS_ELIXIR_OPTS": "--name iex-dbg@127.0.0.1 --cookie 123456"
      },
      "projectDir": "${workspaceRoot}",
      "excludeModules": [":demo_nif", "SlowModule"],
      "requireFiles": [
        "test/test_helper.exs",
        // single file to test
        "test/demo_test.exs"
      ]
    }
  ]
}
```

test/aaa_test.exs
```elixir
defmodule AaaTest do
  use ExUnit.Case
  doctest Aaa

  test "Aaa" do
    assert Aaa.demo() != :world
  end
end
```

test/demo_test.exs
```elixir
defmodule DemoTest do
  use ExUnit.Case
  doctest Demo

  test "demo" do
    assert Demo.demo() != :world
  end
end
```

when i run my_test through debug menu
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/7458713/911bebaa-075b-4149-965e-296092074ba3)

both two tests run
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/7458713/94d13304-bbb8-4e33-97d5-413c0f0febe0)

is there any way to run single test through debug menu?

**Comment by lukaszsamson** [comment]
Use Test Explorer https://code.visualstudio.com/updates/v1_59#_testing-apis or modify your launch.json accordingly (e.g. `"taskArgs": ["--trace", "tests/my_test.exs:123"],

**Comment by ziyouchutuwenwu** [comment]
it works, thank you very much!
