### ISSUE TITLE
<< >> Pairing With BitWise <<< >>> Left And Right Shifts

### ISSUE THREAD

**Issue by David-Bagby** [elixir-lsp/vscode-elixir-ls#353]
BitWise uses <<< and >>> for left and right shifts:

@spi_122_en 1 <<< 0
@spi_100_en 1 <<< 1
@spi_ref_en 1 <<< 2
@spi_dac_en 1 <<< 3
@spi_lo_en 1 <<< 4

The latest release of ElixirLS v0.15.3 incorrectly detects the first two < characters above thinking it is part of a binary bitstring <<>> opening and closing pair. This throws all the pairing out of sync in terms of color highlighting.

![PairingError](https://github.com/elixir-lsp/vscode-elixir-ls/assets/77463615/ad72ceab-08ec-4150-a169-54d15eec1a35)

**Comment by lukaszsamson** [comment]
It is correctly detected as operator but bracket pairing takes over. Unfortunately VSCode API does not allow to use regex or negative cases in brackets configuration. This is a similar problem to https://github.com/elixir-lsp/vscode-elixir-ls/issues/46

<img width="614" alt="Screenshot 2023-08-16 at 07 41 05" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/f252c58e-215a-4ced-b0cb-fb1eea78741d">
<img width="622" alt="Screenshot 2023-08-16 at 07 41 51" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/e52fb7cf-a021-48bc-9b00-62a4f522d182">
