### ISSUE TITLE
Command + click to navigate to modules is broken 

### ISSUE THREAD

**Issue by mcat115** [elixir-lsp/vscode-elixir-ls#361]
The functionality to command + click to navigate to modules (like you can in IntelliJ) has stopped working for me. It used to work with this extension, but not anymore :(  Both of the provided troubleshooting ideas did not help. 

Version info:

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

* VSCode ElixirLS version: 0.15.3
* Operating System Version: darwin 22.5.0

**Comment by lukaszsamson** [comment]
I cannot reproduce this.
Please attach relevant logs from the output tab and vscode developer tools or a repository that reproduces this problem.

**Comment by mcat115** [comment]
I checked with my coworker, he is experiencing the same problem. I cannot share the repo because it is a private one for our company. I'm not sure what logs to provide

**Comment by lukaszsamson** [comment]
Please create a minimal repo that reproduces the problem and/or attach extension logs from vscode output tab and vscode developer tools. Otherwise I’m not able to help

**Comment by mcat115** [comment]
It's happening with other Elixir repos too, but I can't share them, as they all belong to my company. But I don't think it has to do with any specific repository. I'm not too invested in this so no worries, I don't want to take up your time, just wanted to report what I discovered. I found a new elixir VSCode extension where this desired behavior is functional for me, so I'm all good :)
