### ISSUE TITLE
elixir: Permission Denied

### ISSUE THREAD

**Issue by krainboltgreene** [elixir-lsp/vscode-elixir-ls#362]
For some reason the launch.sh script doesn't have permission to run `elixir`. Currently I'm using codespaces, which is built from a dockerfile I wrote, the `elixir` binary comes from the `deb` install. It has `root:root` permission, but even setting all of `bin` to `vscode:vscode` I still get permission denied.

- Elixir & Erlang versions (elixir --version): 1.15
- VSCode ElixirLS version: v0.15.3
- Operating System Version: Linux 247be2bbe20c 5.15.0-1042-azure #49-Ubuntu SMP Tue Jul 11 17:28:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux Ubuntu 20.04.6 LTS

### Troubleshooting

- [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [X] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

### Crash report template

```
[Trace - 3:23:04 PM] Sending request 'initialize - (0)'.
Running /home/vscode/.vscode-remote/extensions/jakebecker.elixir-ls-0.15.3/elixir-ls-release/launch.sh
Looking for ASDF install in /home/vscode/.asdf/asdf.sh
/home/vscode/.vscode-remote/extensions/jakebecker.elixir-ls-0.15.3/elixir-ls-release/launch.sh: 83: elixir: Permission denied
```

![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/334809/0436d1f5-c8c6-4cc2-a2c7-e31069773a34)

**Comment by lukaszsamson** [comment]
I don’t think this is a problem with the extension. Please use elixir forum for support and reserve issue tracker for issues.

**Comment by krainboltgreene** [comment]
For some reason I thought I found the `launch.sh` in *this* repository, that said I think the issue is a little bit in the middle here. I'll open a ticket on the elixir-ls repository.
