### ISSUE TITLE
dialyzerEnabled flag config is ignored after ElixirLS is restarted

### ISSUE THREAD

**Issue by sasa1977** [elixir-lsp/vscode-elixir-ls#366]
### Is this the right repo?

I think so, since the issue is about a vscode config being ignored. But I might be wrong.

### Environment

* Elixir & Erlang versions (elixir --version):
    Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]
    Elixir 1.15.4 (compiled with Erlang/OTP 26)
* VSCode ElixirLS version: 0.15.3
* Operating System Version: linux 6.2.0-10018-tuxedo

### Troubleshooting

- [ ] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [ ] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

### Current behaviour

I have `"elixirLS.dialyzerEnabled": false` in vscode settings. When I start vscode, the dialyzer step is correctly skipped. However, if I restart the language server (using the "Restart language server" command), the flag is ignored, and dialyzer is running on every compilation. The dialyzer warnings are now present in the problems tab.

### Expected behaviour

After restart, the language server should honor the `elixirLS.dialyzerEnabled` config and skip the dialyzer step.

**Comment by michallepicki** [comment]
I am affected by this issue whenever the language server encounters an error and crashes (and is automatically restarted).

**Comment by lukaszsamson** [comment]
The original issue is fixed an now on restart the server will call `workspace/configuration` to get configuration. There is still a bug in VSCode - after restart the server no longer receives notifications about configuration changes https://github.com/elixir-lsp/vscode-elixir-ls/issues/368

**Comment by lukaszsamson** [comment]
BTW this is a recent breaking change in VSCode and it affects other language servers (e.g. https://github.com/haskell/vscode-haskell/issues/920)
