### ISSUE TITLE
Moving people over to the new extension

### ISSUE THREAD

**Issue by alanvardy** [elixir-lsp/vscode-elixir-ls#37]
Thank you very much for the efforts! This tool improves my life greatly.

One thing I am wondering is whether it would be a good idea to start redirecting people who post on https://github.com/JakeBecker/vscode-elixir-ls over here. The current install count for VS Code is just under 73k whereas this most excellent fork is still under 4k.

Would it be valuable to you if I keep an eye on said repo and respond to new messages with a note directing them over here? I am thinking of something like the below:

-----------

Hello!

I am not a maintainer of this project but would like to let you know that this repository has been inactive since May 2019. There is a fork that is being actively developed by community members, and I recommend you switch over!

The GitHub repository is here: 
https://github.com/elixir-lsp/vscode-elixir-ls

And the Visual Studio Code extension is here: 
https://marketplace.visualstudio.com/items?itemName=elixir-lsp.elixir-ls

If you are having any issues or would like to open any pull requests, please try the new extension or clone the new repository first. You may find that the problem is already resolved :slightly_smiling_face: 

Thank you and happy Elixiring.

-----------

Would this be helpful? Any edits?

**Comment by arijoon** [comment]
This would be a very useful effort to even comment on all new PR's on the dormant project. I spent the past day manually update ElixirSense and some other various aspects of the old repo on my own fork only to just find this project now.

**Comment by axelson** [comment]
I agree that this is helpful, thanks for taking the lead on this. I think that wording is fine. Closing the issue but feel free to keep discussing.
