### ISSUE TITLE
ElixirLS on Windows seems to silently not work

### ISSUE THREAD

**Issue by EricR86** [elixir-lsp/vscode-elixir-ls#376]
Hello,

I believe I've gone through most of the troubleshooting on: https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls

I've set the output of the language server to verbose and while there were a number of warnings, there were no errors. The tail end of the log seems to be the only the somewhat relevant portion:
```
warning: :dialyzer_plt.from_file/1 is undefined or private
Invalid call found at 2 locations:
  lib/language_server/dialyzer/manifest.ex:132: ElixirLS.LanguageServer.Dialyzer.Manifest.load_elixir_plt/0
  lib/language_server/dialyzer/manifest.ex:185: ElixirLS.LanguageServer.Dialyzer.Manifest.build_elixir_plt/0

Generated language_server app
Install complete
```

Notably there was no `.elixir_ls` generated which seems to be indicated from the troubleshooting section to be cleared in case of error.

Here's the versioning information as reported by ElixirLS:
```
* Elixir & Erlang versions (elixir --version): Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 26)

* VSCode ElixirLS version: 0.16.0
* Operating System Version: win32 10.0.19045
```

Any tips or help would be really appreciated. Thanks!

**Comment by lukaszsamson** [comment]
Are you runnig OTP 26.1? 26.0 has critical bug on windows.
Please post a full log from output when you open an example mix project
