### ISSUE TITLE
"There is no formatter for 'elixir' files installed"

### ISSUE THREAD

**Issue by gunnars04** [elixir-lsp/vscode-elixir-ls#381]
### Environment
Elixir 1.15.6
Phoenix 1.7.2

### Current behavior

Formating not working in VSCode. 

![image](https://github.com/elixir-lsp/elixir-ls/assets/10080542/5c6cac23-d3fd-458c-ae81-3c8f21879404)
![image](https://github.com/elixir-lsp/elixir-ls/assets/10080542/24ccfe7b-e22d-4fb4-bff7-98f69da6ba1d)

**Comment by gunnars04** [comment]
I'm in windows10.
%APPDATA%\Code\User\settings.json has:

```
{
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "files.autoSave": "afterDelay",
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": ".ex",
                "cmd": "mix format"
            }
        ]
    }
}
```

I don't have any workspace settings.json

**Comment by lukaszsamson** [comment]
Sorry, I cannot reproduce that on Windows.
I tried on a fresh install
![Zrzut ekranu 2023-10-08 165849](https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/7319fb55-1532-4e59-adf4-16634bfdf8d2)
![Zrzut ekranu 2023-10-08 170046](https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/208272f9-c970-49a8-81d3-aae7ef0c4702)
![Zrzut ekranu 2023-10-08 170103](https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/ad03866b-802f-405a-98ac-dba8b76feaa5)
and after selecting the default formatter everything works as expected.
Please verify the extension is working. Please post logs from VSCode developer tools and ElixirLS output panel.

**Comment by gunnars04** [comment]
I did an uninstall + clean unstinall:
Windows - Delete %APPDATA%\Code and %USERPROFILE%\.vscode.
https://code.visualstudio.com/docs/setup/uninstall

Opened my project + downloaded only this plugin:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/10080542/439cd5d2-049a-4834-99a1-99abf53fc432)

I still get the popup:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/10080542/d5620b85-fcae-46fe-9fa4-00e9618b1f22)

In VSCode:
File -> Preferences -> Settings + clicked the "settings.json" file in the top right corner which is empty:
{
}

I updated it to:
{
    "[elixir]": {
        "editor.defaultFormatter": "JakeBecker.elixir-ls"
      },
}

I still get the same popup when I do ctrl + option + F

**Comment by lukaszsamson** [comment]
Please provide logs from [VSCode Developer Tools logs](https://github.com/elixir-lsp/vscode-elixir-ls#check-the-developer-tools) and [ElixirLS output tab logs](https://github.com/elixir-lsp/vscode-elixir-ls#check-elixirls-output) @gunnars04

**Comment by gunnars04** [comment]
With only this in settings.json>
{
    "[elixir]": {
        "editor.defaultFormatter": "JakeBecker.elixir-ls"
      }
}

Still install popup:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/10080542/242a7108-3683-46f9-8398-efaff36e8d54)

**Comment by lukaszsamson** [comment]
OK, it looks like the extension is activated but looking at the output tab it doesn't seem to be running. You should be seeing something like this in the output tab.
<img width="875" alt="Screenshot 2023-10-09 at 16 38 43" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/6db3634e-6a15-4005-a942-e244defe1e64">

You didn't fill the issue template. Are you running a supported OTP version?

**Comment by gunnars04** [comment]
I think I'm using the latest:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/10080542/e386a18c-328f-41f9-a028-1d57efc97328)

**Comment by lukaszsamson** [comment]
OTP 26.0 has critical bugs on windows. It's mentioned in the readme https://github.com/elixir-lsp/elixir-ls#support-matrix. Please update to 26.1+. If you filled the issue template and provided logs as asked we wouldn't have been wasting time.

**Comment by gunnars04** [comment]
@lukaszsamson how do I do that?
I installed the latest Elixir:
https://github.com/elixir-lang/elixir/releases

I'm using the latest Elixir and Phoenix:
Elixir 1.15.6
Phoenix 1.7.2

**Comment by gunnars04** [comment]
@lukaszsamson never mind, I found it:
https://www.erlang.org/downloads

**Comment by gunnars04** [comment]
@lukaszsamson works now (after dl'in Erlang/OTP 26.1.1 in the link above)! 

Sorry for that and thanks a lot!
