### ISSUE TITLE
Syntax highlighting changes in 0.17.0

### ISSUE THREAD

**Issue by MvanDiemen** [elixir-lsp/vscode-elixir-ls#382]
### Is this the right repo?

Since it's syntax related I believe so

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]
Elixir 1.14.1 (compiled with Erlang/OTP 23)
* VSCode ElixirLS version: 0.17.0
* Operating System Version: linux 6.5.6-arch2-1

### Issue

In version 0.17.0 there have been some changes to the syntax highlighting. This has changed the syntax highlighting quite a bit.

Example of 0.16.0
![2023-10-11_09-27](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/a2d61122-52ce-4de3-bd4d-8b74617e510e)

Same code in 0.17.0
![image (1)](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/940466cc-d5a1-4c28-a43e-3b665c218615)

I'm using the `two-firewatch` theme for reference. I have reverted to 0.16.0 for the time being but I hope this example is clear enough :)

**Comment by lukaszsamson** [comment]
Here's a screenshot using Dark Modern theme
<img width="559" alt="Screenshot 2023-10-11 at 09 54 14" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/bcbeadd5-8ae0-4ee9-b000-eb8c04cfb39b">

Please attach screenshots using [VSCode scope inspector](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector) on the syntax elements you believe are wrongly highlighted.

**Comment by dkln** [comment]
I use Monokai Pro.

0.16:

![Screenshot 2023-10-11 at 10 10 31](https://github.com/elixir-lsp/vscode-elixir-ls/assets/59295/6e7ae608-2ef0-4273-a7ef-7031681be98b)

0.17:

![Screenshot 2023-10-11 at 10 11 43](https://github.com/elixir-lsp/vscode-elixir-ls/assets/59295/2c94d4fa-1589-4792-b3ea-cceeac349c20)

Inspector:

![Screenshot 2023-10-11 at 10 11 26](https://github.com/elixir-lsp/vscode-elixir-ls/assets/59295/72805549-efb4-4254-9508-55043fcaaaaa)

Hope this helps 👍

**Comment by lukaszsamson** [comment]
@dkln Nothing wrong in your inspector screenshot, elixir variable matched as `variable.other.readwrite.elixir`

**Comment by dkln** [comment]
But as you can see this seems to be different:

0.16:

![Screenshot 2023-10-11 at 10 30 01](https://github.com/elixir-lsp/vscode-elixir-ls/assets/59295/38fcf482-b15d-407c-878e-4e6118e0fe0d)

0.17:

![Screenshot 2023-10-11 at 10 30 25](https://github.com/elixir-lsp/vscode-elixir-ls/assets/59295/a2b685be-2ba1-4682-ac10-98e8781f6232)

**Comment by lukaszsamson** [comment]
I may need to revert some changes from https://github.com/elixir-lsp/vscode-elixir-ls/commit/6621564bbf1f16bb3032893df01d55eba709f201
but the problem with that function call matching rules was they broke syntax matching inside function arguments.

Any ideas on what textmate scope should variables use? `source.elixir` from 0.16 was definitively wrong

**Comment by MvanDiemen** [comment]
## variable
0.16.0
![2023-10-11_10-17_1](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/31917f80-c528-4ef8-88f9-8ecbe4c43b44)
0.17.0
![2023-10-11_10-15](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/928ec887-ebcb-4f63-a01a-0d11dcfb8706)

## Function
0.16.0
![2023-10-11_10-16](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/d36196be-b0fb-43f8-8c92-7fae00e0e20a)
0.17.0
![2023-10-11_10-25](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/5314a83c-ac33-4cd0-9d01-750ded321c75)

The Github Dark theme is flagging the function as a variable 
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/079ab14b-e285-43f8-aa5d-9f2734dfba96)

**Comment by MvanDiemen** [comment]
I think the comment should not have a first textmate scope as `punctuation.definition.variable.elixir`, what would happen if it only focuses on `variable.other.readwrite.elixir`? 

For the function, should that be `entity.name.function-call.elixir`, `entity.name.function`, `source.elixir`?
I'm not too familiar with VS code highlighting. I'd love to help out and test things but I'd have to figure out how to get that to work.

**Comment by lukaszsamson** [comment]
> I'd love to help out and test things but I'd have to figure out how to get that to work.

If you'd like to contribute please head to https://github.com/elixir-lsp/vscode-elixir-ls#contributing
Syntax definition is in https://github.com/elixir-lsp/vscode-elixir-ls/blob/master/syntaxes/elixir.json

**Comment by navinpeiris** [comment]
In case it helps, experiencing the same with "One Dark Pro":

0.16:

<img width="563" alt="0 16" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/410939/0a9f9392-bc3d-4222-9560-1fe4614d7293">


0.17:

<img width="562" alt="0 17" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/410939/57961d2b-6a7e-4e12-9899-6f169453437a">


0.17 inspector:

<img width="620" alt="0 17 inspector" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/410939/3fffdb8e-040c-49b9-b2bd-4a0a4de3e18e">

**Comment by MvanDiemen** [comment]
https://github.com/elixir-lsp/vscode-elixir-ls/blob/master/syntaxes/elixir.json#L2340-L2347 this seems to be matching functions and variables at once.

I've changed to Nords color scheme to get better color differentiation.

On the current `punctuation.definition.variable.elixir`
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/050fcb38-df76-4a3a-95f0-3d2da7b6e263)

By moving the match to `variable.other.readwrite`
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/1194d666-45bf-4f87-8105-a12a550f677f)

And if it's moved to match to `entity.name.function`
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/513828fd-53b4-4e04-a0c5-f433c85c4def)

**Comment by lukaszsamson** [comment]
> In case it helps, experiencing the same with "One Dark Pro"

Can't decide which one looks better TBH with that theme

**Comment by MvanDiemen** [comment]
I'm not understanding textmate enough to figure out how to do those matches correctly.

**Comment by lukaszsamson** [comment]
> These syntax color changes are madness.

Comments like that are not productive.

**Comment by MvanDiemen** [comment]
@jbosse We are trying to help out, there's a reason we are all using this extension as it works very well :heart: . Indeed I have reverted to 0.16.0 too for the time being.

**Comment by jbosse** [comment]
> > These syntax color changes are madness.
> 
> Comments like that are not productive.

My apologies.

**Comment by dkln** [comment]
@lukaszsamson cool! Will try it out asap

**Comment by aj-foster** [comment]
Posting this for two purposes:

1. In case anyone doesn't want to revert, but wants the "old" behavior,
2. To possibly help diagnose the changes.

The following, placed in a user's settings, effectively "reverts" the syntax highlighting change. The name of the theme, and its corresponding color, would need to change depending on which theme you use.

```json
  "editor.tokenColorCustomizations": {
    "[One Dark Pro*]": {
      "textMateRules": [
        {
          "scope": [
            "variable.other.readwrite.elixir punctuation.definition.variable.elixir"
          ],
          "settings": {
            "foreground": "#ABB2BF"
          }
        }
      ]
    }
  },
```

I'm using this setting simply because I prefer it. In reality, 0.17 seems to more closely align with the syntax highlighting in a typical JavaScript or TypeScript file. So while it is different, it may be more correct.

**Comment by lukaszsamson** [comment]
> 0.17 seems to more closely align with the syntax highlighting in a typical JavaScript or TypeScript file. So while it is different, it may be more correct

Unfortunately there is no standard way of implementing textmate grammars. Some quidelines can be found in https://www.sublimetext.com/docs/scope_naming.html and https://macromates.com/manual/en/language_grammars.
Previous rules were quite broken. An invalid function call match rule made almost everything was matched as `source.elixir`. New rules correctly match variables as `variable.other.readwrite.elixir`. What's definitely not correct is that they also match function calls as variables (and fix for that is already on master).

**Comment by MvanDiemen** [comment]
On master functions are now highlighted indeed, but variables are still noted as punctuation.
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/dbf185b9-7ee8-4bcc-a860-ba55876aa725)

**Comment by lukaszsamson** [comment]
> variables are still noted as punctuation

OK I changed that on master. Funny thing it was like that all the time but due to broken rules elsewhere variables wasn't matched at all.

After spending some time trying to fix the grammar I'm more inclined to throwing it all away and starting from scratch. There are many rules that never match, some thing are matched in different ways, do-end scopes are not respected.

**Comment by MvanDiemen** [comment]
With the new change on master it detects any variable as `parameter.variable.function.elixir` which gets labeled very differently in different color schemes. 

Atom One Dark:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/75712cf9-cf52-4467-9f5f-3b53ef764ae3)

Gruvbox (dark hard):
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/27ee48af-9cc0-4a0a-8557-3f841ccd3655)

Monokai:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/2a3b079a-75ea-48dd-8498-9344dcca2a9c)


It feels more like variables now but very dependable on the color scheme.

But the 0.16.0 notation (even if it was wrong because it doesn't match) still keeps a cleaner look for the variables.

Atom One Dark 0.16.0:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/39218b0e-1cd6-4d74-a4ad-e66c30767554)

Gruvbox Dark Hard 0.16.0:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/db94bc98-0612-444d-9cf2-852ba338f6d4)

Monokai 0.16.0:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/eb5e650a-d28b-4fc1-aabc-047d9983bf59)

**Comment by MvanDiemen** [comment]
> After spending some time trying to fix the grammar I'm more inclined to throwing it all away and starting from scratch. There are many rules that never match, some thing are matched in different ways, do-end scopes are not respected.

That's also an option :upside_down_face: I tried to check some other language servers and others did not have that extensive syntax matching, it's worth a shot to see what happens.
[Dart](https://github.com/Dart-Code/Dart-Code/blob/master/syntaxes/dart.json) was the largest file I could find but is nowhere near the size of Elixirs json. Then again Elixir is something special

**Comment by lukaszsamson** [comment]
@MvanDiemen did you try the latest master? I removed `parameter.variable.function.elixir` all together in a2e203ed56bed4087fa03c063f0dc8c44a8d3299

**Comment by MvanDiemen** [comment]
Yeah I tried the latest master, that's what the screenshots in https://github.com/elixir-lsp/vscode-elixir-ls/issues/382#issuecomment-1759221561 are from.

**Comment by MvanDiemen** [comment]
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/cf4a6a10-9bca-4eda-ab61-765d1e75e6b7)

Seems it indeed did not build correctly before adding the local extension after the last change. Right now they are matched as readwrite variables just like module attributes are

**Comment by lukaszsamson** [comment]
> That's also an option 🙃 I tried to check some other language servers and others did not have that extensive syntax matching, it's worth a shot to see what happens.

The current grammar comes from original atom extension and is a collection of hacks on top of hacks. It definitively could be build up from primitives.

> [Dart](https://github.com/Dart-Code/Dart-Code/blob/master/syntaxes/dart.json) was the largest file I could find but is nowhere near the size of Elixirs json

Markdown grammar is so big it needs to be compiled https://github.com/microsoft/vscode-markdown-tm-grammar

**Comment by lukaszsamson** [comment]
> Right now they are matched as readwrite variables, with colors like module attributes have

I made module attributes `variable.other.constant.elixir` and in Dark+ they get different color

<img width="579" alt="Screenshot 2023-10-12 at 11 23 51" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/5c6852ad-0882-480f-b327-2b5536a3443d">

**Comment by MvanDiemen** [comment]
There are quite some languages where indeed the colors are different from the module attributes and in all languages it's the same as parameters. The differences with 0.16.0 are still very noticeable.

#### Two firewatch
master:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/8d1fb85a-6549-47f3-a5b8-fc06f0e550fe)

0.16.0: 
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/3d961d1b-cfd9-4c13-a73e-f0e2e72c134a)


#### Monokai
master:
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/7d25b735-4a00-4e75-bd0f-5ce4c02c8aa7)

0.16.0: 
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/5143591e-ef81-43ea-aca4-c96ae9a53ad4)

#### Dark+
master: 
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/6871d590-2bb4-4354-886d-a8f047f8efec)


0.16.0: 
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/21cef9f9-9dfd-4bb5-b110-fa5560ae2298)

**Comment by MvanDiemen** [comment]
This also translates to EEx/HEEx

master (Dark+):
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/c8b6f25e-d1f8-48ba-9a7b-26c1ab2f3380)

0.16.0 (Dark+):
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/2279070/571f9834-ae48-47d5-be97-73958d7abfc8)

**Comment by jbosse** [comment]
@lukaszsamson thank you for your efforts and quick response. 17.1 is a great improvement. 

17.1
<img width="588" alt="image" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/119121/87868e09-9077-499b-9b32-9913f889de84">

I do like the new diferentiation between modules in 17.1 but I think I also prefer the differentiation between function names and arguments in 16. Perhaps it is better now and my brain needs time to adjust.

16
<img width="459" alt="image" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/119121/2855db87-77c6-4961-8873-55c1e0641d1f">

17.1
<img width="508" alt="image" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/119121/db19a68c-be47-44ed-86e3-0552e265c9f8">

Again, my apologies for my original outburst.

**Comment by lukaszsamson** [comment]
> I think I also prefer the differentiation between function names and arguments in 16. Perhaps it is better now and my brain needs time to adjust.

There is distinction in textmate scopes. Maybe theme customisation could help https://github.com/elixir-lsp/vscode-elixir-ls/issues/382#issuecomment-1758112397
- function calls
```
entity.name.function.call.elixir
source.elixir
```
- function definitions:
```
entity.name.function.elixir
meta.function.definition.elixir
source.elixir
```
- variables
```
variable.other.readwrite.elixir
source.elixir
```
- function arguments in definition
```
variable.other.readwrite.elixir
meta.function.definition.elixir
source.elixir
```
In Dark+/Dark Modern the distinction is clearly visible
<img width="611" alt="Screenshot 2023-10-14 at 18 52 14" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/b7282fda-3143-4e7e-8607-b3413f4ad82b">

> Again, my apologies for my original outburst.

No need to worry about it. Let's focus on making good OSS

**Comment by MvanDiemen** [comment]
Yeah it's been a nice change. You are right, some color schemes might need some customization but that's possible now with all the right scopes.

Thanks for helping @lukaszsamson, happy with the 0.17.1 changes. Now it's time to figure out how to customize my color scheme :thinking:

**Comment by dkln** [comment]
@lukaszsamson the latest version seems to fix the issues with the colorschemes I am using 🥳 

![Screenshot 2023-10-16 at 09 59 21](https://github.com/elixir-lsp/vscode-elixir-ls/assets/59295/96e2a749-b59b-4741-a877-db6bd18c3b8a)

**Comment by david-clark-1043** [comment]
Chiming in with [Dracula Theme](https://github.com/dracula/visual-studio-code). I kind of liked modules being different than in the `defmodule` definition, but I totally see how the change to consistency would make sense. Seems fine with the customization option commented above.

However, I am now seeing`.` accessed keys on a map as the same as function calls. I guess they always were the same, but just not registering as functions. Thinking about the regex needed to differentiate `.` access and `.` function, I'm really not sure how it would even be possible to be honest.
 0.17.1
![Screenshot 2023-10-16 at 7 53 38 PM](https://github.com/elixir-lsp/vscode-elixir-ls/assets/74992669/3068348d-788d-4c60-9f8e-6b9d4b353c5d)

Example where `map.key` is not a function, but I don't see an obvious way to differentiate.
0.17.1
![Screenshot 2023-10-16 at 8 38 19 PM](https://github.com/elixir-lsp/vscode-elixir-ls/assets/74992669/6b51f191-bee2-4fd0-846f-df9194e2da82)

0.16.0 / 0.17.0
![Screenshot 2023-10-16 at 8 47 05 PM](https://github.com/elixir-lsp/vscode-elixir-ls/assets/74992669/724efeb1-0762-4ee2-9b7b-bbca2511e3e0)

TS/JS in VSCode seems to be able to do this, though I have no idea how and looks complicated:
![Screenshot 2023-10-16 at 8 55 46 PM](https://github.com/elixir-lsp/vscode-elixir-ls/assets/74992669/738b4770-2d84-4938-9797-8e06354afbe4)
![Screenshot 2023-10-16 at 8 56 01 PM](https://github.com/elixir-lsp/vscode-elixir-ls/assets/74992669/03dec514-924a-45d9-b42a-c567cb37a207)


I'm sorry if this is just impossible! Thank you for all the hard work!

**Comment by lukaszsamson** [comment]
Access is a call in elixir. AST is the same. In JS it’s easier as all calls have parens. Moreover, JS have LSP symantic tokens support. Here I need to think on how to create a regex that would match calls without parens and not access

**Comment by MvanDiemen** [comment]
> Thinking about the regex needed to differentiate . access and . function, I'm really not sure how it would even be possible to be honest.

I've tried this too, as well as matching on parentheses at the end, as usually functions are followed with those. But to no avail. This regex stuff for textmate is way more difficult than I expected.

Considering this, I'm okay with closing this issue. The main issue has been addressed, the remaining is a change we either have to help out and provide a PR for or accept in my opinion.

**Comment by aj-foster** [comment]
Similar to my post above, the following settings can effectively revert some of the changes for folks like me who (playfully) don't like change 😀 

```json
  "editor.tokenColorCustomizations": {
    "[One Dark Pro*]": {
      "textMateRules": [
        {
          "scope": [
            "variable.other.readwrite.elixir",
            "entity.name.function.call.elixir",
          ],
          "settings": {
            "foreground": "#ABB2BF"
          }
        },
        {
          "scope": [
            "variable.other.constant.elixir",
          ],
          "settings": {
            "foreground": "#E06C75"
          }
        }
      ]
    }
  },
```

You'll need to change `[One Dark Pro*]` to match the name of your theme, and the hex color codes to match the colors used by your theme.

**Comment by lukaszsamson** [comment]
I managed to resolve the issue with access matching as function call in https://github.com/elixir-lsp/vscode-elixir-ls/commit/9667b1a796e3001de6fe86dacb71e24df107cd6d
