### ISSUE TITLE
ElixirLS v0.17.1 in VSCode significantly changes token scopes, affecting syntax highlighting

### ISSUE THREAD

**Issue by bceskavich** [elixir-lsp/vscode-elixir-ls#385]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir v1.14.5, Erlang/OTP 25
* Elixir Language Server version: v0.17.1
* Operating system: macOS Ventura 13.2.1
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: ElixirLS v0.17.1

### Current behavior

The latest release of ElixirLS for VSCode seems to remove a number of token scopes for Elixir, which in turn significantly changes the appearance of multiple syntax highlighting themes. The example below shows the following cases:

- Differentiation between module definition + module alias usage has disappeared
- Identification of module attributes as distinct entities has disappeared

I am the author of the [Dracula At Night](https://marketplace.visualstudio.com/items?itemName=bceskavich.theme-dracula-at-night) VSCode theme, and the examples below use this theme. However, I've verified that this issue affects other popular themes as well (e.g. [Cobalt2](https://marketplace.visualstudio.com/items?itemName=wesbos.theme-cobalt2)).

| <= v0.17.0 | v0.17.1 |
| - | - |
| <img width="707" alt="image" src="https://github.com/elixir-lsp/elixir-ls/assets/5049830/bc908603-ee9a-4875-9bef-7b90da05a7c0"> | <img width="707" alt="image" src="https://github.com/elixir-lsp/elixir-ls/assets/5049830/b926fcd2-64fe-4d7b-8a53-f097779b27d1"> |

### Expected behavior

Consistent token scopes and syntax highlighting across versions.

**Comment by bceskavich** [comment]
> Grammar changes was mentioned in v0.17.0 and v0.17.1 release notes

Ah, I'm sorry @lukaszsamson, I missed this and was looking in the wrong repo.

> The question now is if the current rules allow you to make your theme work as you wish or do you need some changes? Which areas could be improved?

I haven't yet had time to update my theme package to work with the latest rules. I will let you know if I run into any challenges when I do so.

> I now know that more cere is needed here. I'm afraid there will be more changes in the future. Elixir is notoriously difficult to parse with textmate grammars and LSP symantic tokens seem to be the solution

Noted, and understood!

**Comment by jbosse** [comment]
> In addition, I would advocate for considering significant changes in the token identification grammar as a breaking change in the future. There are thousands of users of this VSCode plugin who are suddenly experiencing a drastic change in appearance of Elixir code across multiple themes as a result of this update. And for those who aren't theme maintainers they may be searching in confusion to understand why this happened (i.e. is this the theme they use? is it their VSCode version? is it the LS plugin?)

FWIW I would place myself in this user category. I was very confused as to what happened to my syntax highlighting. I honestly don't think there is anything @lukaszsamson could have done to avoid my confusion. My extensions auto-update and I rarely look are release notes. Even a note like "updated text mate grammar" would have gone over my head.

There are many developers like me who I would categorize "Line of Business" developers that don't really have a mental model on how our IDE does the magical things it does and don't know where to begin investigating when something odd happens.

On the bright side, this whole thing has taught me about how my editor themes work and how I can tweak them to make them even more to my taste.

**Comment by seanhuggins1** [comment]
Yeah - folks at my work started noticing changes in our theme this week and we traced it to changes in this extension. Installing an older version is our current workaround. It's really wild how much differences in your theme affect readability!

**Comment by lukaszsamson** [comment]
Closing this for now. Please open new issues if you have concrete proposals.
BTW I started work on semantic token provider. Probably it won't be ready for v0.18
