### ISSUE TITLE
vsCode prompts : Restarting server failedElixirLS and ElixirLS - blockscout client: couldn't create connection to server.

### ISSUE THREAD

**Issue by formingform** [elixir-lsp/vscode-elixir-ls#392]
### Environment
- Elixir & Erlang versions (elixir --version): 1.14.4 (compiled with Erlang/OTP 25)
- VSCode ElixirLS version: 
  Version: 1.84.2
  Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
  Date: 2023-11-09T10:50:47.800Z
  Electron: 25.9.2
  ElectronBuildId: 24603566
  Chromium: 114.0.5735.289
  Node.js: 18.15.0
  V8: 11.4.183.29-electron.0
  OS: Linux x64 5.15.133.1-microsoft-standard-WSL2
- Operating System Version: Ubuntu 22.04 in WINDOWS 11 WLS2

My project source code locate in d:/github.com/blockscout/blockscout on WINDOWS 11.

### Troubleshooting
Running /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/launch.sh
Preferred shell is bash, relaunching
Looking for ASDF install
ASDF not found
Looking for rtx executable
rtx not found
Installing ElixirLS release v0.17.10
Running in /mnt/d/github.com/blockscout/blockscout
* Updating elixir_ls (https://github.com/elixir-lsp/elixir-ls.git - v0.17.10)
==> language_server
Could not find Hex, which is needed to build dependency :stream_data
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
* creating /home/joey/.mix/archives/hex-2.0.6
==> mix_install
* Getting elixir_sense (https://github.com/elixir-lsp/elixir_sense.git - 16d28f78e5702678394523c6aa17486931740402)
* Getting erl2ex_vendored (https://github.com/elixir-lsp/erl2ex.git - 073ac6b9a44282e718b6050c7b27cedf9217a12a)
* Getting dialyxir_vendored (https://github.com/elixir-lsp/dialyxir.git - d50dcd7101c6ebd37b57b7ee4a7888d8cb634782)
* Getting jason_v (https://github.com/elixir-lsp/jason.git - c81537e2a5e1acacb915cf339fe400357e3c2aaa)
* Getting path_glob_vendored (https://github.com/elixir-lsp/path_glob.git - 965350dc41def7be4a70a23904195c733a2ecc84)
* Getting erlex_vendored (https://github.com/elixir-lsp/erlex.git - 82db0e82ee4896491bc26dec99f5d795f03ab9f4)
* Getting mix_task_archive_deps (https://github.com/elixir-lsp/mix_task_archive_deps.git)
Failed to fetch record for benchee from registry (using cache instead)
:timeout
Failed to fetch record for patch from registry (using cache instead)
:timeout
Failed to fetch record for nimble_parsec from registry (using cache instead)
:timeout
Resolving Hex dependencies...
Resolution completed in 0.31s
New:
  benchee 1.2.0
  deep_merge 1.0.0
  nimble_parsec 1.1.0
  patch 0.12.0
  statistex 1.0.0
  stream_data 0.6.0
* Getting stream_data (Hex package)
* Getting patch (Hex package)
* Getting benchee (Hex package)
* Getting deep_merge (Hex package)
* Getting statistex (Hex package)
* Getting nimble_parsec (Hex package)
You have added/upgraded packages you could sponsor, run `mix hex.sponsor` to learn more
==> jason_v
Compiling 10 files (.ex)
Generated jason_v app
==> nimble_parsec
Compiling 4 files (.ex)
Generated nimble_parsec app
==> path_glob_vendored
Compiling 2 files (.ex)
Compiling lib/path_glob_vendored.ex (it's taking more than 10s)
Generated path_glob_vendored app
==> mix_task_archive_deps
Compiling 5 files (.ex)
Generated mix_task_archive_deps app
==> elixir_sense
Compiling 1 file (.yrl)
Compiling 5 files (.erl)
Compiling 63 files (.ex)
Generated elixir_sense app
==> erlex_vendored
Compiling 1 file (.yrl)
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 1 file (.ex)
Generated erlex_vendored app
==> dialyxir_vendored
Compiling 66 files (.ex)
Generated dialyxir_vendored app
==> erl2ex_vendored
Compiling 22 files (.ex)
warning: Macro.to_string/2 is deprecated. Use Macro.to_string/1 instead
  lib/erl2ex/pipeline/codegen.ex:505: Erl2exVendored.Pipeline.Codegen.expr_to_string/1

Generated erl2ex_vendored app
==> elixir_ls_utils
Compiling 8 files (.ex)
Generated elixir_ls_utils app
==> elixir_ls_debugger
Compiling 13 files (.ex)
warning: Mix.ensure_application!/1 is undefined or private
  lib/debugger/cli.ex:15: ElixirLS.Debugger.CLI.main/0

Generated elixir_ls_debugger app
==> language_server
Compiling 61 files (.ex)
warning: Macro.to_string/2 is deprecated. Use Macro.to_string/1 instead
Invalid call found at 2 locations:
  lib/language_server/providers/execute_command/manipulate_pipes/ast.ex:75: ElixirLS.LanguageServer.Providers.ExecuteCommand.ManipulatePipes.AST.ast_to_string/1
  lib/language_server/providers/execute_command/manipulate_pipes/ast.ex:149: ElixirLS.LanguageServer.Providers.ExecuteCommand.ManipulatePipes.AST.interpolate/4

warning: Logger.default_formatter/1 is undefined or private
  lib/language_server/json_rpc_logger_backend.ex:184: Logger.Backends.JsonRpc.handler_config/0

warning: Code.with_diagnostics/2 is undefined or private
  lib/language_server/build.ex:595: ElixirLS.LanguageServer.Build.with_diagnostics/2

warning: :dialyzer_cplt.from_file/1 is undefined (module :dialyzer_cplt is not available or is yet to be defined)
Invalid call found at 2 locations:
  lib/language_server/dialyzer/manifest.ex:145: ElixirLS.LanguageServer.Dialyzer.Manifest.load_elixir_plt/0
  lib/language_server/dialyzer/manifest.ex:198: ElixirLS.LanguageServer.Dialyzer.Manifest.build_elixir_plt/0

Generated language_server app
Install complete
Could not find Hex, which is needed to build dependency true
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
** (Mix.Error) request timed out after 60000ms

Could not run archive.install for:

    https://repo.hex.pm/installs/1.14.0/hex-2.0.6.ez

Please download the file above to your current directory and run:

    mix archive.install ./hex-2.0.6.ez

You can download it either with your browser or via the command line.

On Unix-like operating systems (Linux, macOS):

    wget https://repo.hex.pm/installs/1.14.0/hex-2.0.6.ez

or

    curl -o hex-2.0.6.ez https://repo.hex.pm/installs/1.14.0/hex-2.0.6.ez

On Windows / PowerShell (Windows 7 or later):

    powershell -Command "Invoke-WebRequest https://repo.hex.pm/installs/1.14.0/hex-2.0.6.ez -OutFile hex-2.0.6.ez"

or

    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://repo.hex.pm/installs/1.14.0/hex-2.0.6.ez', 'hex-2.0.6.ez')"

    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/local/installer.ex:116: Mix.Local.Installer.local_install/3
    /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/installer.exs:369: anonymous fn/6 in ElixirLS.Mix.install/2
    (elixir 1.14.4) lib/file.ex:1607: File.cd!/2
    /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/installer.exs:337: ElixirLS.Mix.install/2
    /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/launch.exs:14: (file)
[Error - 9:40:43 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 9:40:43 PM] Connection to server got closed. Server will restart.
true
[Error - 9:40:43 PM] ElixirLS - blockscout client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Running /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/launch.sh
Preferred shell is bash, relaunching
Looking for ASDF install
ASDF not found
Looking for rtx executable
rtx not found
Installing ElixirLS release v0.17.10
Running in /mnt/d/github.com/blockscout/blockscout
Could not find Hex, which is needed to build dependency true
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
Mix.install failed with ** (Mix.Error) request timed out after 60000ms

Could not run archive.install for:

    https://repo.hex.pm/installs/1.14.0/hex-2.0.6.ez

Please download the file above to your current directory and run:

    mix archive.install ./hex-2.0.6.ez

You can download it either with your browser or via the command line.

On Unix-like operating systems (Linux, macOS):

    wget https://repo.hex.pm/installs/1.14.0/hex-2.0.6.ez

or

    curl -o hex-2.0.6.ez https://repo.hex.pm/installs/1.14.0/hex-2.0.6.ez

On Windows / PowerShell (Windows 7 or later):

    powershell -Command "Invoke-WebRequest https://repo.hex.pm/installs/1.14.0/hex-2.0.6.ez -OutFile hex-2.0.6.ez"

or

    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://repo.hex.pm/installs/1.14.0/hex-2.0.6.ez', 'hex-2.0.6.ez')"

    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/local/installer.ex:116: Mix.Local.Installer.local_install/3
    /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/installer.exs:369: anonymous fn/6 in ElixirLS.Mix.install/2
    (elixir 1.14.4) lib/file.ex:1607: File.cd!/2
    /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/installer.exs:337: ElixirLS.Mix.install/2
    /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/installer.exs:526: ElixirLS.Installer.install/1
    /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/installer.exs:543: ElixirLS.Installer.install_with_retry/0
    (elixir 1.14.4) src/elixir_compiler.erl:66: :elixir_compiler.dispatch/4

Retrying Mix.install with force: true
Installing ElixirLS release v0.17.10
Running in /mnt/d/github.com/blockscout/blockscout
* Getting elixir_ls (https://github.com/elixir-lsp/elixir-ls.git - v0.17.10)
==> language_server
Could not find Hex, which is needed to build dependency :stream_data
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")
** (EXIT from #PID<0.96.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.179.0>}}
        (mix 1.14.4) lib/mix/utils.ex:652: Mix.Utils.read_httpc/1
        (mix 1.14.4) lib/mix/utils.ex:579: anonymous fn/2 in Mix.Utils.read_path/2
        (elixir 1.14.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
        (elixir 1.14.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
        (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

[Error - 9:42:03 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 9:42:03 PM] Connection to server got closed. Server will restart.
true
[Error - 9:42:03 PM] ElixirLS - blockscout client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Running /home/joey/.vscode/extensions/jakebecker.elixir-ls-0.17.10/elixir-ls-release/launch.sh
Preferred shell is bash, relaunching
Looking for ASDF install
ASDF not found
Looking for rtx executable
rtx not found
Installing ElixirLS release v0.17.10
Running in /mnt/d/github.com/blockscout/blockscout
* Updating elixir_ls (https://github.com/elixir-lsp/elixir-ls.git - v0.17.10)
==> language_server
Could not find Hex, which is needed to build dependency :stream_data
Shall I install Hex? (if running non-interactively, use "mix local.hex --force")

**Comment by lukaszsamson** [comment]
The answer is ion the log you posted. You need to install hex

**Comment by formingform** [comment]
> The answer is ion the log you posted. You need to install hex

But I actually have hex installed.

I download hex-2.0.6.ez to my current directory and run:
$ mix archive.install ./hex-2.0.6.ez
and here is the ouput:
`
joey@Joey:~/download$ mix archive.install ./hex-2.0.6.ez
Found existing entry: /home/joey/.mix/archives/hex-2.0.6
Are you sure you want to replace it with "./hex-2.0.6.ez"? [Yn] Y
* creating /home/joey/.mix/archives/hex-2.0.6
`

**Comment by formingform** [comment]
> No idea what is wrong with you'r install then. Maybe it's access rights? How did you install elixir? I can see you are not using asdf nor rtx for version management. Did you try installing hex with
> 
> ```
> mix local.hex
> ```
> 
I tryed 3 ways to install Hex:
1. run cmd "mix local.hex --force"
2. run cmd: mix archive.install github hexpm/hex branch latest
3. download  ./hex-2.0.6.ez, and run cmd: mix archive.install ./hex-2.0.6.ez.

> What is the effect of running this in iex
> 
> ```
> Mix.install([:stream_data]
> ```

Sorry, I'm a newbie of elixir, I just want to setup a develop environment for now.

> 
> Are you behind a proxy? This crash from mix is suspicious

Yes, I'm behind a proxy.

> 
> ```
> ** (EXIT from #PID<0.96.0>) an exception was raised:
> ** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.179.0>}}
> (mix 1.14.4) lib/mix/utils.ex:652: Mix.Utils.read_httpc/1
> (mix 1.14.4) lib/mix/utils.ex:579: anonymous fn/2 in Mix.Utils.read_path/2
> (elixir 1.14.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
> (elixir 1.14.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
> (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
> ```
> 
> https://github.com/elixir-lang/elixir/blob/6f96693b355a9b670f2630fd8e6217b69e325c5a/lib/mix/lib/mix/utils.ex#L652C18-L652C18

**Comment by lukaszsamson** [comment]
> Sorry, I'm a newbie of elixir, I just want to setup a develop environment for now.

I'm trying to help you and you did not answer my questions.
1. Have you checked the access rights to `~/.mix`?
2. How did you install elixir? I can see you are not using asdf nor rtx for version management.
3. Can you start iex and check what happens if you run
```
Mix.install([{:stream_data, "~> 0.5"}])
```

Evidently your environment is broken if you are not able to install packages via hex. Please use [elixir](https://elixirforum.com) or [slack](https://elixir-lang.slack.com/archives/C03EPRA3B) for support. Github issues are reserved for bugs and feature requests


There are solutions if you search for your https://elixirforum.com/search?q=Could%20not%20find%20Hex%2C%20which%20is%20needed%20to%20build%20dependency, e.g. https://elixirforum.com/t/phoenix-ignoring-hex-install/16649/5 or https://elixirforum.com/t/encountering-could-not-find-hex-only-on-a-different-machine/55857/8 https://elixirforum.com/t/how-to-configure-location-for-hex-folder-file-error-could-not-make-directory-with-p/13936
There are numerous similar issues https://github.com/search?q=repo%3Aelixir-lang%2Felixir+Could+not+find+Hex%2C+which+is+needed+to+build+dependency&type=issues e.g. https://github.com/elixir-lang/elixir/issues/8281 https://github.com/elixir-lang/elixir/issues/8252 https://github.com/elixir-lang/elixir/issues/7522 https://github.com/elixir-lang/elixir/issues/9987

They suggest broken `HOME`, proxy or IPv6 settings

**Comment by formingform** [comment]
> > Sorry, I'm a newbie of elixir, I just want to setup a develop environment for now.
> 
> I'm trying to help you and you did not answer my questions.
> 
> 1. Have you checked the access rights to `~/.mix`?
> 2. How did you install elixir? I can see you are not using asdf nor rtx for version management.
> 3. Can you start iex and check what happens if you run
> 
> ```
> Mix.install([{:stream_data, "~> 0.5"}])
> ```

I installed ErLang and Elixir by using "dpkg -i path_to_deb_file“.

Yes, I can start iex.  I got these by running ’Mix.install([{:stream_data, "~> 0.5"}])‘ in iex:
```
joey@Joey:~$ iex
Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Mix.install([{:stream_data, "~> 0.5"}])
Failed to fetch record for stream_data from registry (using cache instead)
Failed to check for new Hex version
:timeout
:timeout
Resolving Hex dependencies...
Resolution completed in 0.027s
New:
  stream_data 0.6.0
* Getting stream_data (Hex package)
You have added/upgraded packages you could sponsor, run `mix hex.sponsor` to learn more
==> stream_data
Compiling 3 files (.ex)
Generated stream_data app
:ok
```

> 
> Evidently your environment is broken if you are not able to install packages via hex. Please use [elixir](https://elixirforum.com) or [slack](https://elixir-lang.slack.com/archives/C03EPRA3B) for support. Github issues are reserved for bugs and feature requests
> 
> There are solutions if you search for your https://elixirforum.com/search?q=Could%20not%20find%20Hex%2C%20which%20is%20needed%20to%20build%20dependency, e.g. https://elixirforum.com/t/phoenix-ignoring-hex-install/16649/5 or https://elixirforum.com/t/encountering-could-not-find-hex-only-on-a-different-machine/55857/8 https://elixirforum.com/t/how-to-configure-location-for-hex-folder-file-error-could-not-make-directory-with-p/13936 There are numerous similar issues https://github.com/search?q=repo%3Aelixir-lang%2Felixir+Could+not+find+Hex%2C+which+is+needed+to+build+dependency&type=issues e.g. [elixir-lang/elixir#8281](https://github.com/elixir-lang/elixir/issues/8281) [elixir-lang/elixir#8252](https://github.com/elixir-lang/elixir/issues/8252) [elixir-lang/elixir#7522](https://github.com/elixir-lang/elixir/issues/7522) [elixir-lang/elixir#9987](https://github.com/elixir-lang/elixir/issues/9987)
> 
> They suggest broken `HOME`, proxy or IPv6 settings
