### ISSUE TITLE
@doc on hover quit showing recently

### ISSUE THREAD

**Issue by phewitt** [elixir-lsp/vscode-elixir-ls#394]
I'm wanting to know if anyone else has recently noticed @docs and @moduledoc no longer showing on hover. The spec still shows. I've noticed this same behavior on 3 different machines (Mac, Windows, ChromeBook). So I don't think it's environment specific. Has something changed with how to enable it here or on vscode itself? Even on fresh installs.

Here is an example of what I see now.

![Screenshot 2023-11-29 19 24 48](https://github.com/elixir-lsp/vscode-elixir-ls/assets/4573246/44fdc27f-6459-46bc-8789-8a2d492038c2)

I would expect to see the doc info.

```elixir
  @doc """
  Returns the list of products.

  ## Examples

      iex> list_products()
      [%Product{}, ...]

  """
  ```
  
  Am I missing something? Has something changed? has anyone else had this problem?

**Comment by lukaszsamson** [comment]
Extracting docs from the current file is not implemented and never worked. It works for remote calls and modules if the remote file is compiled.
