### ISSUE TITLE
Make use of ASDF managed OTP versions

### ISSUE THREAD

**Issue by NobbZ** [elixir-lsp/vscode-elixir-ls#4]
As the LS needs to be compiled with the appropriate version of erlang, try to pick and precompile proper LS version depending on the erlang configured in `.tool-versions` or whatever `asdf` tells us its using.

**Comment by balduncle** [comment]
asdf is being used in the elixir-ls repo now so I'm going to close this issue.  Any other asdf related improvements likely make more sense in the elixir-ls repo anyway.  Thanks.
