### ISSUE TITLE
All testcases run from VS Code on Windows are always passed 

### ISSUE THREAD

**Issue by ndtoan96** [elixir-lsp/vscode-elixir-ls#400]
### Precheck

I search opened issues with keyword "test" but don't see anything similar.

### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.16.0 (compiled with Erlang/OTP 26)
* Elixir Language Server version: v0.18.1
* Operating system: Windows
* Editor or IDE name (e.g. Emacs/VSCode): VS Code
* Editor Plugin/LSP Client name and version: ElixirLS

### Current behavior

Tests run by clicking the run test button are always passed.

I try to run command `mix test test\testcase.exs:<line>`, it is passed. However, running `mix test test/testcase.exs:<line>`, it is failed as expected => The issue is `\` and `/` in the path.

### Expected behavior

Wrong testcases should be failed.

**Comment by lukaszsamson** [comment]
What do you mean by "I try to run command"? Does mix command return wrong exit code when run with windows path separators? What path separators are generated by ElixirLS when it invokes the command on windows?

**Comment by ndtoan96** [comment]
> What do you mean by "I try to run command"? Does mix command return wrong exit code when run with windows path separators? What path separators are generated by ElixirLS when it invokes the command on windows?

I don't know what path separators are generated by ElixirLS, I just try to run the testcase alone to verify if other testcases affect the result and then I detect that problem. So, I highly suspect that ElixirLS generates the `\` separator.

**Comment by lukaszsamson** [comment]
That's a correct path separator for the platform. Can you verify if mix command returns correct exit code on windows with `\`? If it is not correct please report that to elixir project

**Comment by ndtoan96** [comment]
When separator is `\`, it returns exit code 0 and when separator is `/`, exit code 2. I guess it's a `mix` bug. I'll report to elixir project.
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/33489972/89f419a2-960e-44f4-8279-8edd57858373)

**Comment by lukaszsamson** [comment]
Reported upstream https://github.com/elixir-lang/elixir/issues/13225
We may need to workaround that issue on the extension side
