### ISSUE TITLE
Completions broke?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [elixir-lsp/vscode-elixir-ls#403]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

* VSCode ElixirLS version: 0.19.0
* Operating System Version: darwin 23.2.0

I just updated to the latest version of ElixirLS and my completions aren't working. If I type "def" and invoke completions, I just get "no suggestions".

Any suggestions on how I might trouble shoot? I've tried deleting my ".elixir_ls" dir and restarting vscode.

**Comment by CharlesIrvineKC** [comment]
If I load the previous version of ElixirLS (0.18.1) completions start working again. And, when I reload the most recent version (0.19.0), completions stop working.

**Comment by lukaszsamson** [comment]
Please post output logs, LSP message traces or a repo that reproduces this problem.

**Comment by CharlesIrvineKC** [comment]
When I invoke completions on test.ex, here is what I see:

![no_completions](https://github.com/elixir-lsp/vscode-elixir-ls/assets/657002/e195c922-dcc0-47f1-942b-01a18817b621)

**Comment by CharlesIrvineKC** [comment]
After I revert to version 0.18.3, I get the expected completions:

![completions_are_present](https://github.com/elixir-lsp/vscode-elixir-ls/assets/657002/e6adef10-53a4-4b35-af8a-d144dc84e064)

**Comment by lukaszsamson** [comment]
@CharlesIrvineKC https://github.com/elixir-lsp/vscode-elixir-ls#check-elixirls-output

**Comment by CharlesIrvineKC** [comment]
ElixirLS output logs:

[exlixir_output.log](https://github.com/elixir-lsp/vscode-elixir-ls/files/14025100/exlixir_output.log)

**Comment by lukaszsamson** [comment]
Your repo works on my machine.
<img width="1103" alt="Screenshot 2024-01-23 at 15 36 02" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/ed3deb6e-a8fc-4cd3-8d55-8ee0bca988be">

Your logs look correct. You can also enable tracing in ElixirLS extension settings
<img width="715" alt="Screenshot 2024-01-23 at 15 38 16" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/1078186/e9b5d804-8999-43cb-b484-836dcd979c42">

You should then see something like this in the output tab
```
[Trace - 15:38:29] Sending request 'textDocument/completion - (13)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/myuser/Downloads/complete_problem/lib/test.ex"
    },
    "position": {
        "line": 0,
        "character": 5
    },
    "context": {
        "triggerKind": 1
    }
}


[Trace - 15:38:29] Received response 'textDocument/completion - (13)' in 28ms.
Result: {
    "isIncomplete": true,
    "items": [
        {
            "command": {
                "command": "editor.action.triggerParameterHints",
                "title": "Trigger Parameter Hint"
            },
            "deprecated": false,
            "detail": "macro",
            "documentation": {
                "kind": "markdown",
                "value": "Defines a public macro with the given name and body."
            },
            "insertText": "defmacro $1 do\n\t$0\nend",
            "insertTextFormat": 2,
            "insertTextMode": 2,
            "kind": 21,
            "label": "defmacro",
            "labelDetails": {
                "description": "Kernel.defmacro/2",
                "detail": "(call, expr \\\\ nil)"
            },
            "sortText": "00000000",
            "tags": []
        },
        ...
```

**Comment by CharlesIrvineKC** [comment]
With verbose setting:

[exlixir_output.log](https://github.com/elixir-lsp/vscode-elixir-ls/files/14025578/exlixir_output.log)

**Comment by lukaszsamson** [comment]
ElixirLS extension is working correctly and returning completions. Please verify that no other extension is interfering. Please verify your VSCode settings - maybe some setting is filtering completions

**Comment by CharlesIrvineKC** [comment]
Did you ever check the sharedProcess.log file in the logs.zip file I posted? There was some suspicious stuff in the file I thought.

**Comment by CharlesIrvineKC** [comment]
I got out the big hammer. I deleted VS code and my settings, preferences, extensions etc, then reloaded ElixirLS and now completions are working. Who knows what the problem was exactly. Anyway, problem solved. Thanks for the help.
