### ISSUE TITLE
Syntax highlighting broken in "Darcula theme for Elixir"

### ISSUE THREAD

**Issue by moxley** [elixir-lsp/vscode-elixir-ls#404]
### Environment

- Elixir & Erlang versions (elixir --version): 1.16.0
- VSCode ElixirLS version: 0.19.0
- Operating System Version: MacOS 14.1.2

---

The latest version, 0.19.0 causes disrupted syntax highlighting provided by the "[Darcula theme for Elixir](https://marketplace.visualstudio.com/items?itemName=Arsen.darcula-theme-for-elixir)" (note the spelling of 'Darcula').

Screenshot, prior to version 0.19.0:

![CleanShot 2024-01-22 at 13 58 24@2x](https://github.com/elixir-lsp/vscode-elixir-ls/assets/86996/e3919b68-9fca-46bf-9806-c359b9563f9b)

Screenshot of version 0.19.0:

![CleanShot 2024-01-22 at 13 57 56@2x](https://github.com/elixir-lsp/vscode-elixir-ls/assets/86996/dea5ccbc-532c-477c-8c74-312e97611ae2)

In particular, the `do/end` pairs have different colors depending on what level of indentation they are on. They should all be the same orange color regardless of indentation level.

If this is a backwards incompatibility with Darcula theme for Elixir, let me know, and I'll file an issue with [that repo](https://github.com/arsssen/vscode-darcula-theme-elixir).

**Comment by lukaszsamson** [comment]
That’s not a bug. If you dislike bracket matching you can disable it in VSCode

**Comment by moxley** [comment]
> That’s not a bug. If you dislike bracket matching you can disable it in VSCode

Sounds good. Thank you!

**Comment by dj-murphy** [comment]
FYI, if you want to exclude do/end from bracket pair colorization, you can put this in your settings.json (it was bothering me too lol)
```json
"editor.language.colorizedBracketPairs": [
        [
            "[",
            "]"
        ],
        [
            "(",
            ")"
        ],
        [
            "{",
            "}"
        ],
    ],
```

**Comment by lukaszsamson** [comment]
@dj-murphy I wouldn't set that globally but scoped to elixir
```
"[elixir]": {
    "editor.language.colorizedBracketPairs": [...
```
