### ISSUE TITLE
 elixir extension not supported

### ISSUE THREAD

**Issue by Pratham1716** [elixir-lsp/vscode-elixir-ls#408]
Type: <b>Bug</b>

Code extension not supported

Extension version: 0.19.0
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.93GB free)|
|Process Argv|--crash-reporter-id aa32eb5c-8341-4804-84ca-7b30ecc3ea96|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
d34g3935:30958340
edj9j583:30958191
7j2b6412:30949929
bg6jg535:30958357

```

</details>

**Comment by lukaszsamson** [comment]
@Pratham1716 please fill the issue template

**Comment by Pratham1716** [comment]
![Screenshot (22)](https://github.com/elixir-lsp/vscode-elixir-ls/assets/157418887/d6487cd5-1f47-4cb4-894b-902c978481a8)
I have attached the screenshot of the error I am getting.

**Comment by lukaszsamson** [comment]
Closing, no details provided
