### ISSUE TITLE
Conflict with Code Spell Checker

### ISSUE THREAD

**Issue by arxeiss** [elixir-lsp/vscode-elixir-ls#41]
There is an conflict with [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension, (and maybe with other spell checkers as well).

When I have both extension installed, there is no grammar check in `.ex` and `.exs` files. I know the problem is caused by VSCode Elixir LS extension. Because when I disable it, I loose syntax highlight etc, but spell checker mark typos.

And **big thank you** for keeping this package alive!

**Comment by axelson** [comment]
What version of the Elixir LS Fork plugin are you using? And what version of VSCode?

**Comment by arxeiss** [comment]
**VS Code:**
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-40-generic

**Elixir LS Fork:**
Name: ElixirLS Fork: Elixir support and debugger
Id: elixir-lsp.elixir-ls
Version: 0.3.0

**Comment by arxeiss** [comment]
Sorry, I checked it again and it is working, my fault.
Either Spell Checker doesn't have spell checks ON for Elixir (but says it does). Or I did something wrong.

However, if someone else will have this issue, I just followed those steps and turned it on
https://github.com/streetsidesoftware/vscode-spell-checker/blob/master/packages/client/README.md#enable--disable-file-types

**Comment by axelson** [comment]
Glad you got it sorted!
