### ISSUE TITLE
Suggestion Problem

### ISSUE THREAD

**Issue by blzpedro** [elixir-lsp/vscode-elixir-ls#410]
Why I'm not getting the suggestion/autocomplete from Elixir-LS? Pressing ctrl + space doesn't work either.

I couldn't find the reason why isn't working.

Extension version: 0.19.0
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 26)
Windows 10

The output doesn't show any problem.
![image](https://github.com/elixir-lsp/vscode-elixir-ls/assets/33239399/f666fd3f-b13e-429c-9fbc-75e92a6d6196)

**Comment by lukaszsamson** [comment]
Cannot reproduce.
Please use forum or slack for support questions and reserver issue tracker for issues and feature requests. If you believe it's an issue please fill the issue template
