### ISSUE TITLE
How to Pass "--no-start" flag to the "mix test" command?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [elixir-lsp/vscode-elixir-ls#416]
To prevent my application from starting child GenServers when testing, I'd like to be able to pass the "--no-start" flag to "mix test" command like this "mix test --no-start". How can I cause this to happen when running tests from a file window in vscode?

**Comment by lukaszsamson** [comment]
Create a launch.json with a template configuration. The configuration named „mix test” is treated as template. In this configuration set „startApps”: false

**Comment by CharlesIrvineKC** [comment]
Thanks for the quick response. I'll close the ticket.

**Comment by CharlesIrvineKC** [comment]
The launch.json thing is new to me. I'm having some trouble.

I created the file .vscode/launch.json, with contents:

````
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "mix_task",
        "name": "mix test",
        "request": "launch",
        "task": "test",
        "taskArgs": [
          "--trace"
        ],
        "startApps": false,
        "projectDir": "${workspaceRoot}",
        "requireFiles": [
          "test/**/test_helper.exs",
          "test/**/*_test.exs"
        ]
      }
    ]
  }
````

After that, if I click on triangle run icons, I still get the error indicating that my GenServer is already started. See below. Any ideas? Thanks

![test_file](https://github.com/elixir-lsp/vscode-elixir-ls/assets/657002/fd52ff7b-c7f5-48d0-abb4-786b1c21c643)

![error](https://github.com/elixir-lsp/vscode-elixir-ls/assets/657002/f34122d7-283b-4316-9f36-229ca80c6363)

**Comment by CharlesIrvineKC** [comment]
Nevermind. It's working for me now. I had made a mess of things.
