### ISSUE TITLE
Improve elixir grammar: module prefixes

### ISSUE THREAD

**Issue by thiagomajesk** [elixir-lsp/vscode-elixir-ls#42]
As a follow up on https://github.com/elixir-lsp/vscode-elixir-ls/issues/22: This new issue is meant to track progress on adding a specific scope for "namespaces" to the Elixir grammar.

As previously discussed in the original issue, Elixir does not have namespaces as a builtin language construct, even though part of the module name it acts like it conceptually by convention. So, the objective is to provide an optional configuration to support further customization while keeping the current behavior as a fallback (if the configuration is not specified).

As @axelson suggested [here](https://github.com/elixir-lsp/vscode-elixir-ls/issues/22#issuecomment-589211000), a better name could be "module prefixes", which captures the essence of the scope without compromising semantics about the language specification. 

Notice that this should work for both module definitions and calls. It should also work for aliases, imports and requires.

**Comment by lukaszsamson** [comment]
It's been 3 years with no progress here. Closing this as stale. I'll reopen if anyone is willing to contribute
