### ISSUE TITLE
Enable ANSI colors by default when starting the app with `mix_task`

### ISSUE THREAD

**Issue by macabeus** [elixir-lsp/vscode-elixir-ls#422]
As far as I know, the built-in VS Code debug console supports all ANSI color features.

But when running the application using the `mix_task` task, it's disabled.

It would be good if it's enabled by default.
It avoids confusion and the need to explicitly turn it on from the application code.

### How to reproduce

1 - Clone [this repo](https://github.com/macabeus/vscode-elixir-ls-issue):

```
git clone git@github.com:macabeus/vscode-elixir-ls-issue.git
```

It's a dummy Elixir project with `.vscode/launch.json` configuration to start with `mix_task`

2 - Open the project with VS Code

3 - Run the debugger:

<img width="240" alt="image" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/9501115/f06882d7-e329-48de-a0de-d6c399ea9818">

4 - You'll can see from the debug console that the `ansi_enabled` is disabled, and there are no ANSI colors:

<img width="444" alt="image" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/9501115/f55c34f0-4514-47a5-9adb-f70caffddc31">

5 - But the VS Code debug console supports ANSI colors. If we uncomment the line from `lib/application.ex`, you'll can see it working as expected:

<img width="437" alt="image" src="https://github.com/elixir-lsp/vscode-elixir-ls/assets/9501115/906fb83d-7ca0-46f3-8025-f5ef44285865">

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.17.0 (compiled with Erlang/OTP 26)

* VSCode ElixirLS version: 0.22.0
* Operating System Version: darwin 23.4.0

**Comment by lukaszsamson** [comment]
Last time I checked on VSCode 1.85 it looked bad in both Debug console and Test results thought they supposedly added support in 1.80. On 1.90 it looks OK. Thanks for the repro
