### ISSUE TITLE
Debugging and IO.gets

### ISSUE THREAD

**Issue by odalet** [elixir-lsp/vscode-elixir-ls#427]
When running a debugging session, all of the I/O is redirected to VSCode's Debug Console. Unfortunately, this console does not support input. Hence, the debugger gets stuck on the first `IO.gets` instruction it encounters.

Would it be possible to specify in the `launch.json` options to not use the Debug Console, but rather a regular terminal?

* Elixir Version: 
  ```
  Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

  Elixir 1.16.3 (compiled with Erlang/OTP 26)
  ```
* ElixirLS: `v0.22.1`
* OS: Windows 10

**Comment by lukaszsamson** [comment]
No, that would not be possible in launch mode. DAP uses the terminal stdio for protocol communication. A couple of ideas:
1. Upcoming attach mode. I recently added support for connecting to remote OTP nodes. You would run your app in terminal and connect the DAP server. If you would like to try it you need to run the master version. See https://github.com/elixir-lsp/vscode-elixir-ls?tab=readme-ov-file#contributing
2. Read input from a file in debug session. You could pass a file via env or elixir config

**Comment by odalet** [comment]
I'm very new to Elixir, but I managed to mock my IO.gets when debugging. So I'm good to go for now.
As for the upcoming attach mode, it seems interesting. I might try it once I have some time.

Thanks again for the pointers !
