### ISSUE TITLE
Code folding is lost if both "Phoenix Framework" and "ElixirLS" extensions are installed in vscode.

### ISSUE THREAD

**Issue by CharlesIrvineKC** [elixir-lsp/vscode-elixir-ls#428]
If I have "Phoenix Framework" extension installed in vscode, I lose the ability to collapse and expand sections of code.

![no_folding](https://github.com/user-attachments/assets/4e3ac0f5-7210-426f-972f-48977cf3c6c7)

If I disable "Phoenix Framework" then collapsing and expanding works as expected.

![vscode_folding](https://github.com/user-attachments/assets/9e1829ee-00d2-4593-a509-7cbd807b762f)

Any ideas on what the fix might be? Thanks

**Comment by wheredoipressnow** [comment]
[You can enable code folding by updating the Phoenix Framework configuration](https://github.com/phoenixframework/vscode-phoenix/issues/24#issuecomment-2020326206).

**Comment by CharlesIrvineKC** [comment]
That fixed it for me. Thanks
