### ISSUE TITLE
Improve elixir grammar: function calls without parenthesis

### ISSUE THREAD

**Issue by thiagomajesk** [elixir-lsp/vscode-elixir-ls#43]
As a follow up on #22: This new issue is meant to track progress on expanding the `entity.name.function-call.elixir` scope added on https://github.com/elixir-lsp/vscode-elixir-ls/pull/40 to function calls without parenthesis.
As exemplified [here](https://github.com/elixir-lsp/vscode-elixir-ls/issues/22#issuecomment-570805792), while we can't disambiguate calls for [niladic](https://en.wikipedia.org/wiki/Arity) functions, we probably could do it for functions that have at least one parameter.

Example: The current behavior for `greet/1` is that  `greet("Hello")`  will be scoped to `entity.name.function-call.elixir` while `greet "Hello"` will be scoped to `source.elixir`.

**Comment by lukaszsamson** [comment]
It's been 3 years with no progress here. Closing this as stale. Besides that elixir is slowly deprecating fun calls without parens
