### ISSUE TITLE
the extension not accessing the path to batch file correctly

### ISSUE THREAD

**Issue by Aulk98** [elixir-lsp/vscode-elixir-ls#432]
@lukaszsamson @wheredoipressnow Hi there is still some issue in LS even after update but it is coming from both vs_code versions 1.91.1 & 1.92.0 here is Error ElixirLS output:

 ```
D:\Elixir' is not recognized as an internal or external command,
 operable program or batch file.
 [Error - 10:53:03 AM] Server initialization failed.
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Info  - 10:53:03 AM] Connection to server got closed. Server will restart.
 true
 [Error - 10:53:03 AM] ElixirLS - Elixir_Project client: couldn't create connection to server.
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Error - 10:53:03 AM] Server process exited with code 1.
 'D:\Elixir' is not recognized as an internal or external command,
 operable program or batch file.
 [Error - 10:53:03 AM] Server initialization failed.
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Info  - 10:53:03 AM] Connection to server got closed. Server will restart.
 true
 [Error - 10:53:03 AM] ElixirLS - Elixir_Project client: couldn't create connection to server.
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Error - 10:53:03 AM] Server process exited with code 1.
 'D:\Elixir' is not recognized as an internal or external command,
 operable program or batch file.
 [Error - 10:53:03 AM] Server initialization failed.
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Info  - 10:53:03 AM] Connection to server got closed. Server will restart.
 true
 [Error - 10:53:03 AM] ElixirLS - Elixir_Project client: couldn't create connection to server.
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Error - 10:53:03 AM] Restarting server failed
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Error - 10:53:03 AM] Server process exited with code 1.
 'D:\Elixir' is not recognized as an internal or external command,
 operable program or batch file.
 [Error - 10:53:03 AM] Server initialization failed.
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Info  - 10:53:03 AM] Connection to server got closed. Server will restart.
 true
 [Error - 10:53:03 AM] ElixirLS - Elixir_Project client: couldn't create connection to server.
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Error - 10:53:03 AM] Restarting server failed
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Error - 10:53:03 AM] Server process exited with code 1.
 'D:\Elixir' is not recognized as an internal or external command,
 operable program or batch file.
 [Error - 10:53:03 AM] Server initialization failed.
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Error - 10:53:03 AM] The ElixirLS - Elixir_Project server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
 [Error - 10:53:03 AM] ElixirLS - Elixir_Project client: couldn't create connection to server.
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Error - 10:53:03 AM] Restarting server failed
   Message: Pending response rejected since connection got disposed
   Code: -32097 
 [Error - 10:53:03 AM] Server process exited with code 1.
 ```
 
 so, can you please fix this issue or way to fix this issue
 
 Edit: I don't know if I am correct or wrong, I think the extension not accessing the path to batch file correctly, in laguageserver override path if I give "path/to/release" it works, but without quotes i get same error

**Comment by lukaszsamson** [comment]
I cannot reproduce that. What is your configuration? How did you install the extension?

**Comment by Aulk98** [comment]
* Elixir & Erlang versions (elixir --version): Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.17.2 (compiled with Erlang/OTP 27)

* VSCode ElixirLS version: 0.23.0
* Operating System Version: win32 10.0.19045
![image](https://github.com/user-attachments/assets/47fefe56-a551-424b-854f-ca55b9662d67)
I install directly from vs code extension 
then I got this error, so I copy the repo used the elixirls/release to Language server override path 
in which I find out the path that the extension access to run bat file
as C:\Users\%userprofile%\.vscode\extensions\jakebecker.elixir-ls-0.23.0\elixir-ls-release instead of "C:\Users\%userprofile%\.vscode\extensions\jakebecker.elixir-ls-0.23.0\elixir-ls-release" 
in line 30
I am new to coding so; I just give the path directly and it works 
![image](https://github.com/user-attachments/assets/c594b15c-d6b4-408d-8db8-e5082756050e)

**Comment by lukaszsamson** [comment]
Sorry, it's confusing. Are you trying to use the extension or contribute to it? If you aim to contribute then head to https://github.com/elixir-lsp/vscode-elixir-ls?tab=readme-ov-file#contributing
Otherwise, it seems elixir command is not accessible in your system PATH.

**Comment by Aulk98** [comment]
![image](https://github.com/user-attachments/assets/d23bbeca-4332-441b-b7f0-597d801df8d6)
just for clarification, normally how should we insert path in this setting

**Comment by lukaszsamson** [comment]
Normally you don't need to pass anything there

**Comment by Aulk98** [comment]
yeah, I know but the extension didn't access the .bat file
D:\Elixir' is not recognized as an internal or external command,
operable program or batch file.
by default, it should access the file from C:\Users\%userprofile%\.vscode\extensions\jakebecker.elixir-ls-0.23.0\elixir-ls-release
and start the LS but in my case it directly sending path to shell which is causing the error
so, I tried to set path without quates I got the same error
![image](https://github.com/user-attachments/assets/02a75371-8284-4605-9fb8-7cd23b7c162b)
then I tried with quates and it works then the debug session not starting
![image](https://github.com/user-attachments/assets/1d6317e0-34bd-4999-a79c-5344670f291d)
![image](https://github.com/user-attachments/assets/e25dc7ff-c404-47d0-a6e6-3129174e16c5)

**Comment by paulanthonywilson** [comment]
Do you have spaces in your path / user home directory?

A number of people at work who are using Windows and have spaces in their windows home directory path (or whatever it's called in windows)  are reporting similar issues having just updated.

**Comment by Aulk98** [comment]
I just created PR for this issue, now it is working perfectly fine

**Comment by Aulk98** [comment]
> Do you have spaces in your path / user home directory?
> 
> A number of people at work who are using Windows and have spaces in their windows home directory path (or whatever it's called in windows) are reporting similar issues having just updated.

@paulanthonywilson  you mean userprofile, yeah I have spaces in it

**Comment by iamkanishka** [comment]
@lukaszsamson  still  looking for the solution, please let us know

**Comment by lukaszsamson** [comment]
https://github.com/elixir-lsp/vscode-elixir-ls/pull/433 is supposedly fixing that but I need to verify it does not break mac and linux. I'll try to release a patch shortly.
