### ISSUE TITLE
Autocomplete does not work for functions generated via `macros` in the same module/file.

### ISSUE THREAD

**Issue by SergeyMosin** [elixir-lsp/vscode-elixir-ls#435]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
* Elixir 1.15.7 (compiled with Erlang/OTP 26)
* VSCode ElixirLS version: 0.23.1
* Operating System Version: linux 6.8.0-40-generic, Ubuntu 22.04.5 LTS

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

### Description/Problem
Autocomplete does not work for functions generated via `macros` in the same module/file. However, it works when called from other modules/files.

### Details
MyMacros.ex
```elixir
defmodule MyMacros do
  defmacro enums_kv(kv) do
    Enum.map(kv, fn {k, v} ->
      quote do
        @spec unquote(k)() :: unquote(v)
        def unquote(k)(), do: unquote(v)
      end
    end)
  end
```

MyMod.ex (Autocomplete does NOT works when typing `on` or `tw` inside `hello`)
```elixir
defmodule MyMod do
  require MyMacros
  MyMacros.enums_kv(one: 1, two: 2)
  # enums_kv(one: 1, two: 2) generates:
  #   def one, do: 1
  #   def two, do: 2

  def hello do
    one()
  end
end
```

MyOtherMod.ex (Autocomplete works when typing `MyMod.t` or `MyMod.o` inside `hello`)
```elixir
defmodule MyOtherMod do
  def hello do
    MyMod.two()
  end
end
```

### Demo/Video

[video-demo.webm](https://github.com/user-attachments/assets/8f655f28-761e-4e8a-b3f7-52f2756d05da)

**Comment by lukaszsamson** [comment]
This is the current limitation - only trivial `use` macros are expanded. This branch has change replacing the inference engine and rebuilding it on top of new `Macro.Env` API https://github.com/elixir-lsp/elixir-ls/pull/1116. With that macro expansion is possible in more places and this scenario is working.
<img width="565" alt="Screenshot 2024-09-21 at 15 15 38" src="https://github.com/user-attachments/assets/3ede7843-31c7-45b6-ac93-50df9a93c466">
