### ISSUE TITLE
Freezes Manjaro completely

### ISSUE THREAD

**Issue by Slesa** [elixir-lsp/vscode-elixir-ls#442]
When working long enough with elixir code, and hovering over parts of the code, it happens that my OS freezes completely. Unfortunately, it has not saved the changes for about half an hour or so, so all work of this time is lost.

Has anyone else such problems?

**Comment by lukaszsamson** [comment]
Do you have a stacktrace or a crash dump? Otherwise I don't think it's the right place to debug OS issues

**Comment by Slesa** [comment]
It does not seem to crash really, and I did not notice a sign of dump. I have to power off the laptop for a restart. 
Well, in this case I have to use another editor with highlight support. I have no idea where or what to search for. But yesterday was the 2nd time, so ...

**Comment by lukaszsamson** [comment]
Do you have a repro?

**Comment by Slesa** [comment]
Well, I simply enter the text of the book 'Functional Web Development with Elixir', and after nearly each chapter I was in such an error state. When I was looking for a wrong entered character. Often ) instead of }. And I think it was always when displaying some large content, as in the module docs perhaps? But that does not explain why it didn't suddenly save anymore.

**Comment by Slesa** [comment]
I may have a hint: on Fedora, it worked without freezing. Is it possible that missing inotify-tools lead to such a freeze?

**Comment by Slesa** [comment]
After installation of inotify tools, it never happened again.
