### ISSUE TITLE
Incorrect Elixir being used.

### ISSUE THREAD

**Issue by BobbyMcWho** [elixir-lsp/vscode-elixir-ls#45]
Hello, I use ASDF for elixir version management, and it seems this plugin is trying to use my global elixir version rather than the local version set by the .tool-versions and ASDF.

**Comment by BobbyMcWho** [comment]
restarting vscode seems to have fixed this, but now I'm having my fans spin up a ton...

**Comment by axelson** [comment]
Glad it's working. The fans spinning up is most likely dialyzer running. The first time it runs it builds up a cache, after that each run will be significantly faster.
