### ISSUE TITLE
accept suggestions on enter instead of tab not working

### ISSUE THREAD

**Issue by steveryan** [elixir-lsp/vscode-elixir-ls#51]
Hey all, 

Thanks for this awesome vs code plugin. Everything is working great, but I can't seem to be able to get it to accept suggestions on enter. I'm probably missing something simple, but I can't get it working.

Here is my vs code settings.json
`
{
    "workbench.colorTheme": "dark+(elixir)",
    "editor.formatOnSave": true,
    "editor.acceptSuggestionOnEnter": "on"
}
`

From reading the readme, it _seems_ like that's all that should be required. Completeing with tab is working fine btw.

Edit: Enter is working to accept suggestions in .html.eex files, but not .ex files. Not sure if that helps

**Comment by axelson** [comment]
Hmm, that's a weird one. As far as I can tell there's no code in vscode-elixir-ls that relates to that. The only code is in https://github.com/elixir-lsp/vscode-elixir-ls/blob/c7e9679b782cf7ed79d2713ace1cb340fe0af56d/src/extension.ts

Maybe this is some sort of VSCode bug? Not sure what else to check. But I also see this behavior. What platform are you on? I'm on Arch Linux and running vscode-oss.

**Comment by steveryan** [comment]
@axelson I'm on a Mac and running the latest VSCode. I kind of don't think it's a VSCode bug since enter to accept suggestions is working for .eex files, and in my rails projects.

**Comment by NobbZ** [comment]
As far as I remember, you need to enable that setting explicitely for the elixir edit mode…

```json
"[elixir]": {
  "editor.acceptSuggestionOnEnter": "on"
}
```

It is defined here:

https://github.com/elixir-lsp/vscode-elixir-ls/blob/master/package.json#L28-L37

**Comment by steveryan** [comment]
@NobbZ Amazing, thanks a lot! That solved it

**Comment by axelson** [comment]
@NobbZ do you think we should keep that setting as-is? Or should we remove that default and let user's set it for themselves? If we don't remove the default I think we need to document it better in the readme.

**Comment by NobbZ** [comment]
Personally I tend to remove it, as I never understood why this was there at all…

The other settings are somewhat relevant to the language, but this one is really about personal preference.

**Comment by axelson** [comment]
Yeah I think it makes sense to just remove it
