### ISSUE TITLE
"Go to definition" not working

### ISSUE THREAD

**Issue by iteron-yasir** [elixir-lsp/vscode-elixir-ls#54]
My system config,

Ubuntu - 18.04
VS Code - 1.43.0
Elixir 1.9.2

I've the docker elixir project and I'm using "bitwalker/alpine-elixir:1.9.2" image.

When I click F12. It's only showing "No definition found". It's not working. When I try Ctrl  + Shift + F, I can able to find the function.

**Comment by axelson** [comment]
None of the maintainers use docker with elixir so it's not fully supported, but if you can provide a reproducible example of the problem (with the necessary setup steps) then I can take a look.

**Comment by Korbin73** [comment]
I'm getting the same issue without docker just on my mac. 
VS code: 1.43.2
Elixir 1.9.2
MacOS: 10.15.4

**Comment by axelson** [comment]
@Korbin73 what docker image are you using? Does it have `bash`? If not try installing it. That worked for another user over at https://github.com/elixir-lsp/vscode-elixir-ls/issues/66#issuecomment-609475238

**Comment by Korbin73** [comment]
@axelson I'm actually not using docker. However, I just realized that go to definition works if the function is in the same file, but fails if it is in a different module, is this a limitation of go to definition?

**Comment by axelson** [comment]
@Korbin73 sorry about that. Go to definition should work for any module in your project. Can you open a new issue and attach any relevant logs? And even better would be if you could provide a reproducible example.

@iteron-yasir please let me know if the workaround in https://github.com/elixir-lsp/vscode-elixir-ls/issues/66#issuecomment-609475238 does not work for you and we can investigate further.

**Comment by raphaklaus** [comment]
I have the same problem. Maybe the fact that I am using Elixir installed from asdf? 🤔

**Comment by axelson** [comment]
@raphaklaus Asdf installations are fully supported and go to definition should work for any module in your project (besides ""Go to definition" does not work within the scope of a Phoenix router"). Can you open a new issue and attach any relevant logs? And even better would be if you could provide a reproducible example.

**Comment by Korbin73** [comment]
In my case I was trying to go to definition in an umbrella project which didn't work but worked as intended in a normal project.
