### ISSUE TITLE
Support multiple project folders

### ISSUE THREAD

**Issue by ndarilek** [elixir-lsp/vscode-elixir-ls#58]
I'm fairly new to VSCode, so maybe I'm using it wrong. I have a single project containing multiple microservices in different languages, several in Elixir. I'd eventually like to manage the whole thing in VSCode--launch Skaffold and deploy everything into Minikube, switch between Kotlin and Elixir services in different editor groups, etc.

Unfortunately, I can't see the Mix project directory setting in my workspace configurations.

Again, I'm new to VSCode. Maybe I should be opening each microservice in its own window, and should give up on trying to wrangle the whole thing in a single project. But it did work fine until we added another Elixir project, so I'm wondering how painful it'd be to run several separate language server instances and let me configure the Mix project directory per workspace. May take up more RAM, but that's wy I have 32 GB. :)

Or maybe workspaces are the wrong fix? Can I add .vscode/ directories in each subdirectory containing an Elixir project, then opening a file in one of those directories will automatically run the language server with the correct context, even if my project is still in a single tabbed window?

Thanks.

**Comment by axelson** [comment]
Currently your best bet is to open up multiple windows, one for each elixir project. A PR to improve this would definitely be welcomed but at the moment I'm not sure what would be involved.

**Comment by alex88** [comment]
@ndarilek can you please test with latest master to make sure the PR fixes your issue?

**Comment by aj-foster** [comment]
Hello there 👋 Apologies if this is the wrong place for this question. Unfortunately for us, our multi-project workspace includes two Elixir projects that are located in sub-directories. Normally we use the `elixirLS.projectDir` setting in the individual projects, but this setting is unavailable on a per-project basis. Do you have any advice for us?

**Comment by alex88** [comment]
@aj-foster try latest master version of the extension, it should work. The changes hasn't been released yet iirc

**Comment by aj-foster** [comment]
Hi @alex88, I built the extension using `elixir-lsp/vscode-elixir-ls@master` with elixir-lsp/elixir-ls@959bc556d9193ea2ab8ad9337e52d31fe11cb938 (any later commits failed to build). With that VSIX installed, ElixirLS does not appear in the list of settings available for individual folders in the workspace. Should I be looking elsewhere?

**Comment by alex88** [comment]
@aj-foster what do you need the settings for? The projectDir shouldn't be used anymore I think, you can just open the two root folders (those with mix.exs) and it should work

**Comment by aj-foster** [comment]
Apologies, I'll try to illustrate the interesting setup we have (for other reasons outside the scope of working in Elixir):

```
workspace/
├── project_A/
│   ├── elixir_root_A/
│   ├── other_stuff/
└── project_B/
    ├── elixir_root_B/
    └── other_stuff/
```

The folders `project_A` and `project_B` are the two folders open in the multi-project workspace. When we open each of the projects individually, we're able to set `elixirLS.projectDir` to forward ElixirLS on to `elixir_root_*`.

It sounds like you're suggesting that we should instead open `elixir_root_*` directly, and avoid opening `project_*` where possible.

**Comment by alex88** [comment]
@aj-foster that's how i usually do that, this way each root gets its own language server instance automatically (before only one instance per vscode was allowed). I have never used `projectDir` honestly so I'm not exactly sure about how that works

**Comment by aj-foster** [comment]
Upon further review and some testing, it appears the main barrier to modifying ElixirLS-related settings on a per-folder basis when working in a multi-projec workspace is the `scope` property of the extension's provided configuration. For example, if we were to modify `package.json` like this:

```
        "elixirLS.projectDir": {
          "scope": "resource", // <--- this line
          "type": "string",
          "description": "Subdirectory containing Mix project if not in the project root",
          "minLength": 1
        },
```

The ElixirLS instances begin operating in the correct directories of their respective projects.

According to the [documentation](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration):

>A configuration setting can have one of the following possible scopes:
>
>  ...
>  • `window` - Windows (instance) specific settings which can be configured in user, workspace, or remote settings.
>  • `resource` - Resource settings, which apply to files and folders, and can be configured in all settings levels, even folder settings.
>  ...
>
>Configuration scopes determine when a setting is available to the user through the Settings editor and whether the setting is applicable. If no scope is declared, the default is `window`.

If there's interest, I can investigate each of the configuration keys and make a PR with a recommended `scope` added.

**Comment by aj-foster** [comment]
Also, my apologies to @ndarilek — after re-reading the description of the `elixirLS.projectDir` setting, that appears to be what you were asking about to begin with. Just made the connection in my mind.

**Comment by ndarilek** [comment]
No worries. Apologies for not being more active on this issue. I've 
since stopped working with the client where this particular issue was 
relevant, so it'd be difficult for me to put any proposed changes 
through their paces. But it seems like other folks are hitting the same 
speedbump, so hopefully something can be hashed out.

**Comment by axelson** [comment]
@aj-foster I'm not sure I understand why changing the `elixirLS.projectDir` setting scope to `resource` is necessary. ElixirLS should work if you don't set `elixirLS.projectDir` at all, but create a new workspace, and add the two elixir projects. Here's a sample repository that you can try out: https://github.com/axelson/multi-directory-example

With that said I'm not saying I'm against changing the scope of `elixirLS.projectDir`, I just want to make sure I understand if that is necessary, or if it's merely an improvement. Also, can you find a link to the VSCode docs about how to set folder settings? I wasn't able to find them when searching.

**Comment by ndarilek** [comment]
Speaking for my particular use case, we had a top-level project with 
subprojects in Kotlin and multiple Elixir libraries. The top-level 
project also had some orchestration that applied to everything, and 
because our dev tooling became somewhat complex, I eventually built a 
devcontainer that downloaded all the crazy K8s tooling we needed and 
made sure it was available so you could just open in VSCode and drop 
into a terminal.


Still somewhat new to VSCode, but AFAIK opening things in separate 
workspaces would have lost us all of that. And work commonly touched 
multiple subprojects at a time. So either you're running things in 
separate workspaces and sacrificing the holistic approach, or you're 
just giving up on Elixir tooling, or maybe you're requiring settings 
updates each time someone switches the primary Elixir subproject they're 
working on.


Maybe there's an easier way, but this extension was the only one that I 
struggled with in this regard. Maybe other extensions would have given 
me grief if we had multiple Kotlin projects with their own build.gradle 
files, not sure...

**Comment by aj-foster** [comment]
My (naive) understanding, given the following setup in a multi-root workspace:

```
workspace/
├── .vscode/settings.json
├── project_A/
│   ├── .vscode/settings.json
└── project_B/
    └── .vscode/settings.json
```

When the scope of the setting is `window`, ElixirLS will only look for settings in the root `.vscode` directory, even though there are separate instances running in each project. This makes it impossible to use different settings (`elixirLS.projectDir` is one example, but settings related to Dialyzer behavior and Mix environment are also notable) in the two projects.

With a scope of `resource`, the individual ElixirLS instances will be able to use settings from the individual projects.

**Comment by axelson** [comment]
@aj-foster thanks for the explanation! That clears it up for me.

With the changes in #70 and #110 we can consider this fixed. Although of course any relevant issues can still be filed.
