### ISSUE TITLE
Support EEx tags inside HTML attributes

### ISSUE THREAD

**Issue by dbi1** [elixir-lsp/vscode-elixir-ls#62]
Hello,

I'm using VS Code 1.43.2 and ElixirLS Fork 0.3.2.

Somehow, I can't get EEx tags to highlight correctly inside HTML attributes, as the entire quoted attribute highlights as a single string.

Example:
`<div id="user_<%= @id %>">`

In the above example, `"user_<%= @id %>"` highlights as a string. Ideally, `<%= @id %>` would highlight in the usual EEx tag format inside the string highlighting.

The issue is illustrated nicely with two pictures in this pull request for the original ElixirLS: [https://github.com/JakeBecker/vscode-elixir-ls/pull/121)](https://github.com/JakeBecker/vscode-elixir-ls/pull/121). Not sure why it's not working for me, maybe it didn't make it into the published extension (I don't know much about how VS Code extensions work)?

Thank you for any help on this and all the work on this really useful extension!

**Comment by axelson** [comment]
Hi, this should work. Perhaps you have a conflicting extension installed?

**Comment by axelson** [comment]
Closing due to lack of response. If you're still seeing this then we can revisit.
