### ISSUE TITLE
Add syntax highlighting in Markdown code block

### ISSUE THREAD

**Issue by mupkoo** [elixir-lsp/vscode-elixir-ls#68]
Since this is missing from this package, and I think that this is the only package that you need to work with Elixir, will you be interested in adding a support for syntax highlighting in markdown code blocks? 

There is an existing addon that this, but I think it might be good if it is integrated into this one, as I personally expected this to work, instead of looking for an additional package.

If you think that this is a good idea, I can create a PR

Thank you

**Comment by axelson** [comment]
A PR adding this would definitely be welcome 👍

**Comment by jayjun** [comment]
Sent https://github.com/microsoft/vscode-markdown-tm-grammar/pull/75 to support Elixir and Erlang in default Markdown grammar.
