### ISSUE TITLE
Inconsistent formatting when opening multiple projects

### ISSUE THREAD

**Issue by alex88** [elixir-lsp/vscode-elixir-ls#69]
### Environment

Most of this can be filled out by running the VSCode command (by default bound to Ctrl+Shift+P) "ElixirLS Fork: Copy Debug Info"
```
  * Elixir & Erlang versions (elixir --version): Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.2 (compiled with Erlang/OTP 22)

  * VSCode ElixirLS Fork version: 0.3.2
  * Operating System Version: darwin 19.4.0
```

### Troubleshooting

- [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [X] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  - NOTE: This will cause you to have to re-run the entire dialyzer build

Starting with a new phoenix repo my formatter file consists of:
```
[
  import_deps: [:ecto, :phoenix],
  inputs: ["*.{ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{ex,exs}"],
  subdirectories: ["priv/*/migrations"]
]
```

and a sample ecto schema file the fields are without parenthesis because of https://github.com/elixir-ecto/ecto/blob/master/.formatter.exs

So this code snippet when formatting via VSCode and via CLI stays the same

```
  schema "users" do
    field :name, :string

    timestamps()
  end
```

So far everything is correct.

In the case where I have multiple projects (e.g. I usually open both the frontend and backend) and the elixir project is not first (backend first then frontend), the formatter doesn't seem to respect the `.formatter.exs` file.
After moving the project in the 2nd+ position it adds the parenthesis:

```
  schema "users" do
    field(:name, :string)

    timestamps()
  end
```

**Comment by axelson** [comment]
> In the case where I have multiple projects (e.g. I usually open both the frontend and backend) and the elixir project is not first (backend first then frontend), the formatter doesn't seem to respect the .formatter.exs file.

Can you explain exactly how you're opening the multiple projects? Is the elixir project not at the root of the workspace? Are there multiple elixir projects?

> After moving the project in the 2nd+ position it adds the parenthesis:

What exactly do you mean by moving the project?

I apologize if these are basic questions, but I don't use VSCode as my primary editor.

**Comment by alex88** [comment]
@axelson sure! No worries my bad for not explaining those properly.

Imagine this folder structure:
```
Desktop
 | frontend
 | backend
```

if I only open the backend folder, everything is working properly, formatter works fine as expected.
If I then do `File > Add folder to Workspace` and I select the frontend folder I end up in this situation:

![Screen Shot 2020-04-11 at 7 37 09 PM](https://user-images.githubusercontent.com/436888/79059183-dd82db80-7c2b-11ea-863c-c12a690b5487.png)

so my editor has two open folders, backend first and then frontend (look at the sidebar). Saving and/or manually formatting the file works fine.
If I switch the backend and frontend positions like this:

![Screen Shot 2020-04-11 at 7 37 20 PM](https://user-images.githubusercontent.com/436888/79059205-030fe500-7c2c-11ea-8bfd-0655d617ef18.png)

you can see that now the formatter added the parenthesis to the code, like it's not picking the formatter configuration from the project.

**Comment by axelson** [comment]
Okay, this seems like a subset of #58, I'll leave it open for now since it's possible this could be fixed before adding general support for multiple project folders. But the workaround is to open a new editor instance for each project. PR's are of course welcome, although they may involve significant work to https://github.com/elixir-lsp/elixir-ls/ to handle multiple project directories simultaneously (but if we're scoping that to just formatting it is probably significantly easier).

**Comment by alex88** [comment]
@axelson PR submitted
