### ISSUE TITLE
Document local development instructions

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/vscode-elixir-ls#7]
This comment has some instructions that should be a good starting point:
https://github.com/JakeBecker/elixir-ls/pull/163#issuecomment-481289405

> But if you don't want to wait for the package to be published, you can build the package yourself:
>
> ```
> git clone --recursive https://github.com/leandrocp/vscode-elixir-ls
> cd vscode-elixir-ls
> git checkout support-phoenix-live-view
> npm install
> npm install -g vsce
> vsce package
> ```
>
> A file elixir-ls-0.2.24.vsix will be generated in the current path. On vscode, go to Extensions > ... > Install from VSIX... to install the package.

**Comment by axelson** [comment]
For some reason `npm install -g vsce` didn't install a `vsce` binary to my `$PATH` so I installed the vsce AUR (Arch Linux) package instead.

**Comment by balduncle** [comment]
This is resolved by #8, though I'm sure we'll keep improving.
