### ISSUE TITLE
syntax highlighting for liveview html.leex templates 

### ISSUE THREAD

**Issue by delta1** [elixir-lsp/vscode-elixir-ls#84]
With the release of Phoenix 1.5 it's much easier to include [LiveView](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html) 

https://www.phoenixframework.org/blog/build-a-real-time-twitter-clone-in-15-minutes-with-live-view-and-phoenix-1-5 

#83 adds the .html.leex filetype for syntax highlighting and filewatching

**Comment by axelson** [comment]
#83 has been merged
