### ISSUE TITLE
Repeatedly fails to build core Dialyzer Elixir PLT

### ISSUE THREAD

**Issue by rlipscombe** [elixir-lsp/vscode-elixir-ls#85]
The VS Code extension repeatedly loops, failing to build the core PLT file. It's attempting to write it to `/.mix`, rather than `~/.mix`.

### Environment

Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-46-generic

  * Elixir & Erlang versions (elixir --version): Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.10.2 (compiled with Erlang/OTP 21)

  * VSCode ElixirLS version: 0.3.3
  * Operating System Version: linux 5.3.0-46-generic

### Diagnosis

I cloned the vscode-elixir-ls project and added some tracing in `elixir_plt_path()`:

```
JsonRpc.show_message(:info,
    "XDG_DATA_HOME is #{System.get_env("XDG_DATA_HOME")}, MIX_HOME is #{System.get_env("MIX_HOME")}, ~/.mix is #{Path.expand("~/.mix")}, Mix home is #{Mix.Utils.mix_home()}")
```

```
XDG_DATA_HOME is , MIX_HOME is /.mix, ~/.mix is /home/roger/.mix, Mix home is /.mix
```

This evaluates the environment variables used by `Mix.Utils.mix_home/0`. Now, it's fairly obvious that `MIX_HOME` is getting set somehow. But I'm not setting it:

```
$ env | grep MIX
$ 
```

If I explicitly set it:

```
$ MIX_HOME=$HOME/.mix code .
```

...then everything's fine. How can I debug/fix this problem?

---
The extension works fine on VS Code on my Mac, incidentally.

**Comment by rlipscombe** [comment]
Oh, here's interesting:

```
$ pgrep -f language_server
29323
$ ps -ef | grep 29323
roger    29323 29184  0 15:40 ?        00:00:00 bash /home/roger/.vscode/extensions/jakebecker.elixir-ls-0.3.3/elixir-ls-release/language_server.sh
roger    29333 29323 99 15:40 ?        00:04:22 /usr/lib/erlang/erts-10.7.1/bin/beam.smp -- -root /usr/lib/erlang -progname erl -- -home /home/roger -- -pa /usr/lib/elixir/bin/../lib/eex/ebin /usr/lib/elixir/bin/../lib/elixir/ebin /usr/lib/elixir/bin/../lib/ex_unit/ebin /usr/lib/elixir/bin/../lib/iex/ebin /usr/lib/elixir/bin/../lib/logger/ebin /usr/lib/elixir/bin/../lib/mix/ebin -noshell -s elixir start_cli -- -extra -e ElixirLS.LanguageServer.CLI.main()
roger    31648 31559  0 15:44 pts/4    00:00:00 /bin/grep --color=auto 29323
$ cat /proc/29323/environ | tr '\0' '\n' | grep HOME
HOME=/home/roger
$ cat /proc/29333/environ | tr '\0' '\n' | grep HOME
HOME=/home/roger
MIX_HOME=/.mix
```

...so something's screwing with the MIX_HOME environment variable in between pid 29323 and 29333...

**Comment by rlipscombe** [comment]
It looks like it was this change: https://github.com/elixir-lsp/elixir-ls/pull/78. I'd got an (apparently) broken installation of asdf hanging around, which was screwing up MIX_HOME via the `elixir` wrapper script.

Since I _don't_ use asdf (I use direnv), I just removed it, and everything seems OK now.

**Comment by axelson** [comment]
I'm glad you got it figured out!
