### ISSUE TITLE
Make Eex Language IDs compliant with guidelines?

### ISSUE THREAD

**Issue by zolrath** [elixir-lsp/vscode-elixir-ls#86]
The language identifier guidelines state that language ids should be lowercase and contain no spaces.
https://code.visualstudio.com/docs/languages/identifiers#_new-identifier-guidelines

This causes issues with displaying icons for .html.eex files as noted here:
https://github.com/vscode-icons/vscode-icons/issues/1414#issuecomment-355820539

This was requested and implemented in a Pull Request on the vscode-elixir project.
https://github.com/fr1zle/vscode-elixir/pull/114 corrects the issue but was never merged.

The largest impact of this change is that other extensions that rely on the current identifier would have to be changed for support to continue.

Was there a larger reason this change hasn't occurred? The icon issue definitely persists.

**Comment by axelson** [comment]
I think this is the first time that this issue is coming up on this specific repository. Seems like it is a necessary change, although I'm pretty it will break some people's customizations (remember seeing comments about that last time a change was made to a language id). Can you make a PR?
