### ISSUE TITLE
Parentheses get inserted incorrectly on save when strings have emoji

### ISSUE THREAD

**Issue by acdibble** [elixir-lsp/vscode-elixir-ls#88]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.3 (compiled with Erlang/OTP 21)

  * VSCode ElixirLS Fork version: 0.3.2
  * Operating System Version: linux 5.4.0-7626-generic
  
### Troubleshooting

- [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [X] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  - NOTE: This will cause you to have to re-run the entire dialyzer build

If you have the following code:
```elixir
IO.puts "🎧"
```

On save this gets formatted to:
```elixir
IO.puts("🎧)"
```

But running `mix format path/to/file.ex` gives you:
```elixir
IO.puts("🎧")
```

**Comment by axelson** [comment]
This has a tracking issue in https://github.com/elixir-lsp/elixir-ls/issues/199 any discussion should happen there or in the linked PR.

**Comment by axelson** [comment]
I'm going to keep this open to make it easier for others to find until it is fixed.

**Comment by lukaszsamson** [comment]
@axelson This can be closed now

**Comment by axelson** [comment]
Good point, thanks!

**Comment by a8t** [comment]
it's still pinned btw

**Comment by axelson** [comment]
@a8t thanks for bringing that up. I've unpinned it since this issue is solved.
