### ISSUE TITLE
Symbol search does not work

### ISSUE THREAD

**Issue by lud** [elixir-lsp/vscode-elixir-ls#89]
Command+T allows to search for modules but it seems to be the default VSC functionnality. Using prefixes like `f` or `t` does not find anything.

Otherwise the outline panel shows all symbols without problem.

* Elixir & Erlang versions (elixir --version): Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
* Elixir 1.10.2 (compiled with Erlang/OTP 22)
* VSCode ElixirLS Fork version: 0.3.2
* Operating System Version: darwin 18.7.0
* Visual studio:
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (2 wks ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

**Comment by axelson** [comment]
Can you try again on the latest version of the plugin? On that version if you disable dialyzer that is expected.

**Comment by lud** [comment]
Unfortunately I removed the plugin since it was buggy and prevented vscode to save files (somehow it was hanging while saving). I have to cleanup vscode a little bit before trying again.

**Comment by axelson** [comment]
Okay, please report back when you get a chance (although if you aren't using dialyzer you'll have to wait for a version that includes https://github.com/elixir-lsp/elixir-ls/pull/263)

**Comment by lud** [comment]
My saving problems seem to have started when I started to use dialyxir btw.

**Comment by lud** [comment]
So I just reinstalled `jakebecker.elixir-ls 0.4.0` and I have the same behaviour as usual : A list of modules but no prefixes at all.

**Comment by axelson** [comment]
That's expected since there's no release that includes https://github.com/elixir-lsp/elixir-ls/pull/263

**Comment by lud** [comment]
I installed the version from source but it does not work and the version shown in 0.4.0 …

**Comment by axelson** [comment]
Hmm, okay. What do you see in the ElixirLS output, any errors? https://github.com/elixir-lsp/vscode-elixir-ls/#check-elixirls-output

Do you see output like:
```
[ElixirLS WorkspaceSymbols] Indexing...
[ElixirLS WorkspaceSymbols] Module discovery complete
[ElixirLS WorkspaceSymbols] 19 callbacks added to index
[ElixirLS WorkspaceSymbols] 173 modules added to index
```
Perhaps it's an issue with your project directory configuration, is your mix.exs in the root of the git repo?

**Comment by nocivus** [comment]
I have the same problem on my machine. No Symbol search, and also no go to definition. Even though ElixirLS apparently indexes stuff correctly in the output tab.

**Comment by axelson** [comment]
@noozo do you get any errors listed? And what editor are you using, if you're using VSCode here's the debug instructions: https://github.com/elixir-lsp/vscode-elixir-ls#debugging

**Comment by lainor** [comment]
It works for me, I installed the extension from git but changed the tool-version to match my project. I then disabled the dialyzer and i can still search by symbol.

**Comment by StanBright** [comment]
I'm experiencing similar issues. **Go to symbol in workspace** is locating ONLY module names, but NOT functions. At the same time, "go to definition" seems to work as well as locating functions in the currently opened file. i.e. function names are correctly indexed, however not added to the "workspace index". 

I'm using v0.5.0 of the extension, Elixir 1.40.4 and VS Code 1.47.3. 

Some "interesting" logs from the ElixirLS output console:

```
[Trace - 7:00:24 am] Sending request 'initialize - (0)'.
[Trace - 7:00:25 am] Received notification 'window/logMessage'.
Started ElixirLS v0.5.0
[Trace - 7:00:25 am] Received notification 'window/logMessage'.
Elixir version: "1.10.4 (compiled with Erlang/OTP 23)"
[Trace - 7:00:25 am] Received notification 'window/logMessage'.
Erlang version: "23"
[Trace - 7:00:25 am] Received notification 'window/logMessage'.
ElixirLS compiled with Elixir 1.7.4 and erlang 20
```

Is it normal that ElixirLS was compiled with an older version of Elixir and OTP?

I've tried restarting the editor and removing the extension and restarting again; however, that didn't help. 

Any idea how I could debug further or resolve this? Thansk!

**Comment by StanBright** [comment]
I have the follow logs as well:

```
Info  - 7:46:39 am] [ElixirLS WorkspaceSymbols] 1548 modules added to index
[Info  - 7:46:39 am] [ElixirLS WorkspaceSymbols] 965 types added to index
[Info  - 7:47:08 am] [ElixirLS WorkspaceSymbols] 18446 functions added to index
[Info  - 7:47:39 am] [ElixirLS Dialyzer] Analyzing 1499 modules:
```

It seems that functions should be added to ElixirLS' WorkspaceSymbols, yet they are not listed when searching with cmd+T ¯\_(ツ)_/¯

**Comment by StanBright** [comment]
For the record, I tried compiling ElixirLS locally with Elixir 1.10.4 & OTP 23, but searching for functions in the workspace isn't working again.

**Comment by dgutov** [comment]
@StanBright Did you use the `f ` prefix?

**Comment by StanBright** [comment]
@dgutov if what you mean by `f ` prefix is to type in "f" and a space after cmd+T, well I didn't know there was such magic. I tried now though... but it din't make a difference. 

Thanks for the suggestion!

Again, "go to definition" works when I'm above a function and press "cmd+D"; however, I can't quickly search/filter by function name :/

**Comment by mattbaker** [comment]
I also ran into this when I was testing WorkspaceSymbols but didn't have time to dig in. I tried it on the Elixir LS repo itself.

**Comment by mattbaker** [comment]
I suspect this happened in VS Code v1.44

> _*Filter results by separating multiple queries with spaces*_
> _If you are getting too many results for a file search, you can add more search patterns after typing a space. For example, you can narrow down results by folder if you type <file name> <folder name> one after the other._
https://github.com/microsoft/vscode/issues/94742

I stuck some inspect statements in to the workspace symbol provider and it looks like anything after a space never makes it to the language server

**Comment by lukaszsamson** [comment]
@axelson @lud we can close it now as query prefix feature was removed

**Comment by lud** [comment]
Sure :)
