### ISSUE TITLE
Set up ElixirLS fork for Visual Studio Marketplace

### ISSUE THREAD

**Issue by balduncle** [elixir-lsp/vscode-elixir-ls#9]
In an effort to get this project revitalized, I am setting things up for publishing to the marketplace before I start trying to merge in any fixes or features.  I want the published extension to be clearly labeled as a fork of Jake's work but I also want to be set up so that, if we end up being viable long term, we don't have code and settings littered with `fork` for example.  Here is what I propose.

1. We use elixir-lsp (display name Elixir Language Server Protocol) as the publisher.  Sticking with this as our org name and publisher name feels like consistent branding that should help users understand where it came from.  Alternatively we switch to just ElixirLS (I grabbed the `elixir-ls` org if needed) since this is the language server not the protocol, but that's not super important.
2. We use elixir-ls for the package name, making the full package id be `elixir-lsp.elixir-ls` or `elixir-ls.elixir-ls` if we dropped the `P`.
3. We use something like "ElixirLS Fork: ..." as the display name of the extension, so that anyone who finds us in the marketplace knows right away that this is a fork and isn't misled if they were trying to find Jake's extension.
4. We ensure that the README as displayed on the extension's entry in the marketplace clearly calls out Jake's great work and the reason for the fork, and points people to Jake's extension if that is what they were looking for.
5. We use `ElixirLS` for the `langId` as opposed to Jake's `elixirLS`.  This is very similar I know, but it is different enough to not squash config people are using from his extension and doesn't require that `fork` or similar be left in settings for users of this fork.
6. We use "ElixirLS" and not "ElixirLS Fork" in the UI labels.  It seems unlikely that someone will have both extensions installed at the same time so it doesn't feel necessary to call out fork in those labels.

@JakeBecker I'd love to hear your opinion on this if you can spare the time.  I don't want to do anything disrespectful to your work and hope to help this thrive for the sake of the community.

Anyone else have an opinion? @axelson? @msaraiva?

**Comment by balduncle** [comment]
Another option for number 5 is to use `elixir` as the `langId` per https://github.com/JakeBecker/vscode-elixir-ls/issues/139.  I shied away from this because it feels too broad, but I'm researching to see if this is what we are supposed to do at least for any setting that should be handled by any language server for elixir.

**Comment by axelson** [comment]
I agree with the majority of what you wrote (especially trying not to have to maintain the name "fork" indefinitely).

I'm not as sure about 5 and 6. For 5, I'm not sure what the typical `langId` setting is for VSCode. With `ElixirLS` I'm worried about people missing the capitalization difference (as you mentioned). I guess I'm not _too_ worried about "squashing" existing config since most of it will be portable at first. But overall, I think I net out that if this is truly a "language id" then `elixir` would make sense. But I would definitely be swayed by a better understanding of how `langId` is used in VSCode!

For 6, if this is just a display label I think it would be nice for it to be different than just "ElixirLS". How about "ElixirLS (elixir-lsp)"? That would be in keeping with our consistent branding and the org name. In the future we could drop the suffix if we wanted to, but it's nice to be able to tell at a glance which version is installed, especially if you are looking at a friends or co-workers install. But I may be confusing 3 with 6. So actually it sounds like "ElixirLS" for 6 is good, but I do like my proposed label slightly better for 3.

**Comment by balduncle** [comment]
Based on the use `languageServerExample` for `langId` at [https://code.visualstudio.com/api/language-extensions/language-server-extension-guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) I’m guessing this doesn’t need to be the language name.  Another advantage to using the same `langId` is that it would be easier to merge the projects back together later if Jake decided that was desirable, which seems to me like what we should always aim for. So I think I’m in favor of using `elixirLS` as the `langId`.

For your comment on 6, I'm referring to labels within the already installed extension, where it would be really ugly to include text like `fork` or `elixir-lsp` next to every setting.  I'm convinced we shouldn't do so there.

Perhaps your referring more to 4 though, the display name when you search for the extension or see your list of installed extensions.  I feel like calling out `fork` in the display name is clearer than `elixir-lsp`. The publisher name will already make that clear, and IMO people are more likely to understand fork as a differentiator over Jake's `ElixirLS: ...` entry.

So at https://marketplace.visualstudio.com/search?term=elixirls&target=VSCode&category=All%20categories&sortBy=Relevance you would see Jake's entry and ours would say `ElixirLS Fork: Elixir support and debugger` and where you see `Jake Becker` there you would instead see our publisher name, like `elixir-lsp`.

**Comment by balduncle** [comment]
I just published so you can see what it would look like next to Jake's.  Take a look.

https://marketplace.visualstudio.com/search?term=elixirls&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by balduncle** [comment]
I've removed the published version in the meantime to ensure no one is misled.  Here's what it looked like though.

<img width="716" alt="Screen Shot 2019-08-31 at 3 25 30 PM" src="https://user-images.githubusercontent.com/25121264/64068849-b844de00-cc03-11e9-9ff4-bea7d8454bdf.png">

<img width="1241" alt="Screen Shot 2019-08-31 at 3 25 38 PM" src="https://user-images.githubusercontent.com/25121264/64068850-c1ce4600-cc03-11e9-9b26-b8b3a1be3d63.png">

**Comment by axelson** [comment]
Okay, I think we are on the same page. Thanks for taking the screenshots, it's helpful to see what it will look like visually.

**Comment by JakeBecker** [comment]
Hi, thanks for your work on this. I no problem with you guys publishing the fork on the VS marketplace. My life's gotten very busy -- I'm getting married next month, among other things -- and I haven't been able to spare much headspace for ElixirLS.

But! I'm discussing a job offer with a company that would allow me to spend a significant amount of time at work maintaining ElixirLS. If all goes well, I may be back to maintaining it properly by the end of the year. If that happens, I'll probably start by trying to catch up with this fork.

Regardless, please feel free to publish, and thank you for your work!

**Comment by balduncle** [comment]
@JakeBecker congratulations on getting married soon, and man, that would be fabulous if you were paid to keep working on ElixirLS!  I look forward to hearing more.

**Comment by balduncle** [comment]
I have published v0.2.26 to the vscode marketplace now.

**Comment by axelson** [comment]
@JakeBecker Congrats on getting married! That's very exciting, and very busy :) I hope you get that job and get paid to work on ElixirLS, that would be awesome 🎉
