### ISSUE TITLE
Leex syntax highlighting not working v 0.3.3 on WSL Ubuntu

### ISSUE THREAD

**Issue by sensiblearts** [elixir-lsp/vscode-elixir-ls#91]
### Environment

Erlang/OTP 22 [erts-10.4.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.10.0-dev (495148e) (compiled with Erlang/OTP 20)

VSCode ElixirLS Fork version: 0.3.3

Operating System Version: 
Microsoft Windows [Version 10.0.18362.720]
**WSL**:
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"

### Problem

**No syntax highlighting** for **\*.LEEX** files  (But changelog says it does.)

Highlight works fine on *.EEX files.

I read [https://thinkingelixir.com/vs-code-broken-for-elixir/](https://thinkingelixir.com/vs-code-broken-for-elixir/) but nothing there works, either.

Ideas?

Thanks.

**Comment by sensiblearts** [comment]
SORRY.  Had to edit Settings. Seems like that should be default.
  "files.associations": {
    "*.eex": "HTML (EEx)",
    "*.leex": "HTML (EEx)"
  },

**Comment by axelson** [comment]
It will be the default in the next released version. See #82 

Not sure when the next release will be, maybe this weekend.
