### ISSUE TITLE
Debugger does not properly use the asdf environment

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/vscode-elixir-ls#92]
Currently the debugger appears to launch with an unstable CWD, and since the asdf environment is loaded based on the CWD the asdf environment loaded may not match the project.

Looking at the VSCode docs: https://code.visualstudio.com/api/extension-guides/debugger-extension
I don't see a way to control what the CWD of the `debugger.sh` script or a way to pass the `projectDir` to the script. So I'm not sure what an easy fix to this issue is.

**Comment by jayjun** [comment]
To add, the current working directory used is wherever `code .` is launched from. When launched from the macOS Dock, it is `/`.

**Comment by tuomohopia** [comment]
@jayjun your comment was such a saver! I had a hard time figuring out why ElixirLS failed to launch on VSCode but your tip fixed it. It works fine when launched from Dock, just not from shell via `code .`.
