### ISSUE TITLE
Feature: Good support for eex/leex files

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/vscode-elixir-ls#98]
If VSCode had direct support for universally embedding languages that would be ideal, but it's currently on the backlog:
* https://github.com/microsoft/vscode/issues/1751
* This [comment](https://github.com/microsoft/vscode/issues/1751#issuecomment-573886529) on the above issue has an example of embedding that is possible today

You can embed syntax highlighting, this might be the lowest hanging fruit:
https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages

You can also embed support for another language server:
https://code.visualstudio.com/api/language-extensions/embedded-languages

If you use tailwind css, this extension has support for eex (and leex?) files, and might be a good source of inspiration:
https://github.com/bradlc/vscode-tailwindcss

**Comment by axelson** [comment]
Semi-related issue: https://github.com/elixir-lsp/vscode-elixir-ls/issues/21

**Comment by bdtomlin** [comment]
Thanks for the reply. I was not aware that universal embedding wasn't supported, and judging by the age of that issue it's definitely not a priority. I'll have to spend some time reading in detail to see if there is a reasonable solution in the near term.

**Comment by lukaszsamson** [comment]
Closing this as it's too broad to be actionable. If anyone has a specific ideas on what needs improvement then please open a separate issue.
Basic elixir features like completions, hover, definition work fine. Variables defined in template does not (I opened https://github.com/elixir-lsp/vscode-elixir-ls/issues/279). HTML/CSS/JS completions does not (I opened https://github.com/elixir-lsp/vscode-elixir-ls/issues/278 to track that).
